// BELTANEE v6.1 — unified application loading screen
let shown=false;
const STYLE_ID='beltanee-loader-style';
function installStyles(){if(document.getElementById(STYLE_ID))return;const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`#beltaneeLoadingScreen{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:radial-gradient(circle at 50% 42%,rgba(124,58,237,.16),transparent 28%),linear-gradient(135deg,#151021,#0f1115);opacity:1;visibility:visible;transition:opacity .45s ease,visibility .45s ease}#beltaneeLoadingScreen.beltanee-loader-hidden{opacity:0;visibility:hidden;pointer-events:none}.beltanee-loader-shell{width:min(380px,82vw);text-align:center;color:#fff;animation:beltaneeLoaderIn .7s cubic-bezier(.2,.8,.2,1) both}.beltanee-loader-mark{width:70px;height:70px;margin:0 auto 18px;border:1px solid rgba(255,255,255,.18);border-radius:20px;display:grid;place-items:center;background:linear-gradient(145deg,rgba(255,255,255,.1),rgba(255,255,255,.025));box-shadow:0 18px 60px rgba(0,0,0,.32),0 0 50px rgba(124,58,237,.16)}.beltanee-loader-mark span{font-size:31px;font-weight:800;letter-spacing:-.06em}.beltanee-loader-brand{font-size:19px;font-weight:800;letter-spacing:.28em;margin-left:.28em}.beltanee-loader-subtitle{margin-top:8px;font-size:12px;letter-spacing:.08em;color:rgba(255,255,255,.52)}.beltanee-loader-line{height:2px;background:rgba(255,255,255,.1);border-radius:99px;overflow:hidden;margin:28px 0 12px}.beltanee-loader-line i{display:block;height:100%;width:42%;border-radius:99px;background:linear-gradient(90deg,#7c3aed,#ec4899);animation:beltaneeLoaderProgress 1.35s ease-in-out infinite}.beltanee-loader-status{font-size:11px;color:rgba(255,255,255,.5);min-height:16px}@keyframes beltaneeLoaderIn{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}@keyframes beltaneeLoaderProgress{0%{transform:translateX(-140%)}50%{transform:translateX(170%)}100%{transform:translateX(360%)}}`;document.head.appendChild(style)}
function ensureLoadingScreen(){installStyles();if(document.getElementById('beltaneeLoadingScreen'))return document.getElementById('beltaneeLoadingScreen');const el=document.createElement('div');el.id='beltaneeLoadingScreen';el.innerHTML='<div class="beltanee-loader-shell" role="status" aria-live="polite"><div class="beltanee-loader-mark"><span>B</span></div><div class="beltanee-loader-brand">BELTANEE</div><div class="beltanee-loader-subtitle">Аналитическая платформа</div><div class="beltanee-loader-line"><i></i></div><div class="beltanee-loader-status" id="beltaneeLoadingStatus">Подготавливаем рабочее пространство…</div></div>';document.body.appendChild(el);return el}
export function showLoading(message='Подготавливаем рабочее пространство…'){const el=ensureLoadingScreen();el.querySelector('#beltaneeLoadingStatus').textContent=message;el.classList.remove('beltanee-loader-hidden');shown=true}
export function setLoadingMessage(message){const el=document.getElementById('beltaneeLoadingScreen');if(el)el.querySelector('#beltaneeLoadingStatus').textContent=message}
export function hideLoading(){const el=document.getElementById('beltaneeLoadingScreen');if(!el||!shown)return;el.classList.add('beltanee-loader-hidden');setTimeout(()=>el.remove(),500);shown=false}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>showLoading(),{once:true});else showLoading();
