import * as DB from './db.js';
import {session,listShops,createShop,setActiveShop,activeShop,listUsers,createUser,setActive,changePassword,pendingAuthEvents,confirmAuthEvent} from './userAuth.js';

const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const stores=Array.isArray(DB.STORES)?DB.STORES:[];
const state={open:false};

function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportJson(){download(`bjob-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:2,createdAt:new Date().toISOString(),data:await DB.snapshot()},null,2))}
async function importJson(file){const parsed=JSON.parse(await file.text());if(!parsed?.data||typeof parsed.data!=='object')throw new Error('Это не резервная копия B-JOB JSON.');const names=Object.keys(parsed.data).filter(x=>stores.includes(x));if(!names.length)throw new Error('В JSON нет поддерживаемых таблиц B-JOB.');if(!confirm(`Импортировать ${names.length} разделов базы?\nТекущие данные этих разделов будут заменены.`))return;for(const name of names)if(Array.isArray(parsed.data[name]))await DB.replaceMany(name,parsed.data[name]);location.reload()}
function filePicker(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>i.files[0]&&importJson(i.files[0]).catch(e=>alert(e.message));i.click()}
function inject(){if(document.getElementById('bjob-admin-panel-style'))return;const s=document.createElement('style');s.id='bjob-admin-panel-style';s.textContent=`
.bjob-admin-panel{position:sticky;top:0;z-index:5000;display:flex;align-items:center;gap:10px;padding:10px 18px;background:#11151c;color:#fff;border-bottom:1px solid #2a303a;box-shadow:0 4px 18px #0002;font:14px Inter,system-ui,sans-serif}.bjob-admin-panel .title{font-weight:700;margin-right:auto}.bjob-admin-panel button,.bjob-admin-panel select{border:1px solid #39414d;background:#1a2029;color:#fff;border-radius:8px;padding:8px 11px;cursor:pointer}.bjob-admin-panel button:hover{background:#242c37}.bjob-admin-panel .primary{background:#fff;color:#111;border-color:#fff}.bjob-admin-modal{position:fixed;inset:0;z-index:10000;background:#0008;display:grid;place-items:center;padding:20px;font:14px Inter,system-ui,sans-serif}.bjob-admin-card{width:min(1100px,96vw);max-height:88vh;overflow:auto;background:#fff;color:#111;border-radius:16px;padding:22px;box-shadow:0 24px 70px #0005}.bjob-admin-card h2{margin:0 0 14px}.bjob-admin-grid{display:grid;gap:10px}.bjob-admin-card input,.bjob-admin-card select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #cdd2da;border-radius:8px}.bjob-admin-card label{display:grid;gap:5px}.bjob-admin-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:16px}.bjob-admin-actions button{padding:9px 13px;border-radius:8px;border:1px solid #ccd1d8;background:#fff;cursor:pointer}.bjob-admin-actions .primary{background:#111;color:#fff;border-color:#111}.bjob-admin-table{width:100%;border-collapse:collapse}.bjob-admin-table th,.bjob-admin-table td{padding:9px;border-bottom:1px solid #e6e8ec;text-align:left;vertical-align:top}.bjob-admin-chip{display:inline-flex;padding:3px 7px;border-radius:999px;background:#eef1f5;margin:2px}.bjob-admin-notice{padding:10px;border-radius:9px;background:#fff7d6;margin-bottom:14px}
`;document.head.appendChild(s)}
function modal(title,body){const root=document.createElement('div');root.className='bjob-admin-modal';root.innerHTML=`<div class="bjob-admin-card"><h2>${title}</h2>${body}</div>`;document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target===root)root.remove()});return root}
async function shops(){const rows=await listShops();const w=modal('Магазины',`<p>Создавайте несколько магазинов WB и Ozon и переключайтесь между ними. Данные привязываются к активному магазину.</p><div class="bjob-admin-actions"><button class="primary" data-add>+ Добавить магазин</button><button data-close>Закрыть</button></div><table class="bjob-admin-table"><thead><tr><th>Название</th><th>Маркетплейс</th><th>Статус</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.marketplace==='wb'?'Wildberries':'Ozon'}</td><td>${x.active!==false?'Активен':'Отключён'}</td><td><button data-select="${esc(x.id)}">Выбрать</button></td></tr>`).join('')||'<tr><td colspan="4">Магазинов пока нет.</td></tr>'}</tbody></table>`);w.querySelector('[data-close]').onclick=()=>w.remove();w.querySelector('[data-add]').onclick=()=>addShop(w);w.onclick=async e=>{const b=e.target.closest('[data-select]');if(!b)return;await setActiveShop(b.dataset.select);w.remove();location.reload()}}
function addShop(parent){const w=modal('Создать магазин',`<form class="bjob-admin-grid"><label>Название<input name="name" placeholder="WB1" required></label><label>Маркетплейс<select name="marketplace"><option value="wb">Wildberries</option><option value="ozon">Ozon</option></select></label><div class="bjob-admin-actions"><button type="button" data-close>Отмена</button><button class="primary">Создать</button></div></form>`);w.querySelector('[data-close]').onclick=()=>w.remove();w.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{const s=await createShop({name:f.name.value.trim(),marketplace:f.marketplace.value});await setActiveShop(s.id);w.remove();parent.remove();shops();location.reload()}catch(err){alert(err.message)}}}
async function users(){const [users,shops,pending]=await Promise.all([listUsers(),listShops(),pendingAuthEvents()]);const w=modal('Пользователи и доступы',`<div class="bjob-admin-notice"><b>Новые авторизации: ${pending.length}</b>${pending.slice(0,10).map(x=>`<div>${esc(x.name)} · ${esc(x.login)} · ${new Date(x.date).toLocaleString('ru-RU')} <button data-confirm="${esc(x.id)}">Подтвердить</button></div>`).join('')||'<div>Новых авторизаций нет.</div>'}</div><div class="bjob-admin-actions"><button class="primary" data-add>+ Добавить сотрудника</button><button data-close>Закрыть</button></div><table class="bjob-admin-table"><thead><tr><th>Логин</th><th>Имя</th><th>Роль</th><th>Магазины</th><th>Статус</th><th>Последний вход</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${esc(u.login)}</b></td><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${u.login==='ADMIN'?'Все':(u.shopIds||[]).map(id=>shops.find(s=>s.id===id)?.name).filter(Boolean).join(', ')||'—'}</td><td>${u.active!==false?'Активен':'Заблокирован'}</td><td>${esc(u.lastLoginAt||'—')}</td><td>${u.login==='ADMIN'?'—':`<button data-toggle="${esc(u.id)}">${u.active!==false?'Заблокировать':'Разблокировать'}</button><button data-pass="${esc(u.id)}">Пароль</button>`}</td></tr>`).join('')}</tbody></table>`);w.querySelector('[data-close]').onclick=()=>w.remove();w.querySelector('[data-add]').onclick=()=>addUser(w,shops);w.onclick=async e=>{const c=e.target.closest('[data-confirm]');if(c){await confirmAuthEvent(c.dataset.confirm);w.remove();users();return}const t=e.target.closest('[data-toggle]');if(t){const u=users.find(x=>x.id===t.dataset.toggle);await setActive(t.dataset.toggle,u?.active===false);w.remove();users();return}const p=e.target.closest('[data-pass]');if(p){const password=prompt('Новый пароль, минимум 8 символов:');if(password){try{await changePassword(p.dataset.pass,password);alert('Пароль изменён.')}catch(err){alert(err.message)}}}}}
function addUser(parent,shops){const checks=shops.map(s=>`<label><input type="checkbox" name="shopIds" value="${esc(s.id)}"> ${esc(s.name)} · ${s.marketplace==='wb'?'WB':'Ozon'}</label>`).join('');const w=modal('Создать сотрудника',`<form class="bjob-admin-grid"><label>Имя<input name="name" required></label><label>Логин<input name="login" required></label><label>Роль<select name="role"><option value="warehouse">Склад</option><option value="manager">Менеджер</option><option value="production">Производство</option><option value="manager">Руководитель</option></select></label><div><b>Доступ к магазинам</b>${checks||'<p>Сначала создайте магазин.</p>'}</div><label><input type="checkbox" name="invite"> Сформировать пригласительный код</label><div class="bjob-admin-actions"><button type="button" data-close>Отмена</button><button class="primary">Создать</button></div></form>`);w.querySelector('[data-close]').onclick=()=>w.remove();w.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,fd=new FormData(f);try{const r=await createUser({name:fd.get('name'),login:fd.get('login'),role:fd.get('role'),shopIds:fd.getAll('shopIds'),permissions:{sections:{fbs:['view','scan','update'],warehouses:['view']}},invite:fd.has('invite')});alert(`Пользователь создан.\n\nЛогин: ${r.login}\nОдноразовый пароль: ${r.temporaryPassword}${r.inviteCode?`\nПригласительный код: ${r.inviteCode}`:''}`);w.remove();parent.remove();users()}catch(err){alert(err.message)}}}
async function install(){inject();let last='';for(let i=0;i<60;i++){const s=session();if(s){if(s.role==='admin')mount(s);return}await new Promise(r=>setTimeout(r,500))}}
async function mount(s){if(document.querySelector('.bjob-admin-panel'))return;const panel=document.createElement('div');panel.className='bjob-admin-panel';panel.innerHTML='<span class="title">Администрирование B-JOB</span><button data-shops>Магазины</button><button data-users>Пользователи</button><button data-export>Экспорт JSON</button><button data-import>Импорт JSON</button><button data-refresh>Обновить</button>';document.body.prepend(panel);panel.querySelector('[data-shops]').onclick=shops;panel.querySelector('[data-users]').onclick=users;panel.querySelector('[data-export]').onclick=exportJson;panel.querySelector('[data-import]').onclick=filePicker;panel.querySelector('[data-refresh]').onclick=()=>location.reload()}
install();