import * as DB from '../db.js';
import {session,listShops,createShop,setActiveShop,listUsers,createUser,setActive,changePassword,pendingAuthEvents,confirmAuthEvent,setUserAccess} from './userAuth.js';

const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const admin=()=>session()?.role==='admin';

function modal(title,html){const r=document.createElement('div');r.className='bjob-admin-modal';r.innerHTML=`<div class="bjob-admin-card"><h2>${esc(title)}</h2>${html}</div>`;document.body.appendChild(r);r.onclick=e=>{if(e.target===r)r.remove()};return r}
function css(){if(document.getElementById('bjob-admin-fixed-css'))return;const s=document.createElement('style');s.id='bjob-admin-fixed-css';s.textContent='.bjob-admin-fixed{position:fixed;right:18px;top:84px;z-index:12000;display:flex;gap:7px;align-items:center;padding:8px 10px;background:#111827;color:#fff;border-radius:12px;box-shadow:0 12px 35px #0002}.bjob-admin-fixed button{border:1px solid #374151;background:#1f2937;color:#fff;border-radius:8px;padding:8px 10px;cursor:pointer}.bjob-admin-modal{position:fixed;inset:0;z-index:13000;background:#0008;display:grid;place-items:center;padding:18px}.bjob-admin-card{width:min(1100px,96vw);max-height:90vh;overflow:auto;background:#fff;color:#111;border-radius:16px;padding:22px}.bjob-admin-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin:14px 0}.bjob-admin-actions button{border:1px solid #ccd1d8;background:#fff;border-radius:8px;padding:9px 12px;cursor:pointer}.bjob-admin-actions .primary{background:#111;color:#fff}.bjob-admin-table{width:100%;border-collapse:collapse}.bjob-admin-table th,.bjob-admin-table td{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left}.bjob-admin-form{display:grid;gap:10px}.bjob-admin-form label{display:grid;gap:5px}.bjob-admin-form input,.bjob-admin-form select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #ccd1d8;border-radius:8px}.bjob-admin-note{padding:10px;border-radius:9px;background:#fff7d6;margin-bottom:12px}.bjob-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.bjob-admin-grid section{border:1px solid #e5e7eb;border-radius:12px;padding:14px}@media(max-width:700px){.bjob-admin-grid{grid-template-columns:1fr}.bjob-admin-fixed{left:12px;right:12px;top:76px;overflow:auto}}';document.head.appendChild(s)}

async function exportJson(){
  const data=await DB.snapshot();
  if(window.BJobDesktop?.exportJson){const result=await window.BJobDesktop.exportJson(data);if(!result?.cancelled)alert('Резервная копия сохранена.');return result;}
  const payload={format:'bjob-json',version:2,createdAt:new Date().toISOString(),data};
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='BJOB-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return payload;
}

function importJson(){
  if(window.BJobDesktop?.importJson){window.BJobDesktop.importJson().then(async result=>{if(result?.cancelled)return;if(!result?.data)throw new Error('В резервной копии нет данных.');for(const n of Object.keys(result.data).filter(n=>DB.STORES.includes(n)))if(Array.isArray(result.data[n]))await DB.replaceMany(n,result.data[n]);location.reload();}).catch(e=>alert(e.message||'Не удалось импортировать резервную копию.'));return;}
  const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{if(!i.files?.[0])return;const p=JSON.parse(await i.files[0].text());const data=p?.data&&typeof p.data==='object'?p.data:p;if(!data||typeof data!=='object')throw Error('Неверный файл B-JOB.');const names=Object.keys(data).filter(n=>DB.STORES.includes(n));if(!names.length)throw Error('В файле нет таблиц B-JOB.');if(!confirm('Импортировать '+names.length+' таблиц? Текущие данные этих таблиц будут заменены.'))return;for(const n of names)if(Array.isArray(data[n]))await DB.replaceMany(n,data[n]);location.reload();}catch(e){alert(e.message||'Ошибка импорта.')}};i.click();
}

async function shops(){if(!admin())return;const rows=await listShops();const r=modal('Магазины','<p>Создайте магазины и переключайте активный.</p><div class="bjob-admin-actions"><button class="primary" data-add>+ Добавить магазин</button><button data-close>Закрыть</button></div><table class="bjob-admin-table"><thead><tr><th>Название</th><th>Маркетплейс</th><th>Статус</th><th></th></tr></thead><tbody>'+rows.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.marketplace==='wb'?'Wildberries':'Ozon'}</td><td>${x.active===false?'Отключён':'Активен'}</td><td><button data-select="${esc(x.id)}">Выбрать</button></td></tr>`).join('')||'<tr><td colspan="4">Магазинов пока нет.</td></tr>'+'</tbody></table>');r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('[data-add]').onclick=()=>addShop(r);r.onclick=async e=>{const b=e.target.closest('[data-select]');if(b){await setActiveShop(b.dataset.select);location.reload()}}}
function addShop(parent){const r=modal('Создать магазин','<form class="bjob-admin-form"><label>Название<input name="name" placeholder="WB1" required></label><label>Маркетплейс<select name="marketplace"><option value="wb">Wildberries</option><option value="ozon">Ozon</option></select></label><div class="bjob-admin-actions"><button type="button" data-close>Отмена</button><button class="primary">Создать</button></div></form>');r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const f=e.target,s=await createShop({name:f.name.value.trim(),marketplace:f.marketplace.value});await setActiveShop(s.id);location.reload()}catch(err){alert(err.message)}}}

async function users(){if(!admin())return;const [rows,shopsRows,pending]=await Promise.all([listUsers(),listShops(),pendingAuthEvents()]);const r=modal('Сотрудники','<div class="bjob-admin-note"><b>Новые авторизации: '+pending.length+'</b>'+pending.map(x=>`<div>${esc(x.name)} · ${esc(x.login)} <button data-confirm="${esc(x.id)}">Подтвердить</button></div>`).join('')+'</div><div class="bjob-admin-actions"><button class="primary" data-add>+ Создать сотрудника</button><button data-close>Закрыть</button></div><table class="bjob-admin-table"><thead><tr><th>Логин</th><th>Имя</th><th>Роль</th><th>Магазины</th><th>Статус</th><th>Последний вход</th><th></th></tr></thead><tbody>'+rows.map(u=>`<tr><td>${esc(u.login)}</td><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${u.login==='ADMIN'?'Все':(u.shopIds||[]).map(id=>shopsRows.find(s=>s.id===id)?.name).filter(Boolean).join(', ')||'—'}</td><td>${u.active===false?'Заблокирован':'Активен'}</td><td>${esc(u.lastLoginAt||'—')}</td><td>${u.login==='ADMIN'?'—':`<button data-toggle="${esc(u.id)}">${u.active===false?'Разблокировать':'Заблокировать'}</button> <button data-pass="${esc(u.id)}">Пароль</button> <button data-access="${esc(u.id)}">Права</button>`}</td></tr>`).join('')+'</tbody></table>');r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('[data-add]').onclick=()=>addUser(r,shopsRows);r.onclick=async e=>{const c=e.target.closest('[data-confirm]');if(c){await confirmAuthEvent(c.dataset.confirm);r.remove();users();return}const t=e.target.closest('[data-toggle]');if(t){const u=rows.find(x=>x.id===t.dataset.toggle);if(u)await setActive(u.id,u.active===false);r.remove();users();return}const p=e.target.closest('[data-pass]');if(p){const value=prompt('Новый пароль, минимум 8 символов:');if(value)try{await changePassword(p.dataset.pass,value);alert('Пароль изменён.')}catch(err){alert(err.message)}return}const a=e.target.closest('[data-access]');if(a){const u=rows.find(x=>x.id===a.dataset.access);if(u)accessModal(u,shopsRows,r)}}}
function addUser(parent,shopsRows){const checks=shopsRows.map(s=>`<label><input type="checkbox" name="shopIds" value="${esc(s.id)}"> ${esc(s.name)} · ${s.marketplace==='wb'?'WB':'Ozon'}</label>`).join('');const r=modal('Создать сотрудника',`<form class="bjob-admin-form"><label>Имя<input name="name" required></label><label>Логин<input name="login" required></label><label>Роль<select name="role"><option value="warehouse">Склад</option><option value="manager">Менеджер</option><option value="leader">Руководитель</option><option value="production">Производство</option></select></label><div><b>Магазины</b>${checks||'<p>Сначала создайте магазин.</p>'}</div><div class="bjob-admin-actions"><button type="button" data-close>Отмена</button><button class="primary">Создать</button></div></form>`);r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const f=e.target,x=await createUser({name:f.name.value.trim(),login:f.login.value.trim(),role:f.role.value,shopIds:[...f.querySelectorAll('[name="shopIds"]:checked')].map(v=>v.value),permissions:{sections:{fbs:['view','scan','update'],warehouses:['view']}}});alert('Пользователь создан.\nЛогин: '+x.login+'\nОдноразовый пароль: '+x.temporaryPassword);r.remove();parent.remove();users()}catch(err){alert(err.message)}}}
function accessModal(user,shopsRows,parent){const r=modal('Права: '+user.login,`<form class="bjob-admin-form"><label>Роль<select name="role"><option value="warehouse">Склад</option><option value="manager">Менеджер</option><option value="leader">Руководитель</option><option value="production">Производство</option></select></label><div><b>Магазины</b>${shopsRows.map(s=>`<label><input type="checkbox" name="shopIds" value="${esc(s.id)}" ${(user.shopIds||[]).includes(s.id)?'checked':''}> ${esc(s.name)} · ${s.marketplace==='wb'?'WB':'Ozon'}</label>`).join('')}</div><div class="bjob-admin-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`);r.querySelector('[name="role"]').value=user.role;r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await setUserAccess(user.id,{role:e.target.role.value,shopIds:[...e.target.querySelectorAll('[name="shopIds"]:checked')].map(x=>x.value)});r.remove();parent.remove();users()}catch(err){alert(err.message)}}}

async function organization(){if(!admin())return;const org=await DB.get('settings','organization');const usersRows=await listUsers();const shopsRows=await listShops();const r=modal('Организация и права',`<div class="bjob-admin-grid"><section><h3>${esc(org?.name||'B-JOB')}</h3><p>Пользователи: <b>${usersRows.length}</b></p><p>Магазины: <b>${shopsRows.length}</b></p><p>Главный аккаунт ADMIN не может быть заблокирован обычными действиями интерфейса.</p></section><section><h3>Резервная копия</h3><p>JSON содержит локальную базу и подходит для переноса между установками.</p><div class="bjob-admin-actions"><button class="primary" data-export>Экспорт JSON</button><button data-import>Импорт JSON</button></div></section></div><div class="bjob-admin-actions"><button data-close>Закрыть</button></div>`);r.querySelector('[data-close]').onclick=()=>r.remove();r.querySelector('[data-export]').onclick=exportJson;r.querySelector('[data-import]').onclick=importJson}

function mount(){if(!admin()||document.querySelector('.bjob-admin-fixed'))return;css();const b=document.createElement('div');b.className='bjob-admin-fixed';b.innerHTML='<strong>ADMIN · Управление</strong><button data-shops>Магазины</button><button data-users>Сотрудники</button><button data-org>Организация</button><button data-export>Экспорт JSON</button><button data-import>Импорт JSON</button>';document.body.appendChild(b);b.querySelector('[data-shops]').onclick=shops;b.querySelector('[data-users]').onclick=users;b.querySelector('[data-org]').onclick=organization;b.querySelector('[data-export]').onclick=exportJson;b.querySelector('[data-import]').onclick=importJson)}
function boot(){css();const tick=()=>{if(admin())mount()};tick();window.addEventListener('bjob:auth-ready',tick);setInterval(tick,700)}
boot();
