import * as DB from '../db.js';
import {unitEconomics,spp,productionPlan} from './core/calculations.js';
import {IMPORT_TEMPLATES} from './core/importTemplates.js';
import {createWarehouse,createProductionRequest} from './domain/warehouse.js';

const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${(Number(v)||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₽`;
const num=v=>(Number(v)||0).toLocaleString('ru-RU');
const state={page:'overview',loading:false};
const groups={Обзор:['overview','analytics','reports'],Товары:['products','unit'],Логистика:['warehouses','shipments','fbs'],Маркетинг:['advertising'],Управление:['production','api','import','settings']};
const titles={overview:'Обзор',analytics:'Аналитика',reports:'Отчёты',products:'Товары',unit:'Юнит-экономика',warehouses:'Склады',shipments:'Поставки',fbs:'FBS',advertising:'Реклама',production:'Производство',api:'WB API',import:'Импорт данных',settings:'Личный кабинет'};
async function data(){const names=['products','sales','stocks','ads','expenses','fbs','warehouses','shipments','productionOrders','apiConnections'];const o={};for(const n of names)o[n]=await DB.all(n);return o;}
function nav(){return Object.entries(groups).map(([g,items])=>`<div class="bjob-group"><span>${g}</span>${items.map(id=>`<button data-page="${id}" class="${state.page===id?'active':''}">${titles[id]}</button>`).join('')}</div>`).join('');}
function shell(){return `<div class="bjob"><header><div class="brand"><strong>B-JOB</strong><small>Business operating system</small></div><div class="workspace">Рабочее пространство <b>BELTANEE</b></div><div><button class="btn secondary" data-page="import">Импорт</button><button class="user" data-page="settings">Oleg</button></div></header><nav>${nav()}</nav><main id="view"></main><div id="modal"></div><div id="toast"></div></div>`;}
function k(label,value,meta=''){return `<div class="metric"><span>${label}</span><strong>${value}</strong><small>${meta}</small></div>`;}
function empty(title,text,action=''){return `<section class="bjob-empty"><div class="empty-line"></div><h2>${title}</h2><p>${text}</p>${action}</section>`;}
function table(head,rows,emptyText='Нет данных'){return `<div class="bjob-table"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${head.length}" class="empty-cell">${emptyText}</td></tr>`}</tbody></table></div>`;}
async function overview(){const d=await data(),orders=d.sales.reduce((s,x)=>s+Number(x.orders||0),0),rev=d.sales.reduce((s,x)=>s+Number(x.amount||0),0),stock=d.stocks.reduce((s,x)=>s+Number(x.available||0),0),ads=d.ads.reduce((s,x)=>s+Number(x.spent||0),0);return `<div class="hero"><div><small>BUSINESS CONTROL</small><h1>Весь товарооборот в одной системе.</h1><p>Товары, продажи, реклама, финансы, склады, производство и FBS без разрозненных таблиц.</p></div><button class="btn primary" data-page="analytics">Открыть аналитику</button></div><div class="metrics">${k('Заказы',num(orders),'фактические данные')}${k('Выручка',money(rev),'фактические данные')}${k('Остаток',num(stock),'по загруженным складам')}${k('Реклама',money(ads),'фактический расход')}</div><div class="section"><h2>Состояние системы</h2><div class="status-grid">${[['Товары',d.products.length,'Карточек'],['Продажи',d.sales.length,'Записей'],['Склады',d.warehouses.length,'Складов'],['FBS',d.fbs.length,'Заказов'],['API',d.apiConnections.length,'Подключений']].map(x=>`<div><span>${x[0]}</span><b>${num(x[1])}</b><small>${x[2]}</small></div>`).join('')}</div></div>`;}
async function products(){const d=await data();if(!d.products.length)return empty('Каталог готов','Создайте карточку вручную или загрузите шаблон номенклатуры.','<button class="btn primary" data-add-product>Создать карточку</button>');const map=new Map();d.products.forEach(p=>{const a=p.article||p.id;if(!map.has(a))map.set(a,[]);map.get(a).push(p)});const rows=[...map].map(([a,v])=>{const p=v[0],stock=d.stocks.filter(x=>x.article===a).reduce((s,x)=>s+Number(x.available||0),0);return `<tr><td><b>${esc(a)}</b></td><td>${esc(p.name||'Без названия')}</td><td>${v.length}</td><td>${money(p.price)}</td><td>${num(stock)}</td><td><button class="link" data-product="${esc(a)}">Открыть</button></td></tr>`}).join('');return pageHead('Товары','Карточки, варианты, цены и остатки','<button class="btn primary" data-add-product>Создать карточку</button>')+table(['Артикул','Название','Вариантов','Цена','Остаток',''],rows);}
async function unit(){const d=await data();if(!d.products.length)return empty('Юнит-экономика готова','После создания товара расходы можно заполнить вручную и пересчитывать автоматически.');const rows=d.products.map(p=>{const u=unitEconomics({price:p.price,cost:p.purchasePrice,commission:p.commission,logistics:p.logisticsCost,advertising:p.adCost,other:p.otherExpenses});return `<tr><td><b>${esc(p.article)}</b></td><td>${money(u.revenue)}</td><td>${money(p.purchasePrice)}</td><td>${money(p.commission)}</td><td>${money(p.logisticsCost)}</td><td>${money(p.adCost)}</td><td><strong>${money(u.profit)}</strong></td><td>${u.margin.toFixed(2)}%</td></tr>`}).join('');return pageHead('Юнит-экономика','Полный контроль расходов и маржинальности','<button class="btn secondary" data-expenses>Настроить расходы</button>')+`<div class="formula">Прибыль = цена − себестоимость − комиссия − логистика − хранение − реклама − упаковка − прочие расходы</div>`+table(['Артикул','Цена','Себестоимость','Комиссия','Логистика','Реклама','Прибыль','Маржа'],rows);}
async function warehouses(){const d=await data();const rows=d.warehouses.map(w=>`<tr><td><b>${esc(w.name)}</b></td><td>${esc(w.address||'—')}</td><td>${num(d.stocks.filter(s=>s.warehouse===w.name).reduce((a,x)=>a+Number(x.available||0),0))}</td><td>${esc(w.type||'Собственный')}</td></tr>`).join('');return pageHead('Склады','Склады, зоны, ячейки, палеты и короба','<button class="btn primary" data-add-warehouse>Создать склад</button>')+table(['Склад','Адрес','Остаток','Тип'],rows,'Складов пока нет. Создайте первый склад.');}
async function shipments(){const d=await data();const rows=d.shipments.map(x=>`<tr><td><b>${esc(x.number||x.id)}</b></td><td>${esc(x.warehouse||'—')}</td><td>${esc(x.status||'Черновик')}</td><td>${num(x.itemsCount)}</td><td>${esc(x.date||'—')}</td></tr>`).join('');return pageHead('Поставки','Комплектация и перемещение товара между складами','<button class="btn primary" data-add-shipment>Создать поставку</button>')+table(['Номер','Склад','Статус','Позиций','Дата'],rows,'Поставок пока нет.');}
async function production(){const d=await data();const rows=d.productionOrders.map(x=>`<tr><td><b>${esc(x.number||x.id)}</b></td><td>${esc(x.article)}</td><td>${num(x.quantity)}</td><td>${money(x.cost)}</td><td>${esc(x.status||'Черновик')}</td></tr>`).join('');return pageHead('Производство','Планирование выпуска по актуальности и запасу','<button class="btn primary" data-add-production>Создать заявку</button>')+table(['Заявка','Артикул','Количество','Себестоимость','Статус'],rows,'Заявок нет.');}
async function fbs(){const d=await data();const stages=['Новые','Сборка','Упаковка','Готово к отгрузке'];return pageHead('FBS','Заказ, сканирование, упаковка и отгрузка','<button class="btn primary" data-add-fbs>Добавить заказ</button>')+`<div class="fbs-board">${stages.map((s,i)=>`<section><header><b>${s}</b><span>${d.fbs.filter(x=>Number(x.stage||0)===i).length}</span></header>${d.fbs.filter(x=>Number(x.stage||0)===i).map(x=>`<article><b>${esc(x.article||'—')}</b><small>${esc(x.barcode||'Без штрихкода')}</small><span>${esc(x.warehouse||'—')}</span></article>`).join('')}</section>`).join('')}</div><button class="btn secondary" data-scan>Запустить сканирование</button>`;}
async function advertising(){const d=await data(),spent=d.ads.reduce((s,x)=>s+Number(x.spent||0),0),clicks=d.ads.reduce((s,x)=>s+Number(x.clicks||0),0),impr=d.ads.reduce((s,x)=>s+Number(x.impressions||0),0),orders=d.ads.reduce((s,x)=>s+Number(x.orders||0),0);return pageHead('Реклама','Кампании, эффективность и расходы','<button class="btn primary" data-add-ad>Добавить расход</button>')+`<div class="metrics">${k('Расход',money(spent))}${k('CTR',impr?(clicks/impr*100).toFixed(2)+'%':'—')}${k('CPC',clicks?money(spent/clicks):'—')}${k('CPO',orders?money(spent/orders):'—')}</div>`+table(['Кампания','Показы','Клики','Расход','Заказы'],d.ads.map(x=>`<tr><td><b>${esc(x.campaign||'—')}</b></td><td>${num(x.impressions)}</td><td>${num(x.clicks)}</td><td>${money(x.spent)}</td><td>${num(x.orders)}</td></tr>`).join(''),'После импорта рекламного отчёта здесь появятся кампании.');}
async function analytics(){const d=await data(),days={};d.sales.forEach(x=>days[x.date||'—']=(days[x.date||'—']||0)+Number(x.orders||0));const rows=Object.entries(days).sort().slice(-31).map(([date,v])=>`<tr><td>${esc(date)}</td><td>${num(v)}</td></tr>`).join('');return pageHead('Аналитика','Динамика продаж и контроль ключевых показателей','')+`<div class="chart-placeholder">${rows?table(['Дата','Заказы'],rows):empty('Нет данных','Импортируйте продажи, чтобы построить графики.')}</div>`;}
async function reports(){return pageHead('Отчёты','Выгрузка фактических данных','')+`<div class="report-grid">${['products','sales','stocks','ads','fbs','expenses'].map(s=>`<button class="report-card" data-export="${s}"><b>${s}</b><span>Скачать CSV</span></button>`).join('')}</div>`;}
async function api(){const d=await data();return pageHead('WB API','Подключения и синхронизация данных','<button class="btn primary" data-add-api>Добавить API</button>')+table(['Подключение','Статус'],d.apiConnections.map(x=>`<tr><td><b>${esc(x.name||'WB')}</b></td><td>${x.enabled?'Подключено':'Отключено'}</td></tr>`).join(''),'API пока не подключён.');}
async function importer(){return pageHead('Импорт данных','Шаблоны, проверка структуры и загрузка без угадывания формата','')+`<div class="template-grid">${Object.entries(IMPORT_TEMPLATES).map(([id,t])=>`<article><b>${esc(t.title)}</b><p>${esc(t.description)}</p><small>${t.columns.length} обязательных колонок</small><button class="btn secondary" data-template="${id}">Скачать шаблон</button></article>`).join('')}</div><label class="dropzone">Выберите XLSX, XLS или CSV<input id="importFile" type="file" multiple accept=".xlsx,.xls,.csv" hidden></label>`;}
async function settings(){const d=await data();return pageHead('Личный кабинет','Профиль, магазин и доступ сотрудников','')+`<div class="settings"><section><h3>Магазин</h3><label>Название<input value="BELTANEE"></label><button class="btn primary">Сохранить</button></section><section><h3>Команда</h3><p>Пользователи и роли подключаются к единому рабочему пространству.</p><button class="btn secondary">Добавить сотрудника</button></section><section><h3>Локальная база</h3><p>${num(d.products.length)} товаров, ${num(d.sales.length)} продаж, ${num(d.stocks.length)} остатков.</p></section></div>`;}
function pageHead(t,s,a){return `<div class="page-head"><div><small>B-JOB</small><h1>${t}</h1><p>${s}</p></div>${a}</div>`;}
async function render(){const v=$('#view');v.classList.add('loading');try{const fn={overview,products,unit,warehouses,shipments,fbs,advertising,analytics,reports,production,api,import:importer,settings}[state.page]||overview;v.innerHTML=await fn();bind();}catch(e){console.error(e);v.innerHTML=empty('Ошибка раздела',esc(e.message||'Неизвестная ошибка'));}finally{requestAnimationFrame(()=>v.classList.remove('loading'));}}
function modal(title,fields,save){const m=$('#modal');m.innerHTML=`<div class="modal-bg"><form class="modal"><button type="button" class="close">×</button><h2>${title}</h2>${fields.map(f=>`<label>${f}<input name="${f}" ${f==='token'?'type="password"':''}></label>`).join('')}<button class="btn primary">Сохранить</button></form></div>`;m.querySelector('.close').onclick=()=>m.innerHTML='';m.querySelector('form').onsubmit=async e=>{e.preventDefault();await save(Object.fromEntries(new FormData(e.target)));m.innerHTML='';await render();};}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.page=x.dataset.page;render()});document.querySelectorAll('[data-template]').forEach(x=>x.onclick=()=>downloadTemplate(x.dataset.template));$('#importFile')?.addEventListener('change',async e=>{if(!e.target.files.length)return;toast('Импорт: проверяем файл…');try{const mod=await import('../import.js');const sheets=await mod.parseWorkbook(e.target.files[0]);const result=await mod.importSheets(sheets);await DB.put('imports',{id:'imp:'+Date.now(),date:new Date().toISOString(),result,status:'completed'});toast('Импорт завершён');state.page='overview';render();}catch(err){toast('Импорт не выполнен: '+(err.message||'проверьте шаблон'));}});document.querySelector('[data-add-product]')?.addEventListener('click',()=>modal('Новая карточка',['article','name','price','purchasePrice','commission','logisticsCost','adCost','otherExpenses'],async v=>{if(!v.article||!v.name)throw new Error('Артикул и название обязательны.');await DB.put('products',{id:'p:'+v.article,...v});toast('Карточка создана')}));document.querySelector('[data-add-warehouse]')?.addEventListener('click',()=>modal('Новый склад',['name','address','type'],async v=>{const w=createWarehouse({id:'wh:'+Date.now(),...v});await DB.put('warehouses',w);toast('Склад создан')}));document.querySelector('[data-add-shipment]')?.addEventListener('click',()=>modal('Новая поставка',['number','warehouse','itemsCount'],async v=>{await DB.put('shipments',{id:'sh:'+Date.now(),...v,status:'Черновик',date:new Date().toISOString().slice(0,10)});toast('Поставка создана')}));document.querySelector('[data-add-production]')?.addEventListener('click',()=>modal('Заявка на производство',['number','article','quantity','cost'],async v=>{const r=createProductionRequest({id:'prod:'+Date.now(),...v});await DB.put('productionOrders',r);toast('Заявка создана')}));document.querySelector('[data-add-fbs]')?.addEventListener('click',()=>modal('FBS заказ',['article','barcode','warehouse','amount'],async v=>{await DB.put('fbs',{id:'fbs:'+Date.now(),...v,stage:0,status:'new'});toast('Заказ добавлен')}));document.querySelector('[data-add-api]')?.addEventListener('click',()=>modal('WB API',['name','token'],async v=>{if(!v.token)throw new Error('API-ключ обязателен.');await DB.put('apiConnections',{id:'api:'+Date.now(),name:v.name||'WB',token:v.token,enabled:true,createdAt:new Date().toISOString()});toast('Подключение сохранено локально')}));document.querySelector('[data-scan]')?.addEventListener('click',()=>toast('Сканирование: подключение камеры будет доступно в рабочем модуле FBS.'));document.querySelectorAll('[data-export]').forEach(x=>x.onclick=()=>exportCsv(x.dataset.export));}
function exportCsv(name){DB.all(name).then(rows=>{const keys=[...new Set(rows.flatMap(x=>Object.keys(x)))],csv='\ufeff'+keys.join(';')+'\n'+rows.map(x=>keys.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`B-JOB_${name}.csv`;a.click();URL.revokeObjectURL(a.href);});}
function toast(t){const x=$('#toast');x.textContent=t;x.className='show';setTimeout(()=>x.className='',3000);}
$('#app').innerHTML=shell();render();
