import * as DB from '../db.js';
const REFRESH_MS=300000;
let mounted=false,refreshTimer=null,mode='manager';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${crypto.randomUUID()}`;
const activeShop=()=>localStorage.getItem('bjob:v2:active-shop')||null;
function toast(text,error=false){let t=document.querySelector('#bjob-toast');if(!t){t=document.createElement('div');t.id='bjob-toast';document.body.appendChild(t)}t.textContent=text;t.dataset.type=error?'error':'ok';clearTimeout(window.__assemblyToast);window.__assemblyToast=setTimeout(()=>t.remove(),2800)}
async function apiStatus(){try{const rows=await DB.all('apiConnections');const a=rows.find(x=>x.active!==false&&(x.status==='connected'||x.connected===true));if(a)return{label:'API',detail:`${String(a.marketplace||'API').toUpperCase()} подключён`}}catch{}if(window.BJobDesktop?.lan?.connected||window.bjobLan?.connected)return{label:'LAN',detail:'Локальная сеть подключена'};return{label:'OFFLINE',detail:'Локальные данные'}}
async function orders(){try{return await DB.all('orders')}catch{return[]}}
async function tasks(){try{return(await DB.all('assemblyTasks')).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}catch{return[]}}
const pill=s=>`<span class="assembly-status ${esc(s||'NEW')}">${esc({NEW:'Новое',ROADMAP:'ROADMAP готов',PICKING:'В сборке',READY:'Готово',DONE:'Завершено'}[s]||s||'Новое')}</span>`;
async function shell(body){const st=await apiStatus();return `<section class="page assembly-page"><div class="page-head"><div><div class="eyebrow">B-JOB / Сборочные задания</div><h1>Сборочные задания</h1><p>Заказ → задание → ROADMAP → складская сборка.</p></div><div class="assembly-connection"><b>${esc(st.label)}</b><span>${esc(st.detail)}</span></div></div><div class="assembly-tabs"><button class="ui-btn ${mode==='manager'?'active':''}" data-assembly-mode="manager">Менеджер</button><button class="ui-btn ${mode==='warehouse'?'active':''}" data-assembly-mode="warehouse">Склад</button><button class="ui-btn ghost" data-assembly-back>← Перемещения</button></div>${body}</section>`}
async function manager(){const os=await orders(),ts=await tasks();const rows=os.map((o,i)=>{const ls=Array.isArray(o.lines)?o.lines:Array.isArray(o.items)?o.items:[o];const f=ls[0]||{};const id=o.id||`order-${i}`;return `<article class="assembly-order"><label><input type="checkbox" data-order-check value="${esc(id)}"><span><b>Заказ ${esc(o.orderNumber||o.number||id)}</b><small>${esc(f.name||f.article||f.sku||'Позиция')} · ${esc(f.quantity||o.quantity||1)} шт.</small></span></label><span>${esc(o.status||'Новый')}</span></article>`}).join('');return shell(`<div class="assembly-metrics"><div><span>Заказов</span><b>${os.length}</b></div><div><span>Активных заданий</span><b>${ts.filter(x=>!['DONE','SENT'].includes(x.status)).length}</b></div><div><span>Автообновление</span><b>5 мин</b></div></div><div class="action-row"><button class="ui-btn" data-assembly-refresh>Обновить сейчас</button><button class="ui-btn primary" data-create-assembly>Сформировать сборочное задание</button></div><div class="assembly-list">${rows||'<div class="empty-panel"><b>Заказов пока нет</b><p>При подключении API заказы появятся здесь. Автоматическое обновление — каждые 5 минут.</p></div>'}</div>`)}
async function warehouse(){const ts=await tasks();const rows=ts.map(t=>`<article class="assembly-task"><div><b>Задание ${esc(t.number||t.id)}</b><small>${new Date(t.createdAt||Date.now()).toLocaleString('ru-RU')}</small></div><div>${pill(t.status)}</div><div class="action-row">${t.status==='NEW'?`<button class="ui-btn" data-build-roadmap="${esc(t.id)}">Сформировать ROADMAP</button>`:''}${['ROADMAP','PICKING'].includes(t.status)?`<button class="ui-btn primary" data-start-pick="${esc(t.id)}">Открыть сборку</button>`:''}</div></article>`).join('');return shell(`<div class="assembly-metrics"><div><span>Получено</span><b>${ts.length}</b></div><div><span>В сборке</span><b>${ts.filter(x=>x.status==='PICKING').length}</b></div><div><span>Готово</span><b>${ts.filter(x=>['READY','DONE','SENT'].includes(x.status)).length}</b></div></div><div class="assembly-list">${rows||'<div class="empty-panel"><b>Нет входящих заданий</b><p>Когда менеджер отправит задание, оно появится здесь.</p></div>'}</div>`)}
async function buildPlan(task){const boxes=await DB.all('boxes'),plan=[];for(const line of task.lines||[]){let need=Math.max(0,Number(line.quantity||0)-Number(line.pickedQty||0));const candidates=boxes.filter(b=>b.locked!==true&&Array.isArray(b.contents||b.items||b.products)).filter(b=>(b.contents||b.items||b.products).some(x=>String(x.article||x.sku||x.variantId||'')===String(line.article||line.sku||line.variantId||'')));for(const b of candidates){if(!need)break;const found=(b.contents||b.items||b.products).find(x=>String(x.article||x.sku||x.variantId||'')===String(line.article||line.sku||line.variantId||''));const available=Number(found?.quantity??found?.qty??0),take=Math.min(need,Math.max(0,available));if(take){plan.push({lineId:line.id,boxId:b.id,address:b.address||b.location||b.cell||'Без адреса',article:line.article||line.sku||line.variantId,quantity:take});need-=take}}if(need)plan.push({lineId:line.id,boxId:null,address:'Не найдено',article:line.article||line.sku||line.variantId,quantity:need,missing:true})}return plan}
async function createTask(){const ids=[...document.querySelectorAll('[data-order-check]:checked')].map(x=>x.value);if(!ids.length)throw Error('Выберите хотя бы один заказ.');const os=await orders(),selected=os.filter(o=>ids.includes(String(o.id))),lines=[];for(const o of selected){const src=Array.isArray(o.lines)?o.lines:Array.isArray(o.items)?o.items:[o];for(const item of src){const q=Number(item.quantity||item.qty||1),key=String(item.variantId||item.sku||item.article||item.id||item.name||'unknown'),old=lines.find(x=>x.key===key);if(old)old.quantity+=q;else lines.push({id:uid('line'),key,variantId:item.variantId||null,sku:item.sku||null,article:item.article||null,name:item.name||item.article||item.sku||'Позиция',quantity:q,pickedQty:0})}}const t={id:uid('assembly'),number:`ASM-${Date.now()}`,shopId:activeShop(),sourceOrderIds:ids,lines,status:'NEW',createdAt:new Date().toISOString(),createdBy:'manager'};await DB.put('assemblyTasks',t);await DB.put('assemblyEvents',{id:uid('assembly-event'),taskId:t.id,type:'created',date:new Date().toISOString(),details:{orderIds:ids}});return t}
async function makeRoadmap(id){const t=await DB.get('assemblyTasks',id);if(!t)throw Error('Задание не найдено.');const plan=await buildPlan(t);await DB.put('assemblyTasks',{...t,status:'ROADMAP',roadmap:plan,roadmapCreatedAt:new Date().toISOString()});return plan}
async function openPick(id){const t=await DB.get('assemblyTasks',id);if(!t)throw Error('Задание не найдено.');if(!t.roadmap)await makeRoadmap(id);const fresh=await DB.get('assemblyTasks',id);const rows=(fresh.roadmap||[]).map(r=>`<article class="assembly-pick"><div><b>${esc(r.article)}</b><small>${esc(r.address)} · ${r.boxId?`Короб ${esc(r.boxId)}`:'Источник не найден'}</small></div><strong>${esc(r.quantity)} шт.</strong>${r.missing?'<span class="assembly-warning">Не найдено</span>':`<button class="ui-btn" data-take-line="${esc(r.lineId)}" data-box-id="${esc(r.boxId)}">Взять 1</button>`}</article>`).join('');document.querySelector('#view').innerHTML=await shell(`<div class="empty-panel"><b>${esc(fresh.number)}</b><p>ROADMAP построен по адресам и коробам. Каждое изъятие записывается как складская операция задания.</p></div><div class="assembly-list">${rows}</div><div class="action-row"><button class="ui-btn primary" data-finish-assembly="${esc(fresh.id)}">Завершить сборку</button></div>`);bind()}
async function take(lineId,boxId){const ts=await tasks(),t=ts.find(x=>['ROADMAP','PICKING'].includes(x.status)&&(x.roadmap||[]).some(r=>r.lineId===lineId&&String(r.boxId)===String(boxId)));if(!t)throw Error('Строка сборки не найдена.');const line=t.lines.find(x=>x.id===lineId);if(!line)throw Error('Позиция не найдена.');if(Number(line.pickedQty||0)>=Number(line.quantity||0))throw Error('Позиция уже собрана.');line.pickedQty=Number(line.pickedQty||0)+1;t.status='PICKING';await DB.put('assemblyTasks',{...t,lines:t.lines});await DB.put('assemblyEvents',{id:uid('assembly-event'),taskId:t.id,type:'pick',date:new Date().toISOString(),boxId,lineId,quantity:1,article:line.article||line.sku||line.variantId});await openPick(t.id)}
async function finish(id){const t=await DB.get('assemblyTasks',id);if(!t)throw Error('Задание не найдено.');if(!(t.lines||[]).every(x=>Number(x.pickedQty||0)>=Number(x.quantity||0)))throw Error('Нельзя завершить: часть позиций ещё не собрана.');await DB.put('assemblyTasks',{...t,status:'READY',completedAt:new Date().toISOString()});await DB.put('assemblyEvents',{id:uid('assembly-event'),taskId:id,type:'ready',date:new Date().toISOString()});render()}
function bind(){document.querySelectorAll('[data-assembly-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.assemblyMode;render()});document.querySelector('[data-assembly-back]')?.addEventListener('click',()=>{window.__bjobAssemblyOpen=false;[...document.querySelectorAll('[data-route]')].find(x=>x.dataset.route==='transfers')?.click()});document.querySelector('[data-assembly-refresh]')?.addEventListener('click',()=>render());document.querySelector('[data-create-assembly]')?.addEventListener('click',async()=>{try{const t=await createTask();toast(`Задание ${t.number} создано и отправлено на склад.`);mode='warehouse';render()}catch(e){toast(e.message,true)}});document.querySelectorAll('[data-build-roadmap]').forEach(b=>b.onclick=async()=>{try{await makeRoadmap(b.dataset.buildRoadmap);render()}catch(e){toast(e.message,true)}});document.querySelectorAll('[data-start-pick]').forEach(b=>b.onclick=()=>openPick(b.dataset.startPick).catch(e=>toast(e.message,true)));document.querySelectorAll('[data-take-line]').forEach(b=>b.onclick=()=>take(b.dataset.takeLine,b.dataset.boxId).catch(e=>toast(e.message,true)));document.querySelector('[data-finish-assembly]')?.addEventListener('click',()=>finish(document.querySelector('[data-finish-assembly]').dataset.finishAssembly).catch(e=>toast(e.message,true)))}
async function render(){const view=document.querySelector('#view');if(!view)return;window.__bjobAssemblyOpen=true;view.innerHTML=mode==='manager'?await manager():await warehouse();bind()}
function decorate(){if(localStorage.getItem('bjob:route')!=='transfers'||window.__bjobAssemblyOpen)return;const view=document.querySelector('#view');if(!view||view.querySelector('[data-open-assembly]'))return;const head=view.querySelector('.page-head');if(!head)return;const b=document.createElement('button');b.className='ui-btn primary';b.dataset.openAssembly='1';b.textContent='Сборочные задания';(head.querySelector('.action-row')||head).appendChild(b);b.onclick=()=>{mode='manager';render()}}
export function startAssemblyLayer(){if(mounted)return;mounted=true;const o=new MutationObserver(decorate);o.observe(document.body,{childList:true,subtree:true});decorate();clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(window.__bjobAssemblyOpen&&mode==='manager')render().catch(()=>{})},REFRESH_MS)}