export function createFbsWarehouse({id=crypto.randomUUID(),name='Новый FBS-склад',rows=4,cols=6}={}){return {id,name,rows,cols,cells:[],boxes:[],routes:[],updatedAt:new Date().toISOString()};}
export function addLocation(warehouse,{id=crypto.randomUUID(),address,name='',x=0,y=0,w=1,h=1,type='cell'}={}){if(!address)throw new Error('Адрес обязателен');const location={id,address,name,x,y,w,h,type,locked:false};warehouse.cells.push(location);touch(warehouse);return location;}
export function updateLocation(warehouse,id,patch){const item=warehouse.cells.find(x=>x.id===id);if(!item)throw new Error('Адрес не найден');Object.assign(item,patch);touch(warehouse);return item;}
export function removeLocation(warehouse,id){const i=warehouse.cells.findIndex(x=>x.id===id);if(i<0)throw new Error('Адрес не найден');if(warehouse.boxes.some(b=>b.locationId===id))throw new Error('Нельзя удалить занятый адрес');warehouse.cells.splice(i,1);touch(warehouse);return true;}
export function addBox(warehouse,{code=`BOX-${Date.now()}`,type='mono',locationId=null,color='',qr=null}={}){if(warehouse.boxes.some(b=>b.code===code))throw new Error('Короб уже существует');const box={id:crypto.randomUUID(),code,type,locationId,color,qr,locked:false,contents:[]};warehouse.boxes.push(box);touch(warehouse);return box;}
export function updateBox(warehouse,id,patch){const box=getBox(warehouse,id);Object.assign(box,patch);touch(warehouse);return box;}
export function removeBox(warehouse,id){const i=warehouse.boxes.findIndex(x=>x.id===id);if(i<0)throw new Error('Короб не найден');warehouse.boxes.splice(i,1);touch(warehouse);return true;}
export function setBoxLock(warehouse,id,locked=true){const box=getBox(warehouse,id);box.locked=Boolean(locked);touch(warehouse);return box;}
export function putItem(warehouse,boxId,{article,name='',color='',size='',qty=1}={}){const box=getBox(warehouse,boxId);if(box.locked)throw new Error('Короб заблокирован');if(!article||qty<=0)throw new Error('Некорректный товар');const row=box.contents.find(x=>x.article===article&&x.color===color&&x.size===size);if(row)row.qty+=qty;else box.contents.push({article,name,color,size,qty});touch(warehouse);return box;}
export function takeItem(warehouse,boxId,query,qty=1){const box=getBox(warehouse,boxId);if(box.locked)throw new Error('Короб заблокирован');const row=box.contents.find(x=>x.article===query.article&&x.color===query.color&&x.size===query.size);if(!row||row.qty<qty)throw new Error('Недостаточно товара');row.qty-=qty;touch(warehouse);return {...row,qty};}
export function moveBox(warehouse,boxId,locationId){const box=getBox(warehouse,boxId);box.locationId=locationId;touch(warehouse);return box;}
export function inventory(warehouse){const rows=new Map();for(const box of warehouse.boxes)for(const item of box.contents){const key=[item.article,item.color,item.size].join('|');const row=rows.get(key)||{article:item.article,name:item.name,color:item.color,size:item.size,qty:0};row.qty+=item.qty;rows.set(key,row);}return [...rows.values()];}
export function createRoadmap(warehouse,task){const steps=(task?.lines||[]).map((line,i)=>({order:i+1,article:line.article,qty:line.qty,boxId:findBox(warehouse,line.article),status:'pending'}));const roadmap={id:crypto.randomUUID(),taskId:task?.id||null,steps,createdAt:new Date().toISOString()};warehouse.routes.push(roadmap);touch(warehouse);return roadmap;}
function findBox(w,a){return w.boxes.find(x=>x.contents.some(i=>i.article===a&&i.qty>0))?.id||null;}
function getBox(w,id){const b=w.boxes.find(x=>x.id===id);if(!b)throw new Error('Короб не найден');return b;}
function touch(w){w.updatedAt=new Date().toISOString();}
