import * as DB from '../db.js';

const STYLE='fbs-operations-ui-style';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function installStyle(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
.fbs-workspace{position:relative}.fbs-workspace-head,.fbs-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:nowrap}.fbs-workspace-head{margin-bottom:14px}.fbs-workspace-actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}.fbs-toolbar{overflow-x:auto;padding:5px 2px 10px}.fbs-toolbar>*{flex:0 0 auto}.fbs-toolbar .fbs-search{min-width:260px;flex:1 1 340px}.fbs-toolbar select,.fbs-toolbar button{min-height:38px}.fbs-toolbar .fbs-view-switch{display:flex;gap:4px;padding:3px;border-radius:10px;background:#f1f3f5}.fbs-toolbar .fbs-view-switch button{border:0;background:transparent;padding:7px 11px;border-radius:7px}.fbs-toolbar .fbs-view-switch button.active{background:#fff;box-shadow:0 1px 5px #00000014}.fbs-ops{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-left:auto}.fbs-ops button{white-space:nowrap}.fbs-sector-strip{display:flex;align-items:center;gap:7px;overflow:auto;padding:4px 0 10px;margin-bottom:5px}.fbs-sector{display:inline-flex;align-items:center;gap:5px;border:1px solid #e1e4e8;background:#fff;border-radius:9px;padding:7px 10px;white-space:nowrap;cursor:pointer}.fbs-sector:hover{background:#f7f8fa}.fbs-sector.active{border-color:#111318;box-shadow:0 2px 8px #00000010}.fbs-sector small{opacity:.55}.fbs-sector-add{border-style:dashed}.fbs-sector-menu{display:flex;gap:6px}.fbs-fullscreen{position:fixed!important;inset:0!important;z-index:10000!important;background:#f7f8fa!important;padding:18px!important;overflow:auto!important}.fbs-fullscreen .fbs-map-scroll{max-height:calc(100vh - 270px)}.fbs-fullscreen .fbs-grid{min-height:55vh}.fbs-fs-btn.active{background:#111318!important;color:#fff!important}.fbs-sector-modal .fbs-modal{max-width:560px}@media(max-width:900px){.fbs-workspace-head{align-items:flex-start;flex-direction:column}.fbs-workspace-actions{width:100%;overflow:auto}.fbs-toolbar{align-items:stretch}.fbs-toolbar .fbs-search{min-width:220px}.fbs-ops{margin-left:0}.fbs-fullscreen{padding:10px!important}.fbs-fullscreen .fbs-map-scroll{max-height:calc(100vh - 250px)}}`;
document.head.appendChild(s)}

async function spaces(){return await DB.all('fbsSpaces')}
async function boxes(){return await DB.all('fbsBoxes')}
async function saveSpace(space){await DB.put('fbsSpaces',space)}
function currentSpace(){const select=document.querySelector('#fbs-space-select');return select?.value}

function openModal(title,body,onSave){const wrap=document.createElement('div');wrap.className='fbs-modal-backdrop fbs-sector-modal';wrap.innerHTML=`<div class="fbs-modal"><div class="fbs-modal-head"><div><small>НАСТРОЙКА ПРОСТРАНСТВА</small><h2>${title}</h2></div><button class="fbs-modal-close">×</button></div>${body}<div class="fbs-modal-actions"><button class="btn secondary" data-cancel>Отмена</button><button class="btn primary" data-save>Сохранить</button></div></div>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector('.fbs-modal-close').onclick=close;wrap.querySelector('[data-cancel]').onclick=close;wrap.querySelector('[data-save]').onclick=async()=>{try{await onSave(wrap);close();window.dispatchEvent(new CustomEvent('fbs:rerender'))}catch(e){alert(e.message)}};return wrap}

async function addSector(){const id=currentSpace();const ss=await spaces();const space=ss.find(x=>x.id===id);if(!space)return;const next=(space.rows||0)+1;openModal('Добавить сектор',`<label>Название сектора<input id="sector-name" value="Сектор ${next}" maxlength="40"></label><label>Количество секций<input id="sector-pos" type="number" min="1" max="100" value="${space.positionsPerRow||12}"></label><label>Уровней<input id="sector-levels" type="number" min="1" max="20" value="${space.maxLevels||6}"></label>`,async w=>{space.rows=next;space.sectorNames={...(space.sectorNames||{}),[next]:w.querySelector('#sector-name').value.trim()||`Сектор ${next}`};space.positionsPerRow=Math.max(space.positionsPerRow||1,+w.querySelector('#sector-pos').value);space.maxLevels=Math.max(space.maxLevels||1,+w.querySelector('#sector-levels').value);await saveSpace(space)})}

async function renameSector(row){const id=currentSpace();const ss=await spaces();const space=ss.find(x=>x.id===id);if(!space)return;const old=space.sectorNames?.[row]||`Сектор ${row}`;openModal('Переименовать сектор',`<label>Название<input id="sector-name" value="${esc(old)}" maxlength="40"></label>`,async w=>{space.sectorNames={...(space.sectorNames||{}),[row]:w.querySelector('#sector-name').value.trim()||old};await saveSpace(space)})}

async function deleteSector(row){const id=currentSpace();const ss=await spaces();const space=ss.find(x=>x.id===id);if(!space)return;const all=await boxes();const used=all.some(b=>b.spaceId===space.id&&Number(b.coordinates?.row)===Number(row));if(used){alert('Сектор нельзя удалить: в нём есть коробки. Сначала переместите или удалите коробки.');return}if(!confirm(`Удалить сектор ${space.sectorNames?.[row]||row}?`))return;space.rows=Math.max(1,(space.rows||1)-1);const names={...(space.sectorNames||{})};delete names[row];const shifted={};Object.keys(names).forEach(k=>{const n=Number(k);shifted[n>row?n-1:n]=names[k]});space.sectorNames=shifted;await saveSpace(space)}

async function toggleFullscreen(){const root=document.querySelector('.fbs-workspace');if(!root)return;if(document.fullscreenElement){await document.exitFullscreen?.();root.classList.remove('fbs-fullscreen');return}try{await root.requestFullscreen?.();}catch{}root.classList.add('fbs-fullscreen')}

function enhance(){const root=document.querySelector('.fbs-workspace');if(!root||root.dataset.opsReady)return;root.dataset.opsReady='1';
 const head=root.querySelector('.fbs-workspace-head');if(head){const ops=document.createElement('div');ops.className='fbs-ops';ops.innerHTML='<button class="btn secondary fbs-fs-btn" data-fbs-ops="fullscreen">⛶ Полный экран</button><button class="btn secondary" data-fbs-ops="sector-add">＋ Сектор</button><button class="btn secondary" data-fbs-ops="sector-manage">⚙ Сектора</button>';head.appendChild(ops)}
 const toolbar=root.querySelector('.fbs-toolbar');if(toolbar){const fs=toolbar.querySelector('[data-fbs-action="scan"]');if(fs)fs.style.marginLeft='0'}
 const title=root.querySelector('.fbs-map-title');if(title){const spaceId=currentSpace();spaces().then(ss=>{const space=ss.find(x=>x.id===spaceId);if(!space)return;const strip=document.createElement('div');strip.className='fbs-sector-strip';const names=space.sectorNames||{};strip.innerHTML=Array.from({length:space.rows||0},(_,i)=>{const row=i+1;return `<button class="fbs-sector ${row===1?'active':''}" data-sector-row="${row}"><b>${esc(names[row]||`Сектор ${row}`)}</b><small>R${String(row).padStart(2,'0')}</small></button>`}).join('')+'<button class="fbs-sector fbs-sector-add" data-fbs-ops="sector-add">＋ Добавить</button>';title.parentElement.parentElement.insertBefore(strip,title.parentElement.nextSibling);strip.addEventListener('click',e=>{const b=e.target.closest('[data-sector-row]');if(b){strip.querySelectorAll('.fbs-sector').forEach(x=>x.classList.remove('active'));b.classList.add('active');const row=Number(b.dataset.sectorRow);root.querySelectorAll('[data-fbs-column]').forEach(c=>{c.style.display=c.dataset.fbsColumn?.startsWith(row+':')?'':'none'})}})})}
 root.addEventListener('click',async e=>{const a=e.target.closest('[data-fbs-ops]');if(!a)return;const action=a.dataset.fbsOps;if(action==='fullscreen')await toggleFullscreen();if(action==='sector-add')await addSector();if(action==='sector-manage')manageSectors()});
 document.addEventListener('fullscreenchange',()=>{const fs=root.querySelector('.fbs-fs-btn');if(document.fullscreenElement===root){root.classList.add('fbs-fullscreen');fs?.classList.add('active');fs&&(fs.textContent='⛶ Выйти из полного экрана')}else{root.classList.remove('fbs-fullscreen');fs?.classList.remove('active');fs&&(fs.textContent='⛶ Полный экран')}}); }

async function manageSectors(){const id=currentSpace();const ss=await spaces();const space=ss.find(x=>x.id===id);if(!space)return;const names=space.sectorNames||{};const rows=Array.from({length:space.rows||0},(_,i)=>i+1);openModal('Управление секторами',`<div class="fbs-sector-menu" style="display:grid;gap:8px">${rows.map(r=>`<div style="display:flex;gap:7px;align-items:center"><input value="${esc(names[r]||`Сектор ${r}`)}" data-row-name="${r}" style="flex:1"><button class="btn secondary" data-rename="${r}">Переименовать</button><button class="btn secondary" data-delete="${r}">Удалить</button></div>`).join('')}</div>`,async()=>{const inputs=document.querySelectorAll('[data-row-name]');for(const input of inputs){space.sectorNames={...(space.sectorNames||{}),[input.dataset.rowName]:input.value.trim()||`Сектор ${input.dataset.rowName}`}}await saveSpace(space)})}

installStyle();
const observer=new MutationObserver(()=>enhance());observer.observe(document.body,{childList:true,subtree:true});
window.addEventListener('fbs:rerender',()=>{document.querySelector('.fbs-workspace')?.removeAttribute('data-ops-ready');window.setTimeout(()=>location.reload(),50)});
setTimeout(enhance,250);
