import * as DB from '../db.js';
import {createFbsShipment,scanShipmentItem,getPickingProgress,beginLabeling,addLabel,getLabelProgress,readyShipment,shipShipment,buildPickPlan} from './domain/fbsPicking.js';
import {pickFromBox} from './domain/fbsPicking.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v||0).toLocaleString('ru-RU');
let shipmentId=null;
async function mount(){if(document.querySelector('.fbs-picking-panel'))return;const nav=document.querySelector('#mainNav');if(!nav)return;const b=document.createElement('button');b.textContent='Сборка поставки';b.dataset.fbsPickingNav='1';b.className='fbs-picking-nav';nav.querySelector('.bjob-group:nth-child(3)')?.appendChild(b);b.addEventListener('click',async()=>{const orders=await DB.all('fbs');const source=orders.filter(x=>x.status!=='cancelled');if(!source.length){alert('Нет FBS-заказов для сборки.');return}const grouped=new Map();source.forEach(x=>{const key=x.variantId||x.barcode||x.article;if(!key)return;const cur=grouped.get(key)||{variantId:key,article:x.article,size:x.size,color:x.color,barcode:x.barcode,quantity:0};cur.quantity+=Number(x.quantity||1);grouped.set(key,cur)});const shipment=createFbsShipment({id:`fbs-shipment-${Date.now()}`,number:`FBS-${Date.now()}`,items:[...grouped.values()]});await DB.put('fbs',shipment);shipmentId=shipment.id;render();});
}
async function render(){if(document.querySelector('#view')==null)return;let s=shipmentId?await DB.all('fbs'):[];const shipment=s.find(x=>x.id===shipmentId);if(!shipment)return;let boxes=await DB.all('fbsBoxes');const plan=buildPickPlan(shipment,boxes);const p=getPickingProgress(shipment);const lp=getLabelProgress(shipment);let panel=document.querySelector('.fbs-picking-panel');if(!panel){panel=document.createElement('section');panel.className='fbs-picking-panel';document.querySelector('#view')?.prepend(panel)}panel.innerHTML=`<div class="fbs-picking-head"><div><small>FBS / СБОРКА</small><h2>Поставка ${esc(shipment.number)}</h2><p>Собрано ${n(p.scanned)} из ${n(p.required)} · ${p.percent.toFixed(0)}%</p></div><div class="fbs-picking-actions">${shipment.status==='packed'?'<button class="btn primary" data-pick-action="label">Проклеить поставку</button>':''}${shipment.status==='ready'?'<button class="btn primary" data-pick-action="ship">Поставка готова / Отгрузить</button>':''}</div></div><div class="fbs-picking-progress"><div style="width:${p.percent}%"></div></div><div class="fbs-picking-grid"><div><h3>Маршрут</h3>${plan.length?plan.map((x,i)=>`<button class="pick-step" data-pick-box="${esc(x.boxId)}"><b>${i+1}. Коробка</b><span>ряд ${x.coordinates.row} · позиция ${x.coordinates.position} · уровень ${x.coordinates.level}</span><small>${x.items.map(y=>`${esc(y.article||y.variantId)} × ${y.quantity}`).join(' · ')}</small></button>`).join(''):'<p>В коробках пока нет товаров для этой поставки.</p>'}</div><div><h3>Сканирование</h3><p>Сначала выберите коробку, затем отсканируйте товар. Для теста можно ввести его штрихкод или артикул.</p><button class="btn secondary" data-pick-action="scan">📷 Сканировать товар</button><div class="pick-label-progress"><b>Маркировка</b><span>${n(lp.labels)} / ${n(lp.required)}</span></div></div></div>`;
panel.querySelector('[data-pick-action="scan"]')?.addEventListener('click',async()=>{const boxId=prompt('Штрихкод/ID коробки:');if(!boxId)return;const box=boxes.find(x=>x.id===boxId||x.barcode===boxId);if(!box){alert('Коробка не найдена.');return}const code=prompt('Штрихкод/артикул товара:');if(!code)return;const item=(box.items||[]).find(x=>x.barcode===code||x.variantId===code||x.article===code);if(!item){alert('Товар в этой коробке не найден.');return}try{const nextShipment=scanShipmentItem(shipment,item,{boxId,barcode:code});const nextBox=pickFromBox(box,item.variantId,1);await DB.put('fbs',nextShipment);await DB.put('fbsBoxes',nextBox);render()}catch(e){alert(e.message)}});
panel.querySelector('[data-pick-action="label"]')?.addEventListener('click',async()=>{try{await DB.put('fbs',beginLabeling(shipment));render()}catch(e){alert(e.message)}});
panel.querySelector('[data-pick-action="ship"]')?.addEventListener('click',async()=>{try{await DB.put('fbs',shipShipment(shipment));render()}catch(e){alert(e.message)}});
panel.querySelectorAll('[data-pick-box]').forEach(x=>x.addEventListener('click',()=>{alert(`Коробка ${x.dataset.pickBox}\nОтсканируйте её, затем товар из неё.`)}));
if(shipment.status==='labeling'){const action=document.createElement('button');action.className='btn secondary';action.textContent='Сканировать WB-стикер';action.onclick=async()=>{const code=prompt('Введите код/номер WB-стикера:');if(!code)return;const variant=shipment.items.find(i=Number(i.quantity)>0&&(shipment.labels||[]).filter(l=>l.variantId===i.variantId).length<i.quantity);if(!variant){alert('Все товары промаркированы.');return}await DB.put('fbs',addLabel(shipment,variant.variantId,code));if(getLabelProgress({...shipment,labels:[...(shipment.labels||[]),{variantId:variant.variantId}]}).complete)await DB.put('fbs',readyShipment({...shipment,labels:[...(shipment.labels||[]),{variantId:variant.variantId}]}));render()};panel.querySelector('.fbs-picking-actions').appendChild(action)}}
function watch(){if(document.querySelector('#mainNav button.active')?.dataset.page==='fbs')mount();if(document.querySelector('.fbs-picking-panel'))render()}
setTimeout(watch,100);setInterval(watch,1000);
