import * as DB from '../db.js';
const BOX_KEY='bjob:fbs-open-box';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isFbs=()=>document.querySelector('#mainNav button.active')?.dataset.page==='fbs';
export function fbsBoxUrl(id){const u=new URL(location.href);u.searchParams.set('fbsBox',id);return u.href}
function boxFromUrl(){try{return new URL(location.href).searchParams.get('fbsBox')}catch{return null}}
function openRequestedBox(){const id=boxFromUrl()||sessionStorage.getItem(BOX_KEY);if(!id||!isFbs())return;const target=document.querySelector(`[data-fbs-box="${CSS.escape(id)}"]`);if(target){target.click();sessionStorage.removeItem(BOX_KEY);return true}return false}
function consumeBoxLink(){const id=boxFromUrl();if(!id)return;sessionStorage.setItem(BOX_KEY,id);if(!isFbs())document.querySelector('#mainNav button[data-page="fbs"]')?.click()}
function dedupeFullscreen(){const all=[...document.querySelectorAll('button')].filter(b=>/полный экран|fullscreen/i.test(b.textContent||''));all.slice(1).forEach(b=>b.remove());return all[0]}
function bindFullscreen(){const b=dedupeFullscreen();if(!b||b.dataset.fsBound)return;b.dataset.fsBound='1';b.onclick=async e=>{e.preventDefault();try{if(document.fullscreenElement)await document.exitFullscreen();else await (document.querySelector('.fbs-workspace')||document.documentElement).requestFullscreen()}catch(err){console.warn('Fullscreen unavailable',err)}};const sync=()=>{b.textContent=document.fullscreenElement?'⛶ Выйти из полного экрана':'⛶ Полный экран'};document.addEventListener('fullscreenchange',sync);sync()}
async function printQr58(box){const payload=fbsBoxUrl(box.id);const qr=`https://api.qrserver.com/v1/create-qr-code/?size=500x500&margin=0&data=${encodeURIComponent(payload)}`;const w=window.open('','_blank','width=500,height=650');if(!w)return;w.document.write(`<html lang="ru"><head><meta charset="utf-8"><title>${esc(box.barcode||box.id)}</title><style>@page{size:58mm 60mm;margin:0}*{box-sizing:border-box}body{width:58mm;height:60mm;margin:0;padding:3mm;font-family:Arial,sans-serif;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2mm}img{width:43mm;height:43mm}strong{font-size:5mm}small{font-size:2.6mm;word-break:break-all}</style></head><body><strong>${esc(box.barcode||box.id)}</strong><img src="${qr}" alt="QR"><small>FBS · ${esc(box.name||'Коробка')}</small><script>setTimeout(()=>print(),900)</script></body></html>`);w.document.close()}
async function interceptPrint(e){const b=e.target.closest('button');if(!b)return;const text=b.textContent||'';if(!/печать.*qr|qr.*печать/i.test(text)&&b.dataset.fbsAction!=='print-qr')return;const id=sessionStorage.getItem(BOX_KEY)||document.querySelector('.fbs-stack-box.selected')?.dataset.fbsBox;const boxes=await DB.all('fbsBoxes');const box=boxes.find(x=>x.id===id);if(!box)return;e.preventDefault();e.stopImmediatePropagation();printQr58(box)}
function install(){consumeBoxLink();openRequestedBox();bindFullscreen();document.addEventListener('click',interceptPrint,true);const obs=new MutationObserver(()=>{bindFullscreen();openRequestedBox()});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('popstate',()=>{consumeBoxLink();setTimeout(openRequestedBox,80)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();