import * as S from './fbsStorage.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`.fbs-storage{margin:16px 0;padding:18px;border:1px solid #e2e5e9;border-radius:14px;background:#fff}.fbs-storage h2{margin:0 0 4px}.fbs-storage-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.fbs-storage-actions{display:flex;gap:8px;flex-wrap:wrap}.fbs-storage table{width:100%;border-collapse:collapse;margin-top:14px}.fbs-storage th,.fbs-storage td{padding:9px;border-bottom:1px solid #eceef1;text-align:left;font-size:13px}.fbs-storage th{font-weight:600;background:#f7f8fa}.fbs-storage input,.fbs-storage select{min-height:34px;padding:6px 8px;border:1px solid #d9dde2;border-radius:8px}.fbs-storage .muted{color:#737981;font-size:12px}.fbs-storage .warn{font-weight:600}.fbs-storage-dialog{position:fixed;inset:0;background:#0005;display:grid;place-items:center;z-index:10001}.fbs-storage-dialog>div{width:min(720px,calc(100vw - 24px));max-height:90vh;overflow:auto;background:#fff;border-radius:14px;padding:18px}.fbs-storage-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.fbs-storage-grid label{display:grid;gap:5px;font-size:12px}@media(max-width:700px){.fbs-storage-grid{grid-template-columns:1fr}.fbs-storage table{display:block;overflow:auto;white-space:nowrap}}`;
function style(){if(document.getElementById('fbs-storage-style'))return;const s=document.createElement('style');s.id='fbs-storage-style';s.textContent=css;document.head.appendChild(s)}
function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function dialog(title,html,save){const w=document.createElement('div');w.className='fbs-storage-dialog';w.innerHTML=`<div><h3>${title}</h3>${html}<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:14px"><button data-cancel>Отмена</button><button data-save>Сохранить</button></div></div>`;document.body.appendChild(w);w.querySelector('[data-cancel]').onclick=()=>w.remove();w.querySelector('[data-save]').onclick=async()=>{try{await save(w);w.remove();render()}catch(e){alert(e.message)}}}
async function render(){const root=document.querySelector('#fbs-storage-panel');if(!root)return;const report=await S.getInventoryReport();const boxes=await S.listBoxes();root.innerHTML=`<div class="fbs-storage-head"><div><h2>Склад FBS</h2><div class="muted">Остаток хранится поштучно и связан с конкретными коробками.</div></div><div class="fbs-storage-actions"><button data-add>＋ Добавить остаток</button><button data-export>Экспорт JSON</button><button data-import>Импорт JSON</button></div></div><table><thead><tr><th>Артикул</th><th>Размер</th><th>Цвет</th><th>Всего</th><th>По коробкам</th><th>Коробки</th><th>Списано</th><th></th></tr></thead><tbody>${report.map(r=>{const own=boxes.filter(b=>b.inventoryId===r.id||b.article===r.article);return `<tr><td><b>${esc(r.article)}</b><br><span class="muted">${esc(r.name)}</span></td><td>${esc(r.size)}</td><td>${esc(r.color)}</td><td><input data-qty="${esc(r.id)}" type="number" min="0" value="${r.quantity}"></td><td>${r.boxed}</td><td>${own.length}</td><td>${r.consumed||0}</td><td><button data-box="${esc(r.id)}">＋ Коробка</button></td></tr>`}).join('')}</tbody></table>${!report.length?'<p class="muted">Остатков пока нет. Добавьте фактическую номенклатуру со склада.</p>':''}`;
root.querySelector('[data-add]').onclick=()=>dialog('Добавить остаток',`<div class="fbs-storage-grid"><label>Артикул<input id="a"></label><label>Наименование<input id="n"></label><label>Размер<input id="s"></label><label>Цвет<input id="c"></label><label>Количество<input id="q" type="number" min="0" value="0"></label></div>`,async w=>S.addInventory({article:w.querySelector('#a').value,name:w.querySelector('#n').value,size:w.querySelector('#s').value,color:w.querySelector('#c').value,quantity:w.querySelector('#q').value}));
root.querySelector('[data-export]').onclick=async()=>download(await S.exportFbs(),`fbs-${new Date().toISOString().slice(0,10)}.json`);
root.querySelector('[data-import]').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const text=await i.files[0].text();await S.importFbs(JSON.parse(text));render()}catch(e){alert(e.message)}};i.click()};
root.querySelectorAll('[data-qty]').forEach(i=>i.onchange=async()=>{const row=(await S.listInventory()).find(x=>x.id===i.dataset.qty);if(row){row.quantity=i.value;await S.updateInventory(row);render()}});
root.querySelectorAll('[data-box]').forEach(b=>b.onclick=()=>dialog('Добавить коробку',`<div class="fbs-storage-grid"><label>Пространство ID<input id="space"></label><label>QR/код коробки<input id="qr"></label><label>Количество<input id="q" type="number" min="0" value="0"></label><label>Место<input id="place" placeholder="ряд/позиция/уровень"></label></div>`,async w=>{const row=(await S.listInventory()).find(x=>x.id===b.dataset.box);if(!row)throw new Error('Остаток не найден.');const p=w.querySelector('#place').value.split('/').map(Number);await S.addBox({spaceId:w.querySelector('#space').value.trim(),article:row.article,inventoryId:row.id,quantity:w.querySelector('#q').value,qrCode:w.querySelector('#qr').value,coordinates:{row:p[0]||0,position:p[1]||0,level:p[2]||0}})}));}
style();
function mount(){const fbs=document.querySelector('.fbs-workspace');if(!fbs||document.querySelector('#fbs-storage-panel'))return;const p=document.createElement('section');p.id='fbs-storage-panel';p.className='fbs-storage';fbs.parentElement?.insertBefore(p,fbs);render()}
new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});setTimeout(mount,400);
