import {createFbsWarehouse,addLocation,addBox,removeBox,setBoxLock,putItem,inventory} from './fbsDomain.js';
const KEY='bjob:fbs:warehouse:v1';
let mounted=false;
const load=()=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):createFbsWarehouse()}catch{return createFbsWarehouse()}};
const save=w=>localStorage.setItem(KEY,JSON.stringify(w));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function form(title,fields,done){document.querySelector('.bjob-fbs-modal')?.remove();const e=document.createElement('div');e.className='bjob-fbs-modal';e.innerHTML=`<div class="bjob-fbs-dialog"><h3>${esc(title)}</h3>${fields.map(f=>`<label>${esc(f.label)}<input data-k="${esc(f.key)}" value="${esc(f.value||'')}"></label>`).join('')}<div class="action-row"><button class="ui-btn" data-cancel>Отмена</button><button class="ui-btn primary" data-ok>Сохранить</button></div></div>`;document.body.appendChild(e);e.querySelector('[data-cancel]').onclick=()=>e.remove();e.querySelector('[data-ok]').onclick=()=>{const d={};e.querySelectorAll('[data-k]').forEach(x=>d[x.dataset.k]=x.value);e.remove();done(d)}}
function render(){const root=document.querySelector('#view');if(!root||localStorage.getItem('bjob:route')!=='fbs')return;const w=load(),rows=inventory(w),total=rows.reduce((n,x)=>n+Number(x.qty),0);root.innerHTML=`<section class="page fbs-unified"><div class="page-head"><div><div class="eyebrow">B-JOB / Склады / FBS</div><h1>Склад FBS</h1><p>Единый склад: адреса, короба и учёт изделий.</p></div><div class="action-row"><button class="ui-btn primary" data-new-location>Добавить адрес</button><button class="ui-btn" data-new-box>Создать короб</button></div></div><div class="fbs-metrics"><div><span>Изделия</span><b>${total}</b></div><div><span>Короба</span><b>${w.boxes.length}</b></div><div><span>Адреса</span><b>${w.cells.length}</b></div><div><span>Заблокировано</span><b>${w.boxes.filter(x=>x.locked).length}</b></div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>${esc(w.name)}</h2><span>${w.rows} × ${w.cols}</span></div><div class="fbs-grid">${w.cells.map(c=>{const b=w.boxes.find(x=>x.locationId===c.id);return `<div class="fbs-cell ${b?'occupied':''}"><b>${esc(c.address)}</b><small>${b?esc(b.code):'Пусто'}</small></div>`}).join('')||'<div class="empty-panel">Добавьте адреса, чтобы построить схему.</div>'}</div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>Короба</h2></div><div class="fbs-boxes">${w.boxes.map(b=>`<article class="fbs-box"><div><b>${esc(b.code)}</b><small>${b.locked?'Заблокирован':'Доступен'}</small></div><div class="action-row"><button class="ui-btn" data-content="${esc(b.id)}">Содержимое</button><button class="ui-btn" data-lock="${esc(b.id)}">${b.locked?'Разблокировать':'Заблокировать'}</button><button class="ui-btn danger" data-delete="${esc(b.id)}">Удалить</button></div></article>`).join('')||'<div class="empty-panel">Коробов пока нет.</div>'}</div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>Учёт изделий</h2></div><table class="fbs-inventory"><thead><tr><th>Артикул</th><th>Товар</th><th>Цвет</th><th>Размер</th><th>Количество</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.article)}</td><td>${esc(r.name)}</td><td>${esc(r.color)}</td><td>${esc(r.size)}</td><td><b>${r.qty}</b></td></tr>`).join('')||'<tr><td colspan="5">Склад пуст.</td></tr>'}</tbody></table></div></section>`;bind(root,w)}
function bind(root,w){root.querySelector('[data-new-location]')?.addEventListener('click',()=>form('Новый адрес',[{key:'address',label:'Адрес'}],d=>{if(!d.address)return;addLocation(w,{address:d.address,x:w.cells.length%w.cols,y:Math.floor(w.cells.length/w.cols)});save(w);render()}));root.querySelector('[data-new-box]')?.addEventListener('click',()=>form('Новый короб',[{key:'code',label:'Код короба'}],d=>{if(!d.code)return;addBox(w,{code:d.code});save(w);render()}));root.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>{const box=w.boxes.find(x=>x.id===b.dataset.lock);if(!box)return;setBoxLock(w,box.id,!box.locked);save(w);render()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Удалить короб?')){removeBox(w,b.dataset.delete);save(w);render()}});root.querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>{const box=w.boxes.find(x=>x.id===b.dataset.content);if(!box)return;form('Добавить изделие',[{key:'article',label:'Артикул'},{key:'name',label:'Товар'},{key:'color',label:'Цвет'},{key:'size',label:'Размер'},{key:'qty',label:'Количество',value:'1'}],d=>{const qty=Number(d.qty);if(!d.article||!Number.isFinite(qty)||qty<=0)return;putItem(w,box.id,{article:d.article,name:d.name,color:d.color,size:d.size,qty});save(w);render()})})}
export function mountUnifiedFbs(){if(mounted)return;mounted=true;new MutationObserver(render).observe(document.body,{childList:true,subtree:true});render()}
