import {createFbsWarehouse,addLocation,addBox,removeBox,setBoxLock,putItem,inventory} from './fbsDomain.js';
const KEY='bjob:fbs:warehouse:v1';
let mounted=false;
const load=()=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):createFbsWarehouse()}catch{return createFbsWarehouse()}};
const save=w=>localStorage.setItem(KEY,JSON.stringify(w));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function modal(title,fields,ok){document.querySelector('.bjob-fbs-modal')?.remove();const el=document.createElement('div');el.className='bjob-fbs-modal';el.innerHTML=`<div class="bjob-fbs-dialog"><h3>${esc(title)}</h3>${fields.map(f=>`<label>${esc(f.label)}<input data-fbs-field="${esc(f.key)}" value="${esc(f.value||'')}"></label>`).join('')}<div class="action-row"><button class="ui-btn" data-fbs-cancel>Отмена</button><button class="ui-btn primary" data-fbs-ok>Сохранить</button></div></div>`;document.body.appendChild(el);el.querySelector('[data-fbs-cancel]').onclick=()=>el.remove();el.querySelector('[data-fbs-ok]').onclick=()=>{const d={};el.querySelectorAll('[data-fbs-field]').forEach(x=>d[x.dataset.fbsField]=x.value);el.remove();ok(d)}}
function render(){const root=document.querySelector('#view');if(!root||localStorage.getItem('bjob:route')!=='fbs')return;const w=load(),items=inventory(w);root.innerHTML=`<section class="page fbs-unified"><div class="page-head"><div><div class="eyebrow">B-JOB / Склады / FBS</div><h1>Склад FBS</h1><p>Единый учёт изделий, адресное хранение и короба.</p></div><div class="fbs-actions"><button class="ui-btn primary" data-fbs-new-location>Добавить адрес</button><button class="ui-btn" data-fbs-new-box>Создать короб</button></div></div><div class="fbs-metrics"><div><span>Изделия</span><b>${items.reduce((n,x)=>n+Number(x.qty),0)}</b></div><div><span>Короба</span><b>${w.boxes.length}</b></div><div><span>Адреса</span><b>${w.cells.length}</b></div><div><span>Заблокировано</span><b>${w.boxes.filter(x=>x.locked).length}</b></div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>${esc(w.name)}</h2><span>${w.rows} × ${w.cols}</span></div><div class="fbs-grid">${w.cells.map(c=>{const box=w.boxes.find(b=>b.locationId===c.id);return `<div class="fbs-cell ${box?'occupied':''}"><b>${esc(c.address)}</b><small>${box?esc(box.code):'Пусто'}</small></div>`}).join('')||'<div class="empty-panel">Добавьте адреса, чтобы построить схему склада.</div>'}</div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>Короба</h2></div><div class="fbs-boxes">${w.boxes.map(b=>`<article class="fbs-box"><div><b>${esc(b.code)}</b><small>${esc(b.type)} · ${b.locked?'Заблокирован':'Доступен'}</small></div><div class="action-row"><button class="ui-btn" data-fbs-content="${esc(b.id)}">Содержимое</button><button class="ui-btn" data-fbs-lock="${esc(b.id)}">${b.locked?'Разблокировать':'Заблокировать'}</button><button class="ui-btn danger" data-fbs-delete="${esc(b.id)}">Удалить</button></div></article>`).join('')||'<div class="empty-panel">Коробов пока нет.</div>'}</div></div><div class="fbs-panel"><div class="fbs-panel-head"><h2>Учёт изделий</h2></div><table class="fbs-inventory"><thead><tr><th>Артикул</th><th>Товар</th><th>Цвет</th><th>Размер</th><th>Количество</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.article)}</td><td>${esc(i.name)}</td><td>${esc(i.color)}</td><td>${esc(i.size)}</td><td><b>${i.qty}</b></td></tr>`).join('')||'<tr><td colspan="5">На складе пока нет изделий.</td></tr>'}</tbody></table></div></section>`;bind(root,w)}
function bind(root,w){root.querySelector('[data-fbs-new-location]')?.addEventListener('click',()=>modal('Новый адрес',[{key:'address',label:'Адрес'}],d=>{if(!d.address)return;addLocation(w,{address:d.address,x:w.cells.length%w.cols,y:Math.floor(w.cells.length/w.cols)});save(w);render()}));root.querySelector('[data-fbs-new-box]')?.addEventListener('click',()=>modal('Новый короб',[{key:'code',label:'Код короба'}],d=>{if(!d.code)return;addBox(w,{code:d.code});save(w);render()}));root.querySelectorAll('[data-fbs-lock]').forEach(b=>b.onclick=()=>{const box=w.boxes.find(x=>x.id===b.dataset.fbsLock);if(!box)return;setBoxLock(w,box.id,!box.locked);save(w);render()});root.querySelectorAll('[data-fbs-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Удалить выбранный короб?'))return;removeBox(w,b.dataset.fbsDelete);save(w);render()});root.querySelectorAll('[data-fbs-content]').forEach(b=>b.onclick=()=>{const box=w.boxes.find(x=>x.id===b.dataset.fbsContent);if(!box)return;modal('Добавить изделие',[{key:'article',label:'Артикул'},{key:'name',label:'Наименование'},{key:'color',label:'Цвет'},{key:'size',label:'Размер'},{key:'qty',label:'Количество',value:'1'}],d=>{const qty=Number(d.qty);if(!d.article||!Number.isFinite(qty)||qty<=0)return;putItem(w,box.id,{article:d.article,name:d.name,color:d.color,size:d.size,qty});save(w);render()})})}
export function mountUnifiedFbs(){if(mounted)return;mounted=true;const observer=new MutationObserver(render);observer.observe(document.body,{childList:true,subtree:true});render()}
