const VERSION=3;
const uid=()=>crypto.randomUUID();
const qrCode=()=>`BJOB-${crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase()}`;
const touch=w=>{w.updatedAt=new Date().toISOString()};
const box=(w,id)=>{const b=w.boxes.find(x=>x.id===id);if(!b)throw Error('Короб не найден');return b};
export const DESIGN_TOOLS=Object.freeze(['select','wall','rect','partition','window','route','entrance','erase']);
export const DESIGN_LABELS=Object.freeze({select:'Выбор',wall:'Стена',rect:'Прямоугольник',partition:'Перегородка',window:'Окно',route:'Маршрут',entrance:'Вход / выход',erase:'Ластик'});
export function createStore(name='Основной магазин'){return {id:uid(),name:String(name||'').trim()||'Основной магазин',warehouses:[],activeWarehouseId:null,updatedAt:new Date().toISOString()}}
export function createFbsWarehouseState(name){const store=createStore();const warehouse=createWarehouse(name);store.warehouses.push(warehouse);store.activeWarehouseId=warehouse.id;return store}
export function createWarehouse(name='Новый склад'){return {version:VERSION,id:uid(),name:String(name||'').trim()||'Новый склад',address:'',canvas:{width:1600,height:1000},walls:[],zones:[],entrances:[],features:[],boxes:[],assemblyTasks:[],updatedAt:new Date().toISOString(),designLocked:false}}
export const canEditLayout=w=>!w.designLocked;
export const finishLayout=w=>{w.designLocked=true;touch(w);return w};
export const reopenLayout=w=>{w.designLocked=false;touch(w);return w};
export function normalizeWarehouse(w){if(!w||typeof w!=='object')throw Error('Некорректные данные склада');w.version=VERSION;w.walls=Array.isArray(w.walls)?w.walls:[];w.zones=Array.isArray(w.zones)?w.zones:[];w.entrances=Array.isArray(w.entrances)?w.entrances:[];w.features=Array.isArray(w.features)?w.features:[];w.boxes=Array.isArray(w.boxes)?w.boxes:[];w.assemblyTasks=Array.isArray(w.assemblyTasks)?w.assemblyTasks:[];w.canvas=w.canvas&&typeof w.canvas==='object'?w.canvas:{width:1600,height:1000};if(typeof w.designLocked!=='boolean')w.designLocked=false;for(const z of w.zones){z.boxIds=Array.isArray(z.boxIds)?z.boxIds:[];z.capacity=Math.max(0,Number(z.capacity)||0);z.width=Math.max(160,Number(z.width)||200);z.height=Math.max(100,Number(z.height)||120);z.x=Number.isFinite(Number(z.x))?Number(z.x):0;z.y=Number.isFinite(Number(z.y))?Number(z.y):0}for(const b of w.boxes){if(!('zoneId'in b))b.zoneId=null;b.contents=Array.isArray(b.contents)?b.contents:[]}return w}
export function normalizeStore(value){if(!value||typeof value!=='object')return createStore();if(Array.isArray(value.warehouses)){const store={id:value.id||uid(),name:String(value.name||'Основной магазин'),warehouses:value.warehouses.map(normalizeWarehouse),activeWarehouseId:value.activeWarehouseId||null,updatedAt:value.updatedAt||new Date().toISOString()};if(!store.activeWarehouseId||!store.warehouses.some(x=>x.id===store.activeWarehouseId))store.activeWarehouseId=store.warehouses[0]?.id||null;return store}const legacy=normalizeWarehouse(value);const store=createStore();store.warehouses=[legacy];store.activeWarehouseId=legacy.id;return store}
export function addWarehouse(store,name,address=''){const w=createWarehouse(name);w.address=String(address||'').trim();store.warehouses.push(w);store.activeWarehouseId=w.id;store.updatedAt=new Date().toISOString();return w}
export function removeWarehouse(store,id){if(store.warehouses.length<=1)throw Error('Нельзя удалить последний склад. Сначала создайте другой склад.');store.warehouses=store.warehouses.filter(x=>x.id!==id);if(!store.warehouses.some(x=>x.id===store.activeWarehouseId))store.activeWarehouseId=store.warehouses[0].id;store.updatedAt=new Date().toISOString()}
export function getActiveWarehouse(store){return store.warehouses.find(x=>x.id===store.activeWarehouseId)||null}
export function selectWarehouse(store,id){if(!store.warehouses.some(x=>x.id===id))throw Error('Склад не найден');store.activeWarehouseId=id;store.updatedAt=new Date().toISOString();return getActiveWarehouse(store)}
export function addWall(w,x1,y1,x2,y2,type='wall'){if(!canEditLayout(w))throw Error('Планировка заблокирована');w.walls.push({id:uid(),x1,y1,x2,y2,type});touch(w);return w.walls.at(-1)}
export function addZone(w,{name,capacity=0,x=0,y=0,width=200,height=120}={}){if(!canEditLayout(w))throw Error('Планировка заблокирована');if(!name)throw Error('Название зоны обязательно');const z={id:uid(),name:String(name).trim(),capacity:Math.max(0,Number(capacity)||0),x,y,width:Math.max(160,Number(width)||200),height:Math.max(100,Number(height)||120),boxIds:[]};w.zones.push(z);touch(w);return z}
export function resizeZone(w,id,{width,height}={}){if(!canEditLayout(w))throw Error('Планировка заблокирована');const z=w.zones.find(x=>x.id===id);if(!z)throw Error('Зона не найдена');z.width=Math.max(160,Number(width)||z.width);z.height=Math.max(100,Number(height)||z.height);touch(w);return z}
export function setZoneCapacity(w,id,capacity){if(!canEditLayout(w))throw Error('Планировка заблокирована');const z=w.zones.find(x=>x.id===id);if(!z)throw Error('Зона не найдена');const n=Math.max(0,Math.floor(Number(capacity)||0));if(n&&z.boxIds.length>n)throw Error(`В зоне уже ${z.boxIds.length} коробов. Вместимость нельзя уменьшить до ${n}.`);z.capacity=n;touch(w);return z}
export function addEntrance(w,{name='Вход',x=0,y=0,type='entry'}={}){if(!canEditLayout(w))throw Error('Планировка заблокирована');const e={id:uid(),name,x,y,type};w.entrances.push(e);touch(w);return e}
export function addFeature(w,{type='partition',x=0,y=0,width=120,height=10,label=''}={}){if(!canEditLayout(w))throw Error('Планировка заблокирована');const f={id:uid(),type,x,y,width,height,label};w.features.push(f);touch(w);return f}
export function removeWall(w,id){if(!canEditLayout(w))throw Error('Планировка заблокирована');w.walls=w.walls.filter(x=>x.id!==id);touch(w)}
export function removeFeature(w,id){if(!canEditLayout(w))throw Error('Планировка заблокирована');w.features=w.features.filter(x=>x.id!==id);touch(w)}
export function addBox(w,{zoneId=null,code=qrCode(),color='',type='mono'}={}){const z=zoneId?w.zones.find(x=>x.id===zoneId):null;if(zoneId&&!z)throw Error('Зона не найдена');if(w.boxes.some(x=>x.code===code))throw Error('Такой код короба уже существует');if(z&&z.capacity&&z.boxIds.length>=z.capacity)throw Error('В зоне нет свободного места');const b={id:uid(),code,qr:code,qrPayload:'',color,type,zoneId:z?.id||null,locked:false,contents:[]};b.qrPayload=`BJOB-FBS|${b.id}|${code}`;w.boxes.push(b);if(z)z.boxIds.push(b.id);touch(w);return b}
export function setBoxContents(w,boxId,item){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');const qty=Number(item.qty);if(!item.article||!Number.isFinite(qty)||qty<=0)throw Error('Некорректное изделие');const r=b.contents.find(x=>x.article===item.article&&x.color===item.color&&x.size===item.size);r?r.qty+=qty:b.contents.push({...item,qty});touch(w);return b}
export function moveBox(w,boxId,zoneId){const b=box(w,boxId);const to=zoneId?w.zones.find(x=>x.id===zoneId):null;if(zoneId&&!to)throw Error('Зона не найдена');if(to&&to.capacity&&to.boxIds.length>=to.capacity)throw Error('В зоне нет свободного места');const from=w.zones.find(x=>x.id===b.zoneId);if(from)from.boxIds=from.boxIds.filter(id=>id!==b.id);if(to)to.boxIds.push(b.id);b.zoneId=to?.id||null;touch(w);return b}
export function removeBox(w,boxId){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');const z=w.zones.find(x=>x.id===b.zoneId);if(z)z.boxIds=z.boxIds.filter(x=>x!==boxId);w.boxes=w.boxes.filter(x=>x.id!==boxId);touch(w)}
export function removeZone(w,id){if(!canEditLayout(w))throw Error('Планировка заблокирована');normalizeWarehouse(w);const z=w.zones.find(x=>x.id===id);if(!z)throw Error('Зона не найдена');const ids=new Set(z.boxIds);for(const b of w.boxes)if(b.zoneId===id||ids.has(b.id))b.zoneId=null;w.zones=w.zones.filter(x=>x.id!==id);touch(w);return w}
export function lockBox(w,boxId,locked=true){const b=box(w,boxId);b.locked=!!locked;touch(w);return b}
export function warehouseInventory(w){const map=new Map();for(const b of w.boxes)for(const i of b.contents){const k=[i.article,i.color||'',i.size||''].join('|');const r=map.get(k)||{article:i.article,name:i.name||'',color:i.color||'',size:i.size||'',qty:0,boxes:0};r.qty+=Number(i.qty)||0;r.boxes++;map.set(k,r)}return [...map.values()]}
export const sortInventory=rows=>[...(Array.isArray(rows)?rows:[])].sort((a,b)=>String(a.article||a.name||'').localeCompare(String(b.article||b.name||''),'ru',{numeric:true,sensitivity:'base'}));
export function scanBox(w,code){const raw=String(code||'').trim();const m=raw.match(/^BJOB-FBS\|([^|]+)\|(.+)$/);const id=m?.[1]||null,bc=m?.[2]||raw;const b=w.boxes.find(x=>(id&&x.id===id)||x.code===bc||x.qr===raw||x.qrPayload===raw);if(!b)throw Error('Короб не найден');return b}
export function consumeForOrder(w,boxId,item,orderArticles=[]){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');if(orderArticles.length&&!orderArticles.includes(item.article))throw Error('Изделие отсутствует в текущем заказе');const r=b.contents.find(x=>x.article===item.article&&x.color===item.color&&x.size===item.size);if(!r||r.qty<1)throw Error('Изделия нет в коробе');r.qty--;touch(w);return r}
export function createAssemblyTask(w,lines){const task={id:uid(),status:'Новая',lines:lines.map(x=>({...x})),roadmap:lines.map((x,i)=>({order:i+1,article:x.article,qty:x.qty,status:'Ожидает'})),createdAt:new Date().toISOString()};w.assemblyTasks.push(task);touch(w);return task}
export function setTaskStatus(w,id,status){const t=w.assemblyTasks.find(x=>x.id===id);if(!t)throw Error('Задание не найдено');t.status=status;touch(w);return t}
