const VERSION=2;
const uid=()=>crypto.randomUUID();
export function createWarehouse(name='Новый склад'){return {version:VERSION,id:uid(),name,canvas:{width:1200,height:800},walls:[],zones:[],entrances:[],boxes:[],assemblyTasks:[],updatedAt:new Date().toISOString()};}
export function addWall(w,x1,y1,x2,y2){w.walls.push({id:uid(),x1,y1,x2,y2});touch(w);return w.walls.at(-1)}
export function addZone(w,{name,capacity=0,x=0,y=0,width=200,height=120}={}){if(!name)throw Error('Название зоны обязательно');const z={id:uid(),name,capacity:Number(capacity)||0,x,y,width,height,boxIds:[]};w.zones.push(z);touch(w);return z}
export function addEntrance(w,{name='Вход',x=0,y=0,type='entry'}={}){const e={id:uid(),name,x,y,type};w.entrances.push(e);touch(w);return e}
export function addBox(w,{zoneId,code=`BOX-${Date.now()}`,color='',type='mono'}={}){const z=w.zones.find(x=>x.id===zoneId);if(!z)throw Error('Сначала выберите зону');if(w.boxes.some(x=>x.code===code))throw Error('Такой QR/код короба уже существует');if(z.capacity&&z.boxIds.length>=z.capacity)throw Error('В зоне нет свободного места');const b={id:uid(),code,qr:code,color,type,zoneId,locked:false,contents:[]};w.boxes.push(b);z.boxIds.push(b.id);touch(w);return b}
export function setBoxContents(w,boxId,item){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');if(!item.article||item.qty<=0)throw Error('Некорректное изделие');const r=b.contents.find(x=>x.article===item.article&&x.color===item.color&&x.size===item.size);r?r.qty+=Number(item.qty):b.contents.push({...item,qty:Number(item.qty)});touch(w);return b}
export function moveBox(w,boxId,zoneId){const b=box(w,boxId),to=w.zones.find(x=>x.id===zoneId);if(!to)throw Error('Зона не найдена');if(to.capacity&&to.boxIds.length>=to.capacity)throw Error('В зоне нет свободного места');const from=w.zones.find(x=>x.id===b.zoneId);if(from)from.boxIds=from.boxIds.filter(id=>id!==b.id);to.boxIds.push(b.id);b.zoneId=zoneId;touch(w);return b}
export function removeBox(w,boxId){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');const z=w.zones.find(x=>x.id===b.zoneId);if(z)z.boxIds=z.boxIds.filter(id=>id!==b.id);w.boxes=w.boxes.filter(x=>x.id!==boxId);touch(w)}
export function lockBox(w,boxId,locked=true){const b=box(w,boxId);b.locked=!!locked;touch(w);return b}
export function warehouseInventory(w){const map=new Map();for(const b of w.boxes)for(const i of b.contents){const k=[i.article,i.color||'',i.size||''].join('|');const r=map.get(k)||{article:i.article,name:i.name||'',color:i.color||'',size:i.size||'',qty:0,boxes:0};r.qty+=Number(i.qty);r.boxes++;map.set(k,r)}return [...map.values()]}
export function scanBox(w,code){const b=w.boxes.find(x=>x.code===code||x.qr===code);if(!b)throw Error('Короб не найден');return b}
export function consumeForOrder(w,boxId,item,orderArticles=[]){const b=box(w,boxId);if(b.locked)throw Error('Короб заблокирован');if(!orderArticles.includes(item.article))throw Error('Изделие отсутствует в текущем заказе');const r=b.contents.find(x=>x.article===item.article&&x.color===item.color&&x.size===item.size);if(!r||r.qty<1)throw Error('Изделия нет в коробе');r.qty--;touch(w);return r}
export function createAssemblyTask(w,lines){const task={id:uid(),status:'Новая',lines:lines.map(x=>({...x})),roadmap:lines.map((x,i)=>({order:i+1,article:x.article,qty:x.qty,status:'Ожидает'})),createdAt:new Date().toISOString()};w.assemblyTasks.push(task);touch(w);return task}
export function setTaskStatus(w,id,status){const t=w.assemblyTasks.find(x=>x.id===id);if(!t)throw Error('Задание не найдено');t.status=status;touch(w);return t}
function box(w,id){const b=w.boxes.find(x=>x.id===id);if(!b)throw Error('Короб не найден');return b}
function touch(w){w.updatedAt=new Date().toISOString()}
