import './fbsWarehouse.css';
import {createWarehouse,addWall,addZone,addEntrance,addBox,setBoxContents,moveBox,removeBox,lockBox,warehouseInventory,scanBox} from './fbsWarehouseV2.js';
const KEY='bjob:fbs:v2';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}};
const save=w=>localStorage.setItem(KEY,JSON.stringify(w));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dialog(title,fields,done){const d=document.createElement('dialog');d.className='bjob-fbs-dialog';d.innerHTML=`<form method="dialog"><h2>${esc(title)}</h2>${fields.map(f=>`<label>${esc(f.label)}<input name="${f.key}" value="${esc(f.value||'')}"></label>`).join('')}<footer><button value="cancel">Отмена</button><button value="ok" class="primary">Готово</button></footer></form>`;document.body.append(d);d.addEventListener('close',()=>{if(d.returnValue==='ok'){const v={};d.querySelectorAll('input').forEach(i=>v[i.name]=i.value);done(v)}d.remove()});d.showModal()}
export function mountFbsWarehouseScreen(root=document.querySelector('#view')){if(!root)return;const w=load();if(!w){root.innerHTML='<section class="fbs-screen fbs-empty"><div><h1>Склад FBS</h1><p>Добавьте склад, чтобы начать проектирование.</p><button class="primary" data-create>Добавить склад</button></div></section>';root.querySelector('[data-create]').onclick=()=>dialog('Новый склад',[{key:'name',label:'Название'}],v=>{if(v.name){save(createWarehouse(v.name));mountFbsWarehouseScreen(root)}});return}draw(root,w)}
function draw(root,w){const inv=warehouseInventory(w);root.innerHTML=`<section class="fbs-screen"><header class="fbs-head"><div><small>B-JOB / Склад FBS</small><h1>${esc(w.name)}</h1><p>Проектирование и адресное хранение</p></div><nav><button data-tool="wall">Нарисовать стену</button><button data-tool="zone">Создать зону</button><button data-tool="entrance">Вход / выход</button><button data-tool="scan">Сканировать</button></nav></header><main class="fbs-workspace"><div class="fbs-canvas"><span class="fbs-hint">Размещайте зоны и короба внутри схемы склада.</span>${w.walls.map(x=>`<i class="fbs-wall" style="left:${x.x1}px;top:${x.y1}px;width:${Math.max(2,Math.hypot(x.x2-x.x1,x.y2-x.y1))}px;transform:rotate(${Math.atan2(x.y2-x.y1,x.x2-x.x1)}rad)"></i>`).join('')}${w.entrances.map(e=>`<span class="fbs-entrance" style="left:${e.x}px;top:${e.y}px">${esc(e.name)}</span>`).join('')}${w.zones.map(z=>zoneMarkup(w,z)).join('')}</div><aside class="fbs-accounting"><h2>Учёт склада</h2><table><thead><tr><th>Изделие</th><th>Количество</th><th>Коробов</th></tr></thead><tbody>${inv.map(i=>`<tr><td><b>${esc(i.name||i.article)}</b><small>${esc([i.article,i.color,i.size].filter(Boolean).join(' · '))}</small></td><td>${i.qty}</td><td>${i.boxes}</td></tr>`).join('')||'<tr><td colspan="3">На складе нет изделий</td></tr>'}</tbody></table></aside></main></section>`;bind(root,w)}
function zoneMarkup(w,z){return `<article class="fbs-zone" style="left:${z.x}px;top:${z.y}px;width:${z.width}px;height:${z.height}px"><header><b>${esc(z.name)}</b><small>${z.boxIds.length} / ${z.capacity||'∞'} мест</small><button data-add-box="${z.id}">+ Короб</button></header>${z.boxIds.map(id=>{const b=w.boxes.find(x=>x.id===id);return `<div class="fbs-box ${b?.locked?'locked':''}"><span><b>${esc(b?.code)}</b><small>${b?.contents.reduce((n,x)=>n+Number(x.qty),0)||0} изделий</small></span><button data-content="${id}">Содержимое</button><button data-move="${id}">Переместить</button><button data-lock="${id}">${b?.locked?'Разблокировать':'Блокировать'}</button><button data-delete="${id}">Удалить</button></div>`}).join('')}</article>`}
function bind(root,w){root.querySelector('[data-tool="wall"]').onclick=()=>{const x=80+(w.walls.length%4)*120;addWall(w,x,100,x+300,100);save(w);draw(root,w)};root.querySelector('[data-tool="zone"]').onclick=()=>dialog('Новая зона',[{key:'name',label:'Название зоны'},{key:'capacity',label:'Мест',value:'10'}],v=>{if(!v.name)return;addZone(w,{name:v.name,capacity:v.capacity,x:50+(w.zones.length%4)*240,y:50+Math.floor(w.zones.length/4)*190});save(w);draw(root,w)});root.querySelector('[data-tool="entrance"]').onclick=()=>dialog('Вход / выход',[{key:'name',label:'Название',value:'Вход'}],v=>{addEntrance(w,{name:v.name,x:30+w.entrances.length*100,y:20});save(w);draw(root,w)});root.querySelector('[data-tool="scan"]').onclick=()=>dialog('Сканирование',[{key:'code',label:'QR / код короба'}],v=>{try{const b=scanBox(w,v.code);alert(`Короб ${b.code}\nИзделий: ${b.contents.reduce((n,x)=>n+Number(x.qty),0)}`)}catch(e){alert(e.message)}});root.querySelectorAll('[data-add-box]').forEach(b=>b.onclick=()=>dialog('Добавить короб',[{key:'code',label:'QR / код'},{key:'type',label:'Тип',value:'mono'}],v=>{if(!v.code)return;addBox(w,{zoneId:b.dataset.addBox,code:v.code,type:v.type});save(w);draw(root,w)}));root.querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>dialog('Содержимое короба',[{key:'article',label:'Артикул'},{key:'name',label:'Изделие'},{key:'color',label:'Цвет'},{key:'size',label:'Размер'},{key:'qty',label:'Количество',value:'1'}],v=>{setBoxContents(w,b.dataset.content,{...v,qty:Number(v.qty)});save(w);draw(root,w)}));root.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>{const box=w.boxes.find(x=>x.id===b.dataset.lock);lockBox(w,box.id,!box.locked);save(w);draw(root,w)});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Удалить короб?')){removeBox(w,b.dataset.delete);save(w);draw(root,w)}});root.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>dialog('Переместить короб',[{key:'zoneId',label:'ID зоны'}],v=>{moveBox(w,b.dataset.move,v.zoneId);save(w);draw(root,w)}))}
