import * as DB from '../db.js';
import { session, logout, listShops, createShop, setActiveShop, activeShop, listUsers, createUser, setActive, organization, listWorkspaces, createWorkspace, setActiveWorkspace, activeWorkspace } from './userAuth.js';

const app = document.querySelector('#app');
const routes = {
  home:['Главная','Единый операционный центр'],reports:['Отчёты','Отчёты и выгрузки'],products:['Товары','Номенклатура'],shops:['Магазины','Магазины и подключения'],cabinet:['Личный кабинет','Профиль и доступ'],analytics:['Аналитика','Показатели и динамика'],
  fbo:['Склад FBO','Склад FBO'],fbs:['Склад FBS','Склад FBS'],transfers:['Перемещения FBO → FBS','Пополнение FBS'],shipments:['Поставки','Поставки'],fbsShipments:['Поставки FBS','Поставки FBS'],production:['Производство','Производство'],salesHistory:['История продаж','История продаж'],
  api:['Интеграция по API','API подключения'],lan:['Интеграция по LAN','LAN'],sync:['Синхронизация','Синхронизация'],personal:['Персональный доступ','Права'],prices:['Цены и скидки','Цены'],tables:['Таблицы','Данные'],workspaces:['Рабочие пространства','Пространства'],history:['История изменений','Аудит'],settings:['Настройки','Настройки'],organization:['Организация','Организация'],users:['Пользователи','Пользователи'],employees:['Сотрудники','Сотрудники'],backups:['Резервные копии','Резервные копии'],fbsStats:['Статистика FBS','Статистика FBS']
};
const groups = [['Главная',['home']],['Отчёты',['reports','analytics','salesHistory']],['Товары',['products','prices','tables']],['Магазины',['shops','cabinet']],['Склады',['fbo','fbs','transfers']],['Поставки',['shipments','fbsShipments']],['Производство',['production']],['Интеграции',['api','lan','sync']],['Управление',['workspaces','organization','users','employees','personal','settings','history','backups']],['FBS аналитика',['fbsStats']]];
const state = { route: localStorage.getItem('bjob:route') || 'home' };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = p => `${p}-${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const count = async store => { try { return (await DB.all(store)).length; } catch { return 0; } };
async function audit(type, details={}) { try { await DB.put('audit',{id:uid('audit'),type,userId:session()?.id||null,login:session()?.login||null,date:now(),details}); } catch(e) { console.warn('B-JOB audit',e); } }
function toast(text,error=false){let t=document.querySelector('#bjob-toast');if(!t){t=document.createElement('div');t.id='bjob-toast';document.body.appendChild(t)}t.textContent=text;t.dataset.type=error?'error':'ok';clearTimeout(window.__bjobToast);window.__bjobToast=setTimeout(()=>t.remove(),2600)}
function navigate(route){if(!routes[route])return;state.route=route;localStorage.setItem('bjob:route',route);render().catch(fatal)}
function btn(label,action,id='',kind=''){return `<button class="ui-btn" data-action="${esc(action)}"${id?` data-id="${esc(id)}"`:''}${kind?` data-kind="${esc(kind)}"`:''}>${esc(label)}</button>`}
function cards(items){return `<div class="metric-grid">${items.map(([a,b,c])=>`<article class="metric-card"><span>${esc(a)}</span><strong>${esc(b)}</strong>${c?`<small>${esc(c)}</small>`:''}</article>`).join('')}</div>`}
function page(title,subtitle,body){return `<section class="page"><div class="page-head"><div><div class="eyebrow">B-JOB / ${esc(routes[state.route]?.[0]||'')}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div></div>${body}</section>`}
function topNav(){return groups.map(([label,ids])=>ids.length===1?`<button class="nav-link ${state.route===ids[0]?'active':''}" data-route="${ids[0]}">${esc(label)}</button>`:`<div class="nav-group"><button class="nav-link ${ids.includes(state.route)?'active':''}" data-nav-toggle>${esc(label)} <span>⌄</span></button><div class="nav-dropdown">${ids.map(id=>`<button data-route="${id}">${esc(routes[id][0])}</button>`).join('')}</div></div>`).join('')}
async function shell(){const user=session();const [shop,shops,workspace,workspaces]=await Promise.all([activeShop(),listShops(),activeWorkspace(),listWorkspaces()]);app.innerHTML=`<div class="bjob-app"><header class="app-top"><div class="brand"><div>B-JOB</div><span>операционная система бизнеса</span></div><nav class="app-nav">${topNav()}</nav><div class="context"><select id="workspace-select">${workspaces.map(w=>`<option value="${esc(w.id)}" ${w.id===workspace?.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select><select id="shop-select"><option value="">Магазин</option>${shops.map(s=>`<option value="${esc(s.id)}" ${s.id===shop?.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select><span>${esc(user?.name||'Администратор')}</span><button class="user-btn" data-action="logout">Выйти</button></div></header><main id="view"></main></div>`;
  document.querySelectorAll('[data-nav-toggle]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.nav-group.open').forEach(x=>x!==b.parentElement&&x.classList.remove('open'));b.parentElement.classList.toggle('open')}));
  document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-group.open').forEach(x=>x.classList.remove('open'));navigate(b.dataset.route)}));
  document.addEventListener('click',closeMenus,{once:true});
  document.querySelector('#shop-select').addEventListener('change',async e=>{try{if(e.target.value)await setActiveShop(e.target.value);await audit('shop.switch',{shopId:e.target.value});await render()}catch(err){toast(err.message,true)}});
  document.querySelector('#workspace-select').addEventListener('change',async e=>{try{await setActiveWorkspace(e.target.value);await audit('workspace.switch',{workspaceId:e.target.value});await render()}catch(err){toast(err.message,true)}});
  document.querySelector('[data-action="logout"]').addEventListener('click',()=>{logout();location.reload()});
}
function closeMenus(){document.querySelectorAll('.nav-group.open').forEach(x=>x.classList.remove('open'))}
function bind(){document.querySelectorAll('#view [data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));document.querySelectorAll('#view [data-action]').forEach(b=>b.addEventListener('click',()=>runAction(b.dataset.action,b.dataset.id,b.dataset.kind)))}
async function render(){await shell();const view=document.querySelector('#view');const [title,desc]=routes[state.route];let html;
  switch(state.route){case'home':html=await dashboard();break;case'reports':html=await reports();break;case'products':html=await products();break;case'shops':html=await shops();break;case'workspaces':html=await workspaces();break;case'users':html=await users(false);break;case'employees':html=await users(true);break;case'organization':html=await organizationPage();break;case'settings':html=await settings();break;case'history':html=await history();break;case'fbo':html=await warehouse('FBO');break;case'fbs':html=await warehouse('FBS');break;case'transfers':html=await transfers();break;case'analytics':html=await analytics();break;case'salesHistory':html=await dataPage('sales','История продаж');break;case'fbsStats':html=await dataPage('fbs','Статистика FBS');break;case'shipments':html=await shipments(false);break;case'fbsShipments':html=await shipments(true);break;case'production':html=await production();break;case'prices':html=await prices();break;case'tables':html=await tables();break;case'api':html=await api();break;case'lan':html=await lan();break;case'sync':html=await sync();break;case'personal':html=await personal();break;case'cabinet':html=await cabinet();break;case'backups':html=await backups();break;default:html=page(title,desc,cards([['Статус','Доступен']]));}view.innerHTML=html;bind()}
async function dashboard(){const [products,sales,stocks,warehouses,boxes,moves,shipments,productionOrders]=await Promise.all(['products','sales','stocks','warehouses','boxes','warehouseMoves','shipments','productionOrders'].map(count));const boxRows=await DB.all('boxes');const locked=boxRows.filter(b=>b.locked).length;const mono=boxRows.filter(b=>b.boxType==='mono').length;const mix=boxRows.filter(b=>b.boxType==='mix').length;return page('Главная','Живой центр управления бизнесом',cards([['Товары',products],['Продажи',sales],['Остатки',stocks],['Склады',warehouses],['Короба',boxes],['Заблокировано',locked],['Моно-короба',mono],['Микс-короба',mix],['Перемещения',moves],['Поставки',shipments],['Производство',productionOrders]])+`<div class="hero-grid"><article class="hero-card"><div class="hero-orbit"></div><div><span>Операционный центр</span><h2>Всё важное — на одном экране</h2><p>Склад, товары, поставки и движение продукции под текущим пространством и магазином.</p></div></article><div class="quick-grid">${btn('Склад FBO','route','fbo')}${btn('Склад FBS','route','fbs')}${btn('FBO → FBS','route','transfers')}${btn('Товары','route','products')}${btn('Магазины','route','shops')}${btn('Отчёты','route','reports')}</div></div><div class="storage-summary"><div><b>Учёт хранения</b><span>${boxes} коробов · ${mono} моно · ${mix} микс</span></div><button class="ui-btn ghost" data-route="fbs">Открыть склад</button></div>`)}
async function reports(){return page('Отчёты','Сводные данные и локальные выгрузки',cards([['Продажи',await count('sales')],['Остатки',await count('stocks')],['Реклама',await count('ads')],['Расходы',await count('expenses')]])+`<div class="action-row">${btn('Экспорт JSON','export-json')}${btn('Резервная копия','backup-export')}${btn('Импорт XLSX','import-xlsx')}</div>`)}
async function analytics(){return page('Аналитика','Динамика бизнеса',cards([['Продажи',await count('sales')],['Остатки',await count('stocks')],['Реклама',await count('ads')],['Расходы',await count('expenses')]])+`<div class="empty-panel"><b>Центр динамики</b><p>После загрузки данных здесь отображаются реальные показатели и графики текущего магазина.</p></div>`)}
async function products(){const rows=await DB.all('products');return page('Товары','Номенклатура и карточки',`<div class="action-row">${btn('Добавить товар','add-product')}${btn('Импорт XLSX','import-xlsx')}${btn('Экспорт JSON','export-json')}</div>${table(rows,['article','name','sku','color','size','price','cost','quantity'])}`)}
async function prices(){return page('Цены и скидки','Управление ценами',`<div class="action-row">${btn('Изменить цену','set-price')}</div>${table(await DB.all('products'),['article','name','price','cost'])}`)}
async function shops(){const rows=await listShops();return page('Магазины','Подключённые магазины',`<div class="action-row">${btn('Добавить магазин','add-shop')}</div><div class="list">${rows.map(s=>`<article><div><b>${esc(s.name)}</b><small>${esc(String(s.marketplace||'').toUpperCase())}</small></div>${btn('Выбрать','choose-shop',s.id)}</article>`).join('')||'<div class="empty-panel">Магазинов пока нет.</div>'}</div>`)}
async function workspaces(){const rows=await listWorkspaces();return page('Рабочие пространства','Изолированные контуры данных',`<div class="action-row">${btn('Создать пространство','add-workspace')}</div><div class="list">${rows.map(w=>`<article><div><b>${esc(w.name)}</b><small>${esc(w.description||'')}</small></div>${btn('Выбрать','choose-workspace',w.id)}</article>`).join('')}</div>`)}
async function users(employees){const rows=await listUsers();return page(employees?'Сотрудники':'Пользователи',employees?'Управление сотрудниками и доступом':'Пользователи организации',`<div class="action-row">${btn('Добавить сотрудника','add-user')}</div><div class="list">${rows.map(u=>`<article><div><b>${esc(u.name)}</b><small>${esc(u.login)} · ${esc(u.role)}</small></div>${btn(u.active===false?'Включить':'Отключить','toggle-user',u.id)}</article>`).join('')}</div>`)}
async function organizationPage(){const o=await organization();return page('Организация','Параметры организации',cards([['Название',o?.name||'B-JOB'],['Режим','Local-first']])+`<div class="action-row">${btn('Изменить название','organization-name')}</div>`)}
async function cabinet(){return page('Личный кабинет','Профиль текущего пользователя',cards([['Пользователь',session()?.name||'—'],['Логин',session()?.login||'—'],['Роль',session()?.role||'—'],['Пространство',(await activeWorkspace())?.name||'—'],['Магазин',(await activeShop())?.name||'Не выбран']]))}
async function personal(){return page('Персональный доступ','Права пользователя',cards([['Роль',session()?.role||'—'],['Полный доступ',session()?.permissions?.all?'Да':'Нет']]))}
async function settings(){return page('Настройки','Настройки B-JOB',cards([['Режим','Local-first'],['Хранилище','IndexedDB'],['Offline','Готово'],['DB',DB.DB_VERSION]])+`<div class="action-row">${btn('Экспорт базы','backup-export')}</div>`)}
async function history(){return page('История изменений','Аудит операций',table(await DB.all('audit'),['date','type','login','details']))}
async function warehouse(type){const rows=(await DB.all('warehouses')).filter(w=>String(w.type).toUpperCase()===type);const boxes=(await DB.all('boxes')).filter(b=>rows.some(w=>w.id===b.warehouseId));const mono=boxes.filter(b=>b.boxType==='mono').length,mix=boxes.filter(b=>b.boxType==='mix').length,locked=boxes.filter(b=>b.locked).length;return page(`Склад ${type}`,type==='FBO'?'Полный контроль FBO':'Полный контроль FBS',cards([['Склады',rows.length],['Короба',boxes.length],['Моно',mono],['Микс',mix],['Заблокировано',locked]])+`<div class="action-row">${btn('Создать склад','add-warehouse','',type)}${btn('Создать короб','add-box','',type)}</div><div class="warehouse-grid-list">${rows.map(w=>`<article class="warehouse-card"><div class="warehouse-card-head"><div><b>${esc(w.name)}</b><small>${w.rows||1} × ${w.cols||1} ячеек · ${w.zones||1} зон</small></div><span>${boxes.filter(b=>b.warehouseId===w.id).length} коробов</span></div><div class="rack" style="--cols:${Math.min(Number(w.cols)||1,14)}">${Array.from({length:Math.min((Number(w.rows)||1)*(Number(w.cols)||1),196)},(_,i)=>`<i>${String(i+1).padStart(2,'0')}</i>`).join('')}</div></article>`).join('')||'<div class="empty-panel">Складов пока нет.</div>'}</div><h3 class="subhead">Короба</h3>${table(boxes,['code','boxType','locked','warehouseId','createdAt'])}<div class="action-row">${boxes.map(b=>btn(b.locked?'Разблокировать':'Заблокировать','toggle-box',b.id)).join('')}</div>`)}
async function transfers(){return page('Перемещения FBO → FBS','Пополнение FBS со склада FBO',`<div class="action-row">${btn('Создать перемещение','add-transfer')}</div>${table((await DB.all('warehouseMoves')).filter(x=>x.kind==='FBO_TO_FBS'),['date','fromWarehouse','toWarehouse','sku','quantity','status'])}`)}
async function shipments(fbs){return page(fbs?'Поставки FBS':'Поставки',fbs?'Поставки на FBS':'Поставки на FBO',`<div class="action-row">${btn('Создать поставку',fbs?'add-fbs-shipment':'add-shipment')}</div>${table(await DB.all('shipments'),['date','article','quantity','destination','status'])}`)}
async function production(){return page('Производство','Планирование и выпуск',`<div class="action-row">${btn('Создать заказ','add-production')}</div>${table(await DB.all('productionOrders'),['date','article','quantity','status'])}`)}
async function dataPage(store,title){return page(title,'Операционные данные',table(await DB.all(store),Object.keys((await DB.all(store))[0]||{id:'Нет данных'}).slice(0,8)))}
async function tables(){return page('Таблицы','Данные локальной базы',cards([['Товары',await count('products')],['Остатки',await count('stocks')],['Короба',await count('boxes')],['Перемещения',await count('warehouseMoves')]])+`<div class="action-row">${btn('Импорт XLSX','import-xlsx')}${btn('Экспорт JSON','export-json')}</div>`)}
async function api(){return page('Интеграция по API','Подключения API',`<div class="action-row">${btn('Добавить подключение','add-api')}</div>${table(await DB.all('apiConnections'),['name','marketplace','baseUrl','active'])}`)}
async function lan(){return page('Интеграция по LAN','Локальная сеть',`<div class="action-row">${btn('Переключить LAN','lan-toggle')}</div>`)}
async function sync(){return page('Синхронизация','Состояние обмена',`<div class="action-row">${btn('Экспорт журнала','sync-export')}</div>`)}
async function backups(){return page('Резервные копии','Экспорт и восстановление',`<div class="action-row">${btn('Создать backup','backup-export')}${btn('Восстановить backup','backup-import')}</div>`)}
function table(rows,cols){return `<div class="data-table"><table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,500).map(r=>`<tr>${cols.map(c=>`<td>${esc(typeof r[c]==='object'?JSON.stringify(r[c]):r[c]??'')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">Нет данных</td></tr>`}</tbody></table></div>`}
function modal(title,fields){return new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='modal-layer';overlay.innerHTML=`<div class="modal-card"><button class="modal-x" data-cancel>×</button><div class="eyebrow">B-JOB</div><h2>${esc(title)}</h2><form>${fields.map(f=>`<label>${esc(f.label)}<input name="${esc(f.name)}" type="${f.type||'text'}" value="${esc(f.value||'')}" ${f.required===false?'':'required'} ${f.min?`min="${f.min}"`:''}></label>`).join('')}<div class="modal-actions"><button type="button" class="ui-btn ghost" data-cancel>Отмена</button><button class="ui-btn" type="submit">Сохранить</button></div></form></div>`;document.body.appendChild(overlay);const close=v=>{overlay.remove();resolve(v)};overlay.querySelectorAll('[data-cancel]').forEach(b=>b.addEventListener('click',()=>close(null)));overlay.addEventListener('click',e=>{if(e.target===overlay)close(null)});overlay.querySelector('form').addEventListener('submit',e=>{e.preventDefault();close(Object.fromEntries(new FormData(e.currentTarget).entries()))})})}
async function runAction(type,id,kind){try{
 if(type==='logout'){logout();location.reload();return}
 if(type==='route'){navigate(id);return}
 if(type==='add-shop'){const f=await modal('Добавить магазин',[{name:'name',label:'Название',value:'Новый магазин'},{name:'marketplace',label:'Маркетплейс',value:'WB'}]);if(!f)return;const shop=await createShop(f);await audit('shop.create',{shopId:shop.id});toast('Магазин создан');await render();return}
 if(type==='choose-shop'){await setActiveShop(id);await audit('shop.switch',{shopId:id});await render();return}
 if(type==='add-workspace'){const f=await modal('Новое рабочее пространство',[{name:'name',label:'Название',value:'Новое пространство'},{name:'description',label:'Описание',required:false}]);if(!f)return;const w=await createWorkspace(f);await setActiveWorkspace(w.id);await audit('workspace.create',{workspaceId:w.id});toast('Пространство создано');await render();return}
 if(type==='choose-workspace'){await setActiveWorkspace(id);await audit('workspace.switch',{workspaceId:id});await render();return}
 if(type==='toggle-user'){const users=await listUsers(),u=users.find(x=>x.id===id);if(u){await setActive(id,u.active===false);await audit('user.status',{userId:id,active:u.active===false})}await render();return}
 if(type==='add-user'){const f=await modal('Добавить сотрудника',[{name:'login',label:'Логин'},{name:'name',label:'Имя'},{name:'role',label:'Роль',value:'warehouse'}]);if(!f)return;const r=await createUser(f);await audit('user.create',{userId:r.userId,login:r.login});toast(`Сотрудник создан. Временный пароль: ${r.temporaryPassword}`);await render();return}
 if(type==='organization-name'){const f=await modal('Организация',[{name:'name',label:'Название',value:(await organization())?.name||'B-JOB'}]);if(!f)return;const o=await organization();await DB.put('settings',{...o,name:f.name});await audit('organization.update',{name:f.name});await render();return}
 if(type==='add-product'){const f=await modal('Новый товар',[{name:'article',label:'Артикул'},{name:'name',label:'Название'},{name:'price',label:'Цена',type:'number',value:'0',min:'0'},{name:'cost',label:'Себестоимость',type:'number',value:'0',min:'0'}]);if(!f)return;await DB.put('products',{id:uid('product'),article:f.article.trim(),name:f.name.trim(),sku:f.article.trim(),price:Number(f.price)||0,cost:Number(f.cost)||0,quantity:0,createdAt:now()});await audit('product.create',{article:f.article});toast('Товар создан');await render();return}
 if(type==='set-price'){const rows=await DB.all('products');if(!rows.length){toast('Сначала создайте товар',true);return}const p=rows[0],f=await modal('Изменить цену',[{name:'price',label:`Цена: ${p.name}`,type:'number',value:String(p.price||0),min:'0'}]);if(!f)return;await DB.put('products',{...p,price:Number(f.price)||0,updatedAt:now()});await audit('product.price',{productId:p.id});await render();return}
 if(type==='add-warehouse'){const f=await modal(`Новый склад ${kind}`,[{name:'name',label:'Название',value:`Склад ${kind}`},{name:'rows',label:'Ряды',type:'number',value:'4',min:'1'},{name:'cols',label:'Колонки',type:'number',value:'6',min:'1'},{name:'zones',label:'Зоны',type:'number',value:'1',min:'1'}]);if(!f)return;const row={id:uid('warehouse'),name:f.name.trim(),type:kind,rows:Math.max(1,Number(f.rows)||1),cols:Math.max(1,Number(f.cols)||1),zones:Math.max(1,Number(f.zones)||1),description:`Склад ${kind}`,createdAt:now()};await DB.put('warehouses',row);await audit('warehouse.create',{warehouseId:row.id,type:kind});toast('Склад создан');await render();return}
 if(type==='add-box'){const ws=(await DB.all('warehouses')).filter(w=>w.type===kind);if(!ws.length){toast('Сначала создайте склад',true);return}const f=await modal('Новый короб',[{name:'code',label:'Код',value:`BOX-${Date.now().toString().slice(-6)}`},{name:'boxType',label:'Тип: mono или mix',value:'mono'}]);if(!f)return;const boxType=String(f.boxType).toLowerCase()==='mix'?'mix':'mono';const row={id:uid('box'),warehouseId:ws[0].id,shopId:localStorage.getItem('bjob:v2:active-shop')||null,code:f.code.trim(),boxType,locked:false,qrPayload:`BJOB|BOX|${f.code.trim()}|${ws[0].id}`,contents:[],createdAt:now()};await DB.put('boxes',row);await audit('box.create',{boxId:row.id,warehouseId:ws[0].id,boxType});toast('Короб создан');await render();return}
 if(type==='toggle-box'){const b=await DB.get('boxes',id);if(!b)return;await DB.put('boxes',{...b,locked:!b.locked,lockedAt:!b.locked?now():null,lockedBy:!b.locked?(session()?.id||null):null});await audit('box.lock',{boxId:id,locked:!b.locked});toast(b.locked?'Короб разблокирован':'Короб заблокирован');await render();return}
 if(type==='add-transfer'){const ws=await DB.all('warehouses'),fbo=ws.find(w=>w.type==='FBO'),fbs=ws.find(w=>w.type==='FBS');if(!fbo||!fbs){toast('Создайте FBO и FBS склад',true);return}const f=await modal('Перемещение FBO → FBS',[{name:'sku',label:'Артикул / SKU'},{name:'quantity',label:'Количество',type:'number',value:'1',min:'1'}]);if(!f)return;const row={id:uid('move'),kind:'FBO_TO_FBS',fromWarehouse:fbo.name,toWarehouse:fbs.name,fromWarehouseId:fbo.id,toWarehouseId:fbs.id,sku:f.sku,quantity:Math.max(1,Number(f.quantity)||1),status:'draft',date:now()};await DB.put('warehouseMoves',row);await audit('warehouse.transfer',{moveId:row.id});toast('Перемещение создано');await render();return}
 if(type==='add-shipment'||type==='add-fbs-shipment'){const f=await modal('Новая поставка',[{name:'article',label:'Артикул / SKU'},{name:'quantity',label:'Количество',type:'number',value:'1',min:'1'}]);if(!f)return;await DB.put('shipments',{id:uid('shipment'),article:f.article,quantity:Math.max(1,Number(f.quantity)||1),status:'draft',date:now(),destination:type==='add-fbs-shipment'?'FBS':'FBO'});await audit('shipment.create',{destination:type==='add-fbs-shipment'?'FBS':'FBO'});await render();return}
 if(type==='add-production'){const f=await modal('Производственный заказ',[{name:'article',label:'Артикул / SKU'},{name:'quantity',label:'Количество',type:'number',value:'1',min:'1'}]);if(!f)return;await DB.put('productionOrders',{id:uid('production'),article:f.article,quantity:Math.max(1,Number(f.quantity)||1),status:'planned',date:now()});await audit('production.create',{article:f.article});await render();return}
 if(type==='add-api'){const f=await modal('API подключение',[{name:'name',label:'Название',value:'WB API'},{name:'marketplace',label:'Маркетплейс',value:'WB'},{name:'baseUrl',label:'Base URL',value:'https://'}]);if(!f)return;await DB.put('apiConnections',{id:uid('api'),...f,active:false,createdAt:now()});await audit('api.connection.create',{name:f.name});await render();return}
 if(type==='lan-toggle'){if(!window.bjobDesktop){toast('LAN доступен только в .exe',true);return}const s=await window.bjobDesktop.lanStatus();if(s.enabled)await window.bjobDesktop.lanStop();else await window.bjobDesktop.lanStart();toast('LAN обновлён');return}
 if(type==='sync-export'){if(window.bjobDesktop){await window.bjobDesktop.exportSyncJournal();toast('Журнал экспортирован')}return}
 if(type==='backup-export'||type==='export-json')return exportAll();
 if(type==='backup-import')return importBackup();
 if(type==='import-xlsx')return importXlsx();
 toast(`Действие «${type}» пока не подключено`,true);
 }catch(e){console.error('B-JOB action',type,e);toast(e.message||String(e),true)}}
function fatal(e){console.error('B-JOB UI',e);app.innerHTML=`<div class="fatal"><h1>Ошибка интерфейса</h1><p>${esc(e?.message||e)}</p><button class="ui-btn" onclick="location.reload()">Повторить</button></div>`}
function welcome(){const o=document.createElement('div');o.className='welcome';o.innerHTML='<div class="welcome-mark">B-JOB</div><div class="welcome-line"></div><p>операционная система бизнеса</p>';document.body.appendChild(o);setTimeout(()=>o.classList.add('hide'),850);setTimeout(()=>o.remove(),1450)}
export async function start(){welcome();await render()}
