import * as DB from '../db.js';
import { session, logout, listShops, createShop, setActiveShop, activeShop, listUsers, createUser, setActive, organization, listWorkspaces, createWorkspace, setActiveWorkspace, activeWorkspace } from './userAuth.js';

const app=document.querySelector('#app');
const routes={
 home:['Главная','Центр управления B-JOB'],reports:['Отчёты','Отчёты и выгрузки'],products:['Товары','Номенклатура и карточки'],shops:['Магазины','Магазины и подключения'],cabinet:['Личный кабинет','Профиль и текущий доступ'],analytics:['Аналитика','Показатели и динамика'],fbo:['Склад FBO','Управление складом FBO'],fbs:['Склад FBS','Управление складом FBS'],transfers:['Перемещения FBO → FBS','Пополнение FBS со склада FBO'],shipments:['Поставки','Поставки на склады'],fbsShipments:['Поставки FBS','Поставки FBS'],production:['Производство','Планирование производства'],salesHistory:['История продаж','История продаж'],api:['Интеграция по API','API-интеграции'],lan:['Интеграция по LAN','Локальная сеть'],sync:['Синхронизация','Обмен и журнал синхронизации'],personal:['Персональный доступ','Права и доступ'],prices:['Цены и скидки','Цены и скидки'],tables:['Таблицы','Рабочие таблицы'],workspaces:['Рабочие пространства','Рабочие пространства и кабинеты'],history:['История изменений','Журнал изменений'],settings:['Настройки','Настройки приложения'],organization:['Организация','Организация'],users:['Пользователи','Пользователи'],employees:['Сотрудники','Сотрудники'],backups:['Резервные копии','Резервные копии и восстановление'],fbsStats:['Статистика FBS','Статистика заказов FBS']
};
const groups=[['Главная',['home']],['Отчёты',['reports','analytics','salesHistory']],['Товары',['products','prices','tables']],['Магазины',['shops','cabinet']],['Склады',['fbo','fbs','transfers']],['Поставки',['shipments','fbsShipments']],['Производство',['production']],['Интеграции',['api','lan','sync']],['Управление',['workspaces','organization','users','employees','personal','settings','history','backups']],['FBS аналитика',['fbsStats']]];
const state={route:localStorage.getItem('bjob:route')||'home'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${crypto.randomUUID()}`;
const today=()=>new Date().toISOString();
async function count(name){try{return (await DB.all(name)).length}catch{return 0}}
function navigate(route){if(!routes[route])return;state.route=route;localStorage.setItem('bjob:route',route);renderShell().then(renderRoute).catch(fatal)}
function toast(text,error=false){const t=document.querySelector('#single-toast');if(!t)return;t.textContent=text;t.className=`single-toast ${error?'error':'ok'}`;clearTimeout(window.__bjobToast);window.__bjobToast=setTimeout(()=>t.remove(),2500)}
function page(title,description,body=''){return `<section class="single-page"><header class="single-head"><span>B-JOB</span><h1>${esc(title)}</h1><p>${esc(description)}</p></header>${body}</section>`}
function cards(items){return `<div class="single-cards">${items.map(([a,b])=>`<div><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div>`}
function topNav(){return groups.map(([label,ids])=>ids.length===1?`<button class="top-link ${state.route===ids[0]?'active':''}" data-route="${ids[0]}">${esc(label)}</button>`:`<div class="top-menu"><button class="top-link ${ids.includes(state.route)?'active':''}" data-menu>${esc(label)} <span>⌄</span></button><div class="top-dropdown">${ids.map(id=>`<button data-route="${id}">${esc(routes[id][0])}</button>`).join('')}</div></div>`).join('')}
async function renderShell(){const user=session();const shop=await activeShop();const shops=await listShops();const workspace=await activeWorkspace();const workspaces=await listWorkspaces();app.innerHTML=`<div class="bjob-single"><header class="single-top"><div class="single-brand"><b>B-JOB</b><span>операционная система бизнеса</span></div><nav class="single-nav">${topNav()}</nav><div class="single-context"><select id="active-workspace" title="Рабочее пространство">${workspaces.map(w=>`<option value="${esc(w.id)}" ${w.id===workspace?.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select><select id="active-shop" title="Магазин"><option value="">Магазин не выбран</option>${shops.map(s=>`<option value="${esc(s.id)}" ${s.id===shop?.id?'selected':''}>${esc(s.name)} · ${esc(String(s.marketplace||'').toUpperCase())}</option>`).join('')}</select><span class="single-user-name">${esc(user?.name||'Пользователь')}</span><button class="top-user" data-action="logout">Выйти</button></div></header><main id="single-view"></main><div id="single-toast"></div></div>`;document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.top-menu.open').forEach(x=>x.classList.remove('open'));b.parentElement.classList.toggle('open')}));document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.top-menu.open').forEach(x=>x.classList.remove('open'));navigate(b.dataset.route)}));document.querySelector('#active-shop').addEventListener('change',async e=>{try{if(e.target.value)await setActiveShop(e.target.value);else localStorage.removeItem('bjob:v2:active-shop');await renderShell();await renderRoute()}catch(err){toast(err.message,true)}});document.querySelector('#active-workspace').addEventListener('change',async e=>{try{await setActiveWorkspace(e.target.value);await renderShell();await renderRoute()}catch(err){toast(err.message,true)}});document.querySelector('[data-action="logout"]').addEventListener('click',()=>{logout();location.reload()});}
async function renderRoute(){const view=document.querySelector('#single-view');if(!view)return;const [title,desc]=routes[state.route];let html;if(state.route==='home')html=await dashboardPage();else if(state.route==='shops')html=await shopsPage();else if(state.route==='workspaces')html=await workspacesPage();else if(state.route==='users'||state.route==='employees')html=await usersPage(state.route==='employees');else if(state.route==='organization')html=await organizationPage();else if(['fbo','fbs'].includes(state.route))html=await warehousePage(state.route.toUpperCase());else if(state.route==='transfers')html=await transfersPage();else if(state.route==='backups')html=page(title,desc,`<div class="single-actions"><button data-action="backup-export">Экспорт резервной копии</button><button data-action="backup-import">Импорт резервной копии</button></div>`);else if(state.route==='cabinet')html=page(title,desc,cards([['Пользователь',session()?.name||'—'],['Роль',session()?.role||'—'],['Рабочее пространство',(await activeWorkspace())?.name||'—'],['Магазин',(await activeShop())?.name||'Не выбран']]));else if(state.route==='analytics')html=page(title,desc,cards([['Продажи',await count('sales')],['Реклама',await count('ads')],['Товары',await count('products')],['Остатки',await count('stocks')]]));else if(['products','salesHistory','fbsStats','shipments','fbsShipments','production'].includes(state.route))html=page(title,desc,await tablePage(state.route==='products'?'products':state.route==='salesHistory'?'sales':state.route==='production'?'productionOrders':state.route==='fbsStats'?'fbs':state.route==='fbsShipments'?'shipments':'shipments'));else if(state.route==='tables')html=page(title,desc,`<div class="single-actions"><button data-action="export-json">Экспорт JSON</button></div>`);else if(['api','lan','sync'].includes(state.route))html=page(title,desc,cards([['Режим','Локальный / автономный'],['Состояние','Готово']])+`<div class="single-actions"><button data-action="info">Проверить состояние</button></div>`);else if(state.route==='prices')html=page(title,desc,await tablePage('products'));else if(['personal','settings','history'].includes(state.route))html=page(title,desc,cards([['Состояние','Раздел доступен'],['Пользователь',session()?.name||'—']]));else html=page(title,desc,cards([['Статус','Раздел доступен'],['Назначение',desc]]));view.innerHTML=html;bindView()}
async function dashboardPage(){const [products,sales,stocks,shipments,fbs,warehouses,boxes,moves]=await Promise.all(['products','sales','stocks','shipments','fbs','warehouses','boxes','warehouseMoves'].map(count));return page('Главная','Единый центр управления бизнесом',cards([['Товары',products],['Продажи',sales],['Остатки',stocks],['Поставки',shipments],['FBS',fbs],['Склады',warehouses],['Короба',boxes],['Перемещения',moves]])+`<div class="single-actions"><button data-route="fbo">Склад FBO</button><button data-route="fbs">Склад FBS</button><button data-route="transfers">FBO → FBS</button><button data-route="products">Товары</button></div>`+`<div class="dashboard-grid"><div class="dashboard-panel"><h3>Контроль</h3><p>Активное рабочее пространство: ${esc((await activeWorkspace())?.name||'—')}</p><p>Активный магазин: ${esc((await activeShop())?.name||'не выбран')}</p></div><div class="dashboard-panel"><h3>Складская система</h3><p>Склады, ячейки, короба и движения хранятся локально и разделены по магазину.</p></div></div>`) }
async function shopsPage(){const shops=await listShops();return page('Магазины','Магазины организации',`<div class="single-actions"><button data-action="add-shop">Добавить магазин</button></div><div class="single-list">${shops.length?shops.map(s=>`<article><div><b>${esc(s.name)}</b><span>${esc(String(s.marketplace||'').toUpperCase())}</span></div><button data-action="choose-shop" data-id="${esc(s.id)}">Сделать активным</button></article>`).join(''):'<div class="empty-state">Магазинов пока нет.</div>'}</div>`) }
async function workspacesPage(){const rows=await listWorkspaces();return page('Рабочие пространства','Переключение и создание локальных рабочих пространств',`<div class="single-actions"><button data-action="add-workspace">Создать пространство</button></div><div class="single-list">${rows.map(w=>`<article><div><b>${esc(w.name)}</b><span>${esc(w.description||'Без описания')}</span></div><button data-action="choose-workspace" data-id="${esc(w.id)}">Сделать активным</button></article>`).join('')}</div>`) }
async function usersPage(employees){const users=await listUsers();return page(employees?'Сотрудники':'Пользователи',employees?'Сотрудники и доступы':'Пользователи организации',`<div class="single-actions"><button data-action="add-user">Добавить сотрудника</button></div><div class="single-list">${users.map(u=>`<article><div><b>${esc(u.name)}</b><span>${esc(u.login)} · ${esc(u.role)}</span></div><button data-action="toggle-user" data-id="${esc(u.id)}">${u.active===false?'Включить':'Отключить'}</button></article>`).join('')}</div>`) }
async function organizationPage(){const org=await organization();return page('Организация','Единая организация и её параметры',cards([['Название',org?.name||'B-JOB'],['Организация','default'],['Режим','Локальный']])+`<div class="single-actions"><button data-action="organization-name">Изменить название</button></div>`) }
async function tablePage(store){const rows=await DB.all(store);const keys=Object.keys(rows[0]||{}).filter(k=>k!=='passwordHash');const cols=keys.slice(0,8);return `<div class="single-table"><table><thead><tr>${cols.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,300).map(r=>`<tr>${cols.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${Math.max(cols.length,1)}">Нет данных</td></tr>`}</tbody></table></div>`}
async function warehousePage(type){const rows=(await DB.all('warehouses')).filter(w=>String(w.type||'').toUpperCase()===type);const boxes=await DB.all('boxes');const moves=await DB.all('warehouseMoves');return page(`Склад ${type}`,type==='FBO'?'Полный контроль склада FBO':'Полный контроль склада FBS',`<div class="single-actions"><button data-action="add-warehouse" data-type="${type}">Создать склад</button><button data-action="add-box" data-type="${type}">Создать короб</button><button data-action="print-box-label" data-type="${type}">Подготовить QR-метку</button></div><div class="warehouse-layout">${rows.map(w=>`<article class="warehouse-card"><div><h3>${esc(w.name)}</h3><p>${esc(w.description||'')} · ${w.rows||1}×${w.cols||1} ячеек</p></div><div class="warehouse-grid" style="--cols:${Math.min(Number(w.cols)||1,12)}">${Array.from({length:Math.min((Number(w.rows)||1)*(Number(w.cols)||1),144)},(_,i)=>`<span title="${esc(w.name)} / ${i+1}">${String(i+1).padStart(2,'0')}</span>`).join('')}</div><div class="warehouse-meta"><b>Короба: ${boxes.filter(b=>b.warehouseId===w.id).length}</b><span>Движения: ${moves.filter(m=>m.warehouseId===w.id).length}</span></div></article>`).join('')||'<div class="empty-state">Складов пока нет. Создайте первый склад.</div>'}</div><h3 class="section-title">Таблица складов</h3>${warehouseTable(rows)}`)}
function warehouseTable(rows){return `<div class="single-table"><table><thead><tr><th>Склад</th><th>Тип</th><th>Ячеек</th><th>Зон</th><th>Статус</th></tr></thead><tbody>${rows.map(w=>`<tr><td>${esc(w.name)}</td><td>${esc(w.type)}</td><td>${Number(w.rows||1)*Number(w.cols||1)}</td><td>${Number(w.zones||1)}</td><td>Активен</td></tr>`).join('')||'<tr><td colspan="5">Нет данных</td></tr>'}</tbody></table></div>`}
async function transfersPage(){const rows=await DB.all('warehouseMoves');const transfers=rows.filter(x=>x.kind==='FBO_TO_FBS');return page('Перемещения FBO → FBS','Пополнение складов FBS со склада FBO',`<div class="single-actions"><button data-action="add-transfer">Создать перемещение</button></div><div class="single-table"><table><thead><tr><th>ID</th><th>FBO</th><th>FBS</th><th>Количество</th><th>Статус</th><th>Дата</th></tr></thead><tbody>${transfers.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.fromWarehouse||'—')}</td><td>${esc(t.toWarehouse||'—')}</td><td>${esc(t.quantity)}</td><td>${esc(t.status)}</td><td>${esc(t.date)}</td></tr>`).join('')||'<tr><td colspan="6">Перемещений пока нет.</td></tr>'}</tbody></table></div>`) }
function bindView(){document.querySelectorAll('#single-view [data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));document.querySelectorAll('#single-view [data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action,b.dataset.id,b.dataset.type)))}
async function action(type,id,kind){try{
 if(type==='add-shop'){const name=prompt('Название магазина','Новый магазин');if(!name)return;const marketplace=(prompt('Маркетплейс: WB или Ozon','WB')||'WB').trim().toLowerCase();const shop=await createShop({name,marketplace});toast(`Магазин «${shop.name}» создан`);await renderShell();await renderRoute();return}
 if(type==='choose-shop'){await setActiveShop(id);toast('Магазин выбран');await renderShell();await renderRoute();return}
 if(type==='add-workspace'){const name=prompt('Название рабочего пространства','Новое пространство');if(!name)return;const description=prompt('Описание','')||'';await createWorkspace({name,description});toast('Рабочее пространство создано');await renderShell();await renderRoute();return}
 if(type==='choose-workspace'){await setActiveWorkspace(id);toast('Рабочее пространство выбрано');await renderShell();await renderRoute();return}
 if(type==='toggle-user'){const users=await listUsers();const u=users.find(x=>x.id===id);if(u)await setActive(id,u.active===false);toast('Статус сотрудника изменён');await renderRoute();return}
 if(type==='add-user'){const login=prompt('Логин сотрудника');const name=prompt('Имя сотрудника');if(!login||!name)return;const role=prompt('Роль','warehouse')||'warehouse';const r=await createUser({login,name,role});alert(`Сотрудник создан. Временный пароль: ${r.temporaryPassword}`);await renderRoute();return}
 if(type==='organization-name'){const name=prompt('Название организации');if(!name)return;const org=await organization();await DB.put('settings',{...org,name});toast('Название сохранено');await renderRoute();return}
 if(type==='add-warehouse'){const name=prompt(`Название склада ${kind}`);if(!name)return;const rows=Math.max(1,Number(prompt('Количество рядов','4'))||4);const cols=Math.max(1,Number(prompt('Количество колонок','6'))||6);const zones=Math.max(1,Number(prompt('Количество зон','1'))||1);await DB.put('warehouses',{id:uid('warehouse'),name:name.trim(),type:kind,rows,cols,zones,description:`Склад ${kind}`,createdAt:today()});toast('Склад создан');await renderRoute();return}
 if(type==='add-box'){const warehouses=(await DB.all('warehouses')).filter(w=>w.type===kind);if(!warehouses.length){toast('Сначала создайте склад',true);return}const warehouseId=prompt(`ID склада (${warehouses.map(w=>w.id).join(', ')})`,warehouses[0].id);const warehouse=warehouses.find(w=>w.id===warehouseId)||warehouses[0];const code=prompt('Код короба',`BOX-${Date.now().toString().slice(-6)}`);if(!code)return;const payload=`BJOB|BOX|${code}|${warehouse.id}`;await DB.put('boxes',{id:uid('box'),warehouseId:warehouse.id,shopId:localStorage.getItem('bjob:v2:active-shop')||null,code:code.trim(),qrPayload:payload,contents:[],createdAt:today()});toast('Короб создан. QR-пayload сохранён');await renderRoute();return}
 if(type==='print-box-label'){const boxes=await DB.all('boxes');if(!boxes.length){toast('Сначала создайте короб',true);return}const box=boxes[boxes.length-1];const w=window.open('','_blank','width=500,height=500');if(!w){toast('Разрешите открытие окна печати',true);return}w.document.write(`<html><body style="font-family:Arial;padding:30px"><h1>B-JOB</h1><h2>${esc(box.code)}</h2><p>QR payload: ${esc(box.qrPayload)}</p><p>Идентификатор можно использовать для печати/кодирования QR на локальном терминале.</p><button onclick="print()">Печать</button></body></html>`);w.document.close();return}
 if(type==='add-transfer'){const warehouses=await DB.all('warehouses');const fbo=warehouses.find(w=>w.type==='FBO'),fbs=warehouses.find(w=>w.type==='FBS');if(!fbo||!fbs){toast('Создайте хотя бы один FBO и один FBS склад',true);return}const quantity=Math.max(1,Number(prompt('Количество единиц','1'))||1);const sku=prompt('Артикул / SKU','');if(!sku)return;await DB.put('warehouseMoves',{id:uid('move'),kind:'FBO_TO_FBS',fromWarehouse:fbo.name,toWarehouse:fbs.name,fromWarehouseId:fbo.id,toWarehouseId:fbs.id,sku,quantity,status:'draft',date:today(),shopId:localStorage.getItem('bjob:v2:active-shop')||null});toast('Перемещение создано');await renderRoute();return}
 if(type==='backup-export'||type==='export-json')return exportAll();if(type==='info'){toast('Локальное ядро работает');return}if(type==='logout'){logout();location.reload()}
 }catch(e){console.error('B-JOB action failed',e);toast(e?.message||'Операция не выполнена',true)}}
async function exportAll(){const data=await DB.snapshot();const payload=JSON.stringify({format:'bjob-json',version:4,createdAt:today(),data},null,2);if(window.bjobDesktop?.exportJson)return window.bjobDesktop.exportJson(data);const blob=new Blob([payload],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`BJOB-backup-${today().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export async function start(){if(!session())return;await renderShell();await renderRoute();window.BJobNavigate=navigate;window.BJobLogout=()=>{logout();location.reload()}}
function fatal(e){console.error('B-JOB render failed',e);const view=document.querySelector('#single-view');if(view)view.innerHTML=page('Ошибка раздела','Не удалось отобразить экран',`<div class="single-fatal-inline">${esc(e?.message||e)}</div>`)}
