import * as DB from '../db.js';
import { session, logout, listShops, createShop, setActiveShop, activeShop, listUsers, createUser, setActive, changePassword, setUserAccess, organization } from './userAuth.js';

const app = document.querySelector('#app');
const routes = {
  home:['Главная','Обзор бизнеса'], reports:['Отчёты','Отчёты и выгрузки'], products:['Товары','Номенклатура и карточки'], shops:['Магазины','Магазины и активное подключение'], cabinet:['Личный кабинет','Профиль пользователя'], analytics:['Аналитика','Показатели и динамика'], fbo:['Склад FBO','Остатки и операции FBO'], fbs:['Склад FBS','Операции склада FBS'], shipments:['Поставки','Поставки на склады'], fbsShipments:['Поставки FBS','Поставки FBS'], production:['Производство','Планирование производства'], salesHistory:['История продаж','История продаж'], api:['Интеграция по API','API-интеграции'], lan:['Интеграция по LAN','Локальная сеть'], sync:['Синхронизация','Обмен и журнал синхронизации'], personal:['Персональный доступ','Права и доступ'], prices:['Цены и скидки','Цены и скидки'], tables:['Таблицы','Рабочие таблицы'], workspaces:['Рабочие пространства и личные кабинеты','Организации и рабочие пространства'], history:['История изменений','Журнал изменений'], settings:['Настройки','Настройки приложения'], organization:['Организация','Организация'], users:['Пользователи','Пользователи'], employees:['Сотрудники','Сотрудники'], backups:['Резервные копии','Резервные копии и восстановление'], fbsStats:['Статистика FBS','Статистика заказов FBS']
};
const groups = [
  ['Главная',['home']],['Отчёты',['reports','salesHistory','analytics']],['Товары',['products','prices','tables']],['Магазины',['shops','cabinet']],['Склады',['fbo','fbs']],['Поставки',['shipments','fbsShipments']],['Производство',['production']],['Интеграции',['api','lan','sync']],['Управление',['personal','organization','users','employees','workspaces','settings','history','backups']],['FBS аналитика',['fbsStats']]
];
const state={route:localStorage.getItem('bjob:route')||'home'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₽';
const num=v=>Number(v||0).toLocaleString('ru-RU');
async function count(store){try{return (await DB.all(store)).length}catch{return 0}}
async function renderShell(){
  const user=session(); const shop=await activeShop(); const shops=await listShops();
  app.innerHTML=`<div class="bjob-single"><header class="single-top"><div class="single-brand"><b>B-JOB</b><span>операционная система бизнеса</span></div><div class="single-shop"><label>Магазин</label><select id="active-shop"><option value="">Не выбран</option>${shops.map(s=>`<option value="${esc(s.id)}" ${s.id===shop?.id?'selected':''}>${esc(s.name)} · ${esc(String(s.marketplace||'').toUpperCase())}</option>`).join('')}</select></div><div class="single-user"><span>${esc(user?.name||'Пользователь')}</span><button data-action="logout">Выйти</button></div></header><div class="single-body"><aside class="single-nav">${groups.map(([g,ids])=>`<section><h3>${esc(g)}</h3>${ids.map(id=>`<button data-route="${id}" class="${state.route===id?'active':''}">${esc(routes[id][0])}</button>`).join('')}</section>`).join('')}</aside><main id="single-view"></main></div><div id="single-toast"></div></div>`;
  document.querySelector('#active-shop').addEventListener('change',async e=>{if(!e.target.value)return;try{await setActiveShop(e.target.value);toast('Магазин переключён');await renderShell();await renderRoute()}catch(err){toast(err.message,true)}});
  document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));
  document.querySelector('[data-action="logout"]').addEventListener('click',()=>{logout();location.reload()});
}
function navigate(route){if(!routes[route])return;state.route=route;localStorage.setItem('bjob:route',route);renderShell().then(renderRoute)}
function toast(text,error=false){const t=document.querySelector('#single-toast');if(!t)return;t.textContent=text;t.className=error?'error':'ok';setTimeout(()=>t.remove(),2500)}
function page(title,description,body=''){return `<div class="single-page"><div class="single-head"><div><span>B-JOB</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div></div>${body}</div>`}
function cards(items){return `<div class="single-cards">${items.map(([a,b])=>`<div><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div>`}
async function renderRoute(){const view=document.querySelector('#single-view');if(!view)return;const [title,desc]=routes[state.route];let html='';
  if(state.route==='home'){html=page(title,desc,cards([['Товары',await count('products')],['Продажи',await count('sales')],['Остатки',await count('stocks')],['Поставки',await count('shipments')],['FBS',await count('fbs')]])+`<div class="single-actions"><button data-route="products">Товары</button><button data-route="analytics">Аналитика</button><button data-route="reports">Отчёты</button></div>`)}
  else if(state.route==='shops')html=await shopsPage();
  else if(state.route==='users'||state.route==='employees')html=await usersPage(state.route==='employees');
  else if(state.route==='organization')html=await organizationPage();
  else if(state.route==='backups')html=backupPage();
  else if(state.route==='reports')html=page(title,desc,reportPage());
  else if(state.route==='products')html=page(title,desc,tablePage('products',['Артикул','Название','Цена','Количество']));
  else if(state.route==='analytics')html=page(title,desc,cards([['Продажи',await count('sales')],['Реклама',await count('ads')],['Товары',await count('products')],['Остатки',await count('stocks')]]));
  else if(state.route==='salesHistory')html=page(title,desc,tablePage('sales',['Дата','Артикул','Заказы','Сумма']));
  else if(state.route==='fbs')html=page(title,desc,tablePage('fbs',['Артикул','Баркод','Статус','Склад']));
  else if(state.route==='fbo')html=page(title,desc,tablePage('stocks',['Артикул','Склад','Доступно','Дата']));
  else if(state.route==='shipments'||state.route==='fbsShipments')html=page(title,desc,tablePage('shipments',['Номер','Склад','Статус','Дата']));
  else if(state.route==='production')html=page(title,desc,tablePage('productionOrders',['Артикул','Количество','Статус','Дата']));
  else if(state.route==='prices')html=page(title,desc,tablePage('products',['Артикул','Цена','Себестоимость','Комиссия']));
  else if(state.route==='reports')html=page(title,desc,reportPage());
  else if(state.route==='tables')html=page(title,desc,`<div class="single-actions"><button data-action="export-json">Экспорт JSON</button><button data-action="import-json">Импорт JSON</button></div>`);
  else if(state.route==='api'||state.route==='lan'||state.route==='sync')html=page(title,desc,cards([['Режим','Локальный / автономный'],['Статус','Готов к настройке']])+`<div class="single-actions"><button data-action="info">Проверить состояние</button></div>`);
  else if(state.route==='cabinet')html=page(title,desc,cards([['Пользователь',session()?.name||'—'],['Роль',session()?.role||'—'],['Магазин',(await activeShop())?.name||'Не выбран']]));
  else if(state.route==='personal'||state.route==='settings'||state.route==='workspaces'||state.route==='history')html=page(title,desc,cards([['Состояние','Работает локально'],['Пользователь',session()?.name||'—']]));
  else if(state.route==='fbsStats')html=page(title,desc,tablePage('fbs',['Артикул','Статус','Количество','Склад']));
  else html=page(title,desc,cards([['Статус','Раздел доступен'],['Назначение',desc]]));
  view.innerHTML=html;bindView();
}
async function shopsPage(){const shops=await listShops();return page('Магазины','Магазины организации',`<div class="single-actions"><button data-action="add-shop">Добавить магазин</button></div><div class="single-list">${shops.length?shops.map(s=>`<article><b>${esc(s.name)}</b><span>${esc(String(s.marketplace||'').toUpperCase())}</span><button data-action="choose-shop" data-id="${esc(s.id)}">Сделать активным</button></article>`).join(''):'<p>Магазинов пока нет.</p>'}</div>`)}
async function usersPage(employees){const users=await listUsers();return page(employees?'Сотрудники':'Пользователи',employees?'Сотрудники и доступы':'Пользователи организации',`<div class="single-actions"><button data-action="add-user">Добавить сотрудника</button></div><div class="single-list">${users.map(u=>`<article><b>${esc(u.name)}</b><span>${esc(u.login)} · ${esc(u.role)}</span><span>${u.active===false?'Отключён':'Активен'}</span><button data-action="toggle-user" data-id="${esc(u.id)}">${u.active===false?'Включить':'Отключить'}</button></article>`).join('')}</div>`)}
async function organizationPage(){const org=await organization();return page('Организация','Единая организация и её параметры',cards([['Название',org?.name||'B-JOB'],['ID','default'],['Режим','Локальный']])+`<div class="single-actions"><button data-action="organization-name">Изменить название</button></div>`)}
function backupPage(){return page('Резервные копии','Создание и восстановление локальной базы',`<div class="single-actions"><button data-action="backup-export">Экспорт резервной копии</button><button data-action="backup-import">Импорт резервной копии</button></div>`)}
function reportPage(){return `<div class="single-actions"><button data-action="export-json">Экспорт JSON</button><button data-action="backup-export">Резервная копия</button></div>`}
async function tablePage(store,headers){const rows=await DB.all(store);const keys=Object.keys(rows[0]||{});return `<div class="single-table"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,200).map(r=>`<tr>${keys.slice(0,headers.length).map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">Нет данных</td></tr>`}</tbody></table></div>`}
async function exportAll(){const data={};for(const n of ['users','shops','settings','products','sales','stocks','ads','warehouses','shipments','fbs','productionOrders','expenses','apiConnections','invitations','authEvents']){try{data[n]=await DB.all(n)}catch{data[n]=[]}}const payload=JSON.stringify({format:'bjob-json',version:2,createdAt:new Date().toISOString(),data},null,2);if(window.bjobDesktop?.exportJson)return window.bjobDesktop.exportJson(data);const blob=new Blob([payload],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`BJOB-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function bindView(){document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action,b.dataset.id)))}
async function action(type,id){try{if(type==='add-shop'){const name=prompt('Название магазина');if(!name)return;const marketplace=(prompt('Маркетплейс: WB или Ozon','WB')||'').toLowerCase();await createShop({name,marketplace});toast('Магазин создан');return renderShell().then(renderRoute)}if(type==='choose-shop'){await setActiveShop(id);toast('Магазин выбран');return renderShell().then(renderRoute)}if(type==='toggle-user'){const users=await listUsers(),u=users.find(x=>x.id===id);if(u)await setActive(id,u.active===false);toast('Статус сотрудника изменён');return renderRoute()}if(type==='add-user'){const login=prompt('Логин');const name=prompt('Имя');if(!login||!name)return;const role=prompt('Роль','warehouse')||'warehouse';const r=await createUser({login,name,role});alert(`Сотрудник создан. Временный пароль: ${r.temporaryPassword}`);return renderRoute()}if(type==='organization-name'){const name=prompt('Название организации');if(!name)return;const org=await organization();await DB.put('settings',{...org,name});toast('Название сохранено');return renderRoute()}if(type==='backup-export'||type==='export-json')return exportAll();if(type==='backup-import'||type==='import-json'){if(window.bjobDesktop?.importJson){const r=await window.bjobDesktop.importJson();if(r?.data){for(const [store,rows] of Object.entries(r.data))if(Array.isArray(rows))for(const row of rows)await DB.put(store,row);toast('Резервная копия восстановлена');return renderRoute()}}throw new Error('Импорт резервной копии доступен в desktop-режиме.')}if(type==='info'){toast('Локальное ядро работает')} }catch(e){console.error('B-JOB action failed',e);toast(e.message||'Операция не выполнена',true)}}
export async function start(){if(!session())return;await renderShell();await renderRoute();window.BJobNavigate=navigate;window.BJobLogout=()=>{logout();location.reload()};}
