import * as DB from '../db.js';
import { session, logout, listShops, createShop, setActiveShop, activeShop, listUsers, createUser, setActive, organization, listWorkspaces, createWorkspace, setActiveWorkspace, activeWorkspace, setUserAccess } from './userAuth.js';

const app=document.querySelector('#app');
const routes={home:['Главная','Центр управления B-JOB'],reports:['Отчёты','Отчёты и выгрузки'],products:['Товары','Номенклатура и карточки'],shops:['Магазины','Магазины и подключения'],cabinet:['Личный кабинет','Профиль и текущий доступ'],analytics:['Аналитика','Показатели и динамика'],fbo:['Склад FBO','Управление складом FBO'],fbs:['Склад FBS','Управление складом FBS'],transfers:['Перемещения FBO → FBS','Пополнение FBS со склада FBO'],shipments:['Поставки','Поставки на склады'],fbsShipments:['Поставки FBS','Поставки FBS'],production:['Производство','Планирование производства'],salesHistory:['История продаж','История продаж'],api:['Интеграция по API','Подключения и настройки API'],lan:['Интеграция по LAN','Локальная сеть и обмен'],sync:['Синхронизация','Состояние и журнал синхронизации'],personal:['Персональный доступ','Права и доступ'],prices:['Цены и скидки','Цены и скидки'],tables:['Таблицы','Импорт и экспорт данных'],workspaces:['Рабочие пространства','Рабочие пространства и кабинеты'],history:['История изменений','Журнал изменений'],settings:['Настройки','Настройки приложения'],organization:['Организация','Организация'],users:['Пользователи','Пользователи'],employees:['Сотрудники','Сотрудники'],backups:['Резервные копии','Резервные копии и восстановление'],fbsStats:['Статистика FBS','Статистика заказов FBS']};
const groups=[['Главная',['home']],['Отчёты',['reports','analytics','salesHistory']],['Товары',['products','prices','tables']],['Магазины',['shops','cabinet']],['Склады',['fbo','fbs','transfers']],['Поставки',['shipments','fbsShipments']],['Производство',['production']],['Интеграции',['api','lan','sync']],['Управление',['workspaces','organization','users','employees','personal','settings','history','backups']],['FBS аналитика',['fbsStats']]];
const state={route:localStorage.getItem('bjob:route')||'home'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${crypto.randomUUID()}`;
const today=()=>new Date().toISOString();
async function count(name){try{return(await DB.all(name)).length}catch{return 0}}
async function audit(type,details={}){try{await DB.put('audit',{id:uid('audit'),type,userId:session()?.id||null,login:session()?.login||null,date:today(),details})}catch(error){console.warn('B-JOB audit',error)}}
function toast(text,error=false){const t=document.querySelector('#single-toast');if(!t)return;t.textContent=text;t.className=`single-toast ${error?'error':'ok'}`;clearTimeout(window.__bjobToast);window.__bjobToast=setTimeout(()=>t.remove(),2500)}
function navigate(route){if(!routes[route])return;state.route=route;localStorage.setItem('bjob:route',route);renderShell().then(renderRoute).catch(fatal)}
function page(title,description,body=''){return `<section class="single-page"><header class="single-head"><span>B-JOB</span><h1>${esc(title)}</h1><p>${esc(description)}</p></header>${body}</section>`}
function cards(items){return `<div class="single-cards">${items.map(([a,b])=>`<div><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div>`}
function actions(items){return `<div class="single-actions">${items.join('')}</div>`}
function button(label,action,id='',type=''){return `<button data-action="${action}"${id?` data-id="${esc(id)}"`:''}${type?` data-type="${esc(type)}"`:''}>${esc(label)}</button>`}
function topNav(){return groups.map(([label,ids])=>ids.length===1?`<button class="top-link ${state.route===ids[0]?'active':''}" data-route="${ids[0]}">${esc(label)}</button>`:`<div class="top-menu"><button class="top-link ${ids.includes(state.route)?'active':''}" data-menu>${esc(label)} <span>⌄</span></button><div class="top-dropdown">${ids.map(id=>`<button data-route="${id}">${esc(routes[id][0])}</button>`).join('')}</div></div>`).join('')}
async function renderShell(){const user=session();const shop=await activeShop();const shops=await listShops();const workspace=await activeWorkspace();const workspaces=await listWorkspaces();app.innerHTML=`<div class="bjob-single"><header class="single-top"><div class="single-brand"><b>B-JOB</b><span>операционная система бизнеса</span></div><nav class="single-nav">${topNav()}</nav><div class="single-context"><select id="active-workspace" title="Рабочее пространство">${workspaces.map(w=>`<option value="${esc(w.id)}" ${w.id===workspace?.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select><select id="active-shop" title="Магазин"><option value="">Магазин не выбран</option>${shops.map(s=>`<option value="${esc(s.id)}" ${s.id===shop?.id?'selected':''}>${esc(s.name)} · ${esc(String(s.marketplace||'').toUpperCase())}</option>`).join('')}</select><span class="single-user-name">${esc(user?.name||'Пользователь')}</span><button class="top-user" data-action="logout">Выйти</button></div></header><main id="single-view"></main><div id="single-toast"></div></div>`;document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.top-menu.open').forEach(x=>x.classList.remove('open'));b.parentElement.classList.toggle('open')}));document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.top-menu.open').forEach(x=>x.classList.remove('open'));navigate(b.dataset.route)}));document.querySelector('#active-shop').addEventListener('change',async e=>{try{if(e.target.value)await setActiveShop(e.target.value);else localStorage.removeItem('bjob:v2:active-shop');await renderShell();await renderRoute()}catch(err){toast(err.message,true)}});document.querySelector('#active-workspace').addEventListener('change',async e=>{try{await setActiveWorkspace(e.target.value);await audit('workspace.switch',{workspaceId:e.target.value});await renderShell();await renderRoute()}catch(err){toast(err.message,true)}});document.querySelector('[data-action="logout"]').addEventListener('click',()=>{logout();location.reload()})}
async function renderRoute(){const view=document.querySelector('#single-view');if(!view)return;const [title,desc]=routes[state.route];let html;if(state.route==='home')html=await dashboardPage();else if(state.route==='reports')html=await reportsPage();else if(state.route==='products')html=await productsPage();else if(state.route==='shops')html=await shopsPage();else if(state.route==='workspaces')html=await workspacesPage();else if(state.route==='users'||state.route==='employees')html=await usersPage(state.route==='employees');else if(state.route==='organization')html=await organizationPage();else if(['fbo','fbs'].includes(state.route))html=await warehousePage(state.route.toUpperCase());else if(state.route==='transfers')html=await transfersPage();else if(state.route==='analytics')html=await analyticsPage();else if(state.route==='salesHistory')html=await historyTablePage('sales','История продаж');else if(state.route==='fbsStats')html=await historyTablePage('fbs','Статистика FBS');else if(state.route==='shipments'||state.route==='fbsShipments')html=await shipmentsPage(state.route==='fbsShipments');else if(state.route==='production')html=await productionPage();else if(state.route==='prices')html=await pricesPage();else if(state.route==='tables')html=await tablesPage();else if(state.route==='api')html=await apiPage();else if(state.route==='lan')html=await lanPage();else if(state.route==='sync')html=await syncPage();else if(state.route==='personal')html=await personalPage();else if(state.route==='settings')html=await settingsPage();else if(state.route==='history')html=await auditPage();else if(state.route==='backups')html=await backupsPage();else if(state.route==='cabinet')html=await cabinetPage();else html=page(title,desc,cards([['Статус','Раздел доступен'],['Назначение',desc]]));view.innerHTML=html;bindView()}
async function dashboardPage(){const [products,sales,stocks,shipments,fbs,warehouses,boxes,moves,orders]=await Promise.all(['products','sales','stocks','shipments','fbs','warehouses','boxes','warehouseMoves','productionOrders'].map(count));return page('Главная','Единый операционный центр B-JOB',cards([['Товары',products],['Продажи',sales],['Остатки',stocks],['Поставки',shipments],['FBS',fbs],['Склады',warehouses],['Короба',boxes],['Перемещения',moves],['Производственные заказы',orders]])+actions([button('Склад FBO','route','fbo'),button('Склад FBS','route','fbs'),button('FBO → FBS','route','transfers'),button('Товары','route','products')])+`<div class="dashboard-grid"><div class="dashboard-panel"><h3>Контроль</h3><p>Пространство: ${esc((await activeWorkspace())?.name||'—')}</p><p>Магазин: ${esc((await activeShop())?.name||'не выбран')}</p></div><div class="dashboard-panel"><h3>Локальное ядро</h3><p>Данные хранятся локально и разделяются по активному магазину.</p></div></div>`)}
async function reportsPage(){const [sales,products,stocks,ads,expenses]=await Promise.all(['sales','products','stocks','ads','expenses'].map(count));return page('Отчёты','Сводные показатели и выгрузки',cards([['Продажи',sales],['Товары',products],['Остатки',stocks],['Реклама',ads],['Расходы',expenses]])+actions([button('Экспорт полной базы','backup-export'),button('Экспорт JSON','export-json'),button('Импорт XLSX','import-xlsx')]))}
async function analyticsPage(){const [sales,ads,expenses,stocks]=await Promise.all(['sales','ads','expenses','stocks'].map(count));return page('Аналитика','Показатели бизнеса',cards([['Продажи',sales],['Реклама',ads],['Расходы',expenses],['Остатки',stocks]])+`<div class="dashboard-grid"><div class="dashboard-panel"><h3>Контроль данных</h3><p>Аналитика строится из локальных таблиц текущего магазина.</p></div><div class="dashboard-panel"><h3>Следующий уровень</h3><p>После импорта данных здесь отображаются реальные показатели и динамика.</p></div></div>`)}
async function productsPage(){const rows=await DB.all('products');const cols=['article','name','sku','color','size','price','cost','quantity'];return page('Товары','Номенклатура и карточки',actions([button('Добавить товар','add-product'),button('Импорт XLSX','import-xlsx'),button('Экспорт JSON','export-json')])+tableFromRows(rows,cols))}
async function pricesPage(){const rows=await DB.all('products');return page('Цены и скидки','Управление ценами локальных карточек',actions([button('Изменить цену','set-price')])+tableFromRows(rows,['article','name','price','cost']))}
async function shopsPage(){const shops=await listShops();return page('Магазины','Магазины организации',actions([button('Добавить магазин','add-shop')])+`<div class="single-list">${shops.length?shops.map(s=>`<article><div><b>${esc(s.name)}</b><span>${esc(String(s.marketplace||'').toUpperCase())}</span></div>${button('Сделать активным','choose-shop',s.id)}</article>`).join(''):'<div class="empty-state">Магазинов пока нет.</div>'}</div>`)}
async function workspacesPage(){const rows=await listWorkspaces();return page('Рабочие пространства','Переключение и создание локальных рабочих пространств',actions([button('Создать пространство','add-workspace')])+`<div class="single-list">${rows.map(w=>`<article><div><b>${esc(w.name)}</b><span>${esc(w.description||'Без описания')}</span></div>${button('Сделать активным','choose-workspace',w.id)}</article>`).join('')}</div>`)}
async function usersPage(employees){const users=await listUsers();return page(employees?'Сотрудники':'Пользователи',employees?'Сотрудники и доступы':'Пользователи организации',actions([button('Добавить сотрудника','add-user')])+`<div class="single-list">${users.map(u=>`<article><div><b>${esc(u.name)}</b><span>${esc(u.login)} · ${esc(u.role)}</span></div>${button(u.active===false?'Включить':'Отключить','toggle-user',u.id)}</article>`).join('')}</div>`)}
async function organizationPage(){const org=await organization();return page('Организация','Единая организация и её параметры',cards([['Название',org?.name||'B-JOB'],['ID','default'],['Режим','Локальный']])+actions([button('Изменить название','organization-name')]))}
async function cabinetPage(){return page('Личный кабинет','Профиль и текущий доступ',cards([['Пользователь',session()?.name||'—'],['Логин',session()?.login||'—'],['Роль',session()?.role||'—'],['Пространство',(await activeWorkspace())?.name||'—'],['Магазин',(await activeShop())?.name||'Не выбран']]))}
async function personalPage(){const u=session();return page('Персональный доступ','Права текущего пользователя',cards([['Роль',u?.role||'—'],['Полный доступ',u?.permissions?.all?'Да':'Нет'],['Магазинов',u?.shopIds?.length||0]])+actions([button('Обновить доступ','info')]))}
async function settingsPage(){return page('Настройки','Настройки приложения',cards([['Режим','Local-first'],['Хранилище','IndexedDB'],['Автономность','Да'],['Версия БД',DB.DB_VERSION]] )+actions([button('Проверить ядро','info'),button('Экспорт базы','backup-export')]))}
async function auditPage(){const rows=(await DB.all('audit')).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return page('История изменений','Журнал операций B-JOB',tableFromRows(rows,['date','type','login','details']))}
async function backupsPage(){return page('Резервные копии','Экспорт и восстановление всей локальной базы',actions([button('Создать резервную копию','backup-export'),button('Восстановить резервную копию','backup-import'),button('Импорт XLSX','import-xlsx')])+`<div class="empty-state">Резервная копия включает локальные таблицы B-JOB. Перед восстановлением рекомендуется сделать текущий backup.</div>`)}
async function tablesPage(){return page('Таблицы','Импорт и экспорт данных',actions([button('Импорт XLSX','import-xlsx'),button('Экспорт JSON','export-json'),button('Импорт backup','backup-import')])+cards([['Источник','Локальные таблицы'],['Формат Excel','XLS/XLSX'],['Формат backup','JSON']]))}
async function apiPage(){const rows=await DB.all('apiConnections');return page('Интеграция по API','Подключения хранятся локально; реальные запросы выполняются только после настройки',actions([button('Добавить подключение','add-api')])+tableFromRows(rows,['marketplace','name','baseUrl','active','createdAt']))}
async function lanPage(){const info=window.bjobDesktop?await window.bjobDesktop.lanStatus():{enabled:false};return page('Интеграция по LAN','Локальная сеть без внешнего сервиса',cards([['Статус',info.enabled?'Запущен':'Остановлен'],['Адрес',info.address||'—'],['Порт',info.port||'—']])+actions([button(info.enabled?'Остановить LAN':'Запустить LAN','lan-toggle'),button('Обновить статус','info')]))}
async function syncPage(){const info=window.bjobDesktop?await window.bjobDesktop.syncStatus():{deviceId:'web',pending:0};return page('Синхронизация','Состояние локального журнала обмена',cards([['Устройство',info.deviceId||'—'],['Операций в журнале',info.pending||0],['Режим','Local-first']])+actions([button('Обновить','info'),button('Экспорт журнала','sync-export')]))}
async function productionPage(){return page('Производство','Планирование и контроль производства',actions([button('Создать производственный заказ','add-production')])+tableFromRows(await DB.all('productionOrders'),['id','article','quantity','status','date']))}
async function shipmentsPage(fbs){return page(fbs?'Поставки FBS':'Поставки',fbs?'Сборка и передача FBS':'Поставки на склады',actions([button('Создать поставку',fbs?'add-fbs-shipment':'add-shipment')])+tableFromRows(await DB.all('shipments'),['id','article','quantity','status','date','destination']))}
async function historyTablePage(store,title){return page(title,routes[state.route][1],tableFromRows(await DB.all(store),['date','article','sku','quantity','price','status']))}
function tableFromRows(rows,cols){return `<div class="single-table"><table><thead><tr>${cols.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,500).map(r=>`<tr>${cols.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k]??'')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">Нет данных</td></tr>`}</tbody></table></div>`}
async function warehousePage(type){const rows=(await DB.all('warehouses')).filter(w=>String(w.type||'').toUpperCase()===type);const boxes=await DB.all('boxes');const moves=await DB.all('warehouseMoves');return page(`Склад ${type}`,type==='FBO'?'Полный контроль склада FBO':'Полный контроль склада FBS',actions([button('Создать склад','add-warehouse','',type),button('Создать короб','add-box','',type),button('Подготовить QR-метку','print-box-label','',type)])+`<div class="warehouse-layout">${rows.map(w=>`<article class="warehouse-card"><div><h3>${esc(w.name)}</h3><p>${esc(w.description||'')} · ${w.rows||1}×${w.cols||1} ячеек</p></div><div class="warehouse-grid" style="--cols:${Math.min(Number(w.cols)||1,12)}">${Array.from({length:Math.min((Number(w.rows)||1)*(Number(w.cols)||1),144)},(_,i)=>`<span title="${esc(w.name)} / ${i+1}">${String(i+1).padStart(2,'0')}</span>`).join('')}</div><div class="warehouse-meta"><b>Короба: ${boxes.filter(b=>b.warehouseId===w.id).length}</b><span>Движения: ${moves.filter(m=>m.fromWarehouseId===w.id||m.toWarehouseId===w.id).length}</span></div></article>`).join('')||'<div class="empty-state">Складов пока нет. Создайте первый склад.</div>'}</div><h3 class="section-title">Таблица складов</h3>${tableFromRows(rows,['name','type','rows','cols','zones','createdAt'])}`)}
async function transfersPage(){const rows=(await DB.all('warehouseMoves')).filter(x=>x.kind==='FBO_TO_FBS');return page('Перемещения FBO → FBS','Пополнение складов FBS со склада FBO',actions([button('Создать перемещение','add-transfer')])+tableFromRows(rows,['id','fromWarehouse','toWarehouse','sku','quantity','status','date']))}
function bindView(){document.querySelectorAll('#single-view [data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));document.querySelectorAll('#single-view [data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action,b.dataset.id,b.dataset.type)))}
async function action(type,id,kind){try{
 if(type==='add-shop'){const name=prompt('Название магазина','Новый магазин');if(!name)return;const marketplace=(prompt('Маркетплейс: WB или Ozon','WB')||'WB').trim().toLowerCase();const shop=await createShop({name,marketplace});await audit('shop.create',{shopId:shop.id,name:shop.name,marketplace});toast(`Магазин «${shop.name}» создан`);await renderShell();await renderRoute();return}
 if(type==='choose-shop'){await setActiveShop(id);await audit('shop.switch',{shopId:id});toast('Магазин выбран');await renderShell();await renderRoute();return}
 if(type==='add-workspace'){const name=prompt('Название рабочего пространства','Новое пространство');if(!name)return;const description=prompt('Описание','')||'';const row=await createWorkspace({name,description});await audit('workspace.create',{workspaceId:row.id});toast('Рабочее пространство создано');await renderShell();await renderRoute();return}
 if(type==='choose-workspace'){await setActiveWorkspace(id);await audit('workspace.switch',{workspaceId:id});toast('Рабочее пространство выбрано');await renderShell();await renderRoute();return}
 if(type==='toggle-user'){const users=await listUsers();const u=users.find(x=>x.id===id);if(u){await setActive(id,u.active===false);await audit('user.status',{userId:id,active:u.active===false});}toast('Статус сотрудника изменён');await renderRoute();return}
 if(type==='add-user'){const login=prompt('Логин сотрудника');const name=prompt('Имя сотрудника');if(!login||!name)return;const role=prompt('Роль','warehouse')||'warehouse';const r=await createUser({login,name,role});await audit('user.create',{userId:r.userId,login:r.login,role});alert(`Сотрудник создан. Временный пароль: ${r.temporaryPassword}`);await renderRoute();return}
 if(type==='organization-name'){const name=prompt('Название организации');if(!name)return;const org=await organization();await DB.put('settings',{...org,name});await audit('organization.update',{name});toast('Название сохранено');await renderRoute();return}
 if(type==='add-product'){const article=prompt('Артикул','SKU-001');if(!article)return;const name=prompt('Название','Новый товар')||article;const price=Number(prompt('Цена','0'))||0;const cost=Number(prompt('Себестоимость','0'))||0;await DB.put('products',{id:uid('product'),article:article.trim(),name:name.trim(),sku:article.trim(),price,cost,quantity:0,createdAt:today()});await audit('product.create',{article});toast('Товар создан');await renderRoute();return}
 if(type==='set-price'){const rows=await DB.all('products');if(!rows.length){toast('Сначала создайте товар',true);return}const p=rows[0];const price=Number(prompt(`Новая цена для ${p.name}`,String(p.price||0)));if(!Number.isFinite(price)||price<0)return;await DB.put('products',{...p,price,updatedAt:today()});await audit('product.price',{productId:p.id,price});toast('Цена сохранена');await renderRoute();return}
 if(type==='add-warehouse'){const name=prompt(`Название склада ${kind}`);if(!name)return;const rows=Math.max(1,Number(prompt('Количество рядов','4'))||4);const cols=Math.max(1,Number(prompt('Количество колонок','6'))||6);const zones=Math.max(1,Number(prompt('Количество зон','1'))||1);const row={id:uid('warehouse'),name:name.trim(),type:kind,rows,cols,zones,description:`Склад ${kind}`,createdAt:today()};await DB.put('warehouses',row);await audit('warehouse.create',{warehouseId:row.id,type:kind});toast('Склад создан');await renderRoute();return}
 if(type==='add-box'){const warehouses=(await DB.all('warehouses')).filter(w=>w.type===kind);if(!warehouses.length){toast('Сначала создайте склад',true);return}const warehouse=warehouses[0];const code=prompt('Код короба',`BOX-${Date.now().toString().slice(-6)}`);if(!code)return;const row={id:uid('box'),warehouseId:warehouse.id,shopId:localStorage.getItem('bjob:v2:active-shop')||null,code:code.trim(),qrPayload:`BJOB|BOX|${code.trim()}|${warehouse.id}`,contents:[],createdAt:today()};await DB.put('boxes',row);await audit('box.create',{boxId:row.id,warehouseId:warehouse.id});toast('Короб создан. QR-payload сохранён');await renderRoute();return}
 if(type==='print-box-label'){const boxes=await DB.all('boxes');if(!boxes.length){toast('Сначала создайте короб',true);return}const box=boxes[boxes.length-1];const w=window.open('','_blank','width=500,height=500');if(!w){toast('Разрешите окно печати',true);return}w.document.write(`<html><body style="font-family:Arial;padding:30px"><h1>B-JOB</h1><h2>${esc(box.code)}</h2><p>${esc(box.qrPayload)}</p><button onclick="print()">Печать</button></body></html>`);w.document.close();return}
 if(type==='add-transfer'){const warehouses=await DB.all('warehouses');const fbo=warehouses.find(w=>w.type==='FBO'),fbs=warehouses.find(w=>w.type==='FBS');if(!fbo||!fbs){toast('Создайте FBO и FBS склад',true);return}const quantity=Math.max(1,Number(prompt('Количество единиц','1'))||1);const sku=prompt('Артикул / SKU','');if(!sku)return;const row={id:uid('move'),kind:'FBO_TO_FBS',fromWarehouse:fbo.name,toWarehouse:fbs.name,fromWarehouseId:fbo.id,toWarehouseId:fbs.id,sku,quantity,status:'draft',date:today(),shopId:localStorage.getItem('bjob:v2:active-shop')||null};await DB.put('warehouseMoves',row);await audit('warehouse.transfer',{moveId:row.id,from:fbo.id,to:fbs.id,sku,quantity});toast('Перемещение создано');await renderRoute();return}
 if(type==='add-shipment'||type==='add-fbs-shipment'){const article=prompt('Артикул / SKU');if(!article)return;const quantity=Math.max(1,Number(prompt('Количество','1'))||1);const row={id:uid('shipment'),article,quantity,status:'draft',date:today(),destination:type==='add-fbs-shipment'?'FBS':'FBO',shopId:localStorage.getItem('bjob:v2:active-shop')||null};await DB.put('shipments',row);await audit('shipment.create',{shipmentId:row.id,destination:row.destination});toast('Поставка создана');await renderRoute();return}
 if(type==='add-production'){const article=prompt('Артикул / SKU');if(!article)return;const quantity=Math.max(1,Number(prompt('Количество','1'))||1);const row={id:uid('production'),article,quantity,status:'planned',date:today(),createdAt:today(),shopId:localStorage.getItem('bjob:v2:active-shop')||null};await DB.put('productionOrders',row);await audit('production.create',{orderId:row.id,article,quantity});toast('Производственный заказ создан');await renderRoute();return}
 if(type==='add-api'){const name=prompt('Название подключения','WB API');if(!name)return;const marketplace=(prompt('Маркетплейс','WB')||'WB').toLowerCase();const baseUrl=prompt('Base URL API','https://')||'';const row={id:uid('api'),name,marketplace,baseUrl,active:false,createdAt:today()};await DB.put('apiConnections',row);await audit('api.connection.create',{id:row.id,marketplace});toast('Подключение сохранено');await renderRoute();return}
 if(type==='lan-toggle'){if(!window.bjobDesktop){toast('LAN доступен только в .exe',true);return}const info=await window.bjobDesktop.lanStatus();if(info.enabled)await window.bjobDesktop.lanStop();else await window.bjobDesktop.lanStart();toast('LAN статус обновлён');await renderRoute();return}
 if(type==='sync-export'){if(!window.bjobDesktop){toast('Экспорт журнала доступен в .exe',true);return}await window.bjobDesktop.exportSyncJournal();toast('Журнал экспортирован');return}
 if(type==='backup-export'||type==='export-json')return exportAll();
 if(type==='backup-import'){return importBackup()}
 if(type==='import-xlsx'){return importXlsx()}
 if(type==='info'){toast('Локальное ядро работает');return}
 if(type==='logout'){logout();location.reload()}
 }catch(e){console.error('B-JOB action failed',e);toast(e?.message||'Операция не выполнена',true)}}
async function exportAll(){const data=await DB.snapshot();if(window.bjobDesktop?.exportJson){const r=await window.bjobDesktop.exportJson(data);if(!r?.cancelled)await audit('backup.export',{filePath:r?.filePath||null});return}const payload=JSON.stringify({format:'bjob-json',version:5,createdAt:today(),data},null,2);const blob=new Blob([payload],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`BJOB-backup-${today().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(){try{if(!window.bjobDesktop?.importJson){toast('Восстановление backup доступно в .exe',true);return}const result=await window.bjobDesktop.importJson();if(result?.cancelled)return;const stores=new Set(DB.STORES);for(const [name,rows] of Object.entries(result.data||{})){if(stores.has(name)&&Array.isArray(rows))await DB.replaceMany(name,rows)}await audit('backup.import',{filePath:result.filePath||null});toast('Резервная копия восстановлена');location.reload()}catch(error){console.error(error);toast(error.message||'Не удалось восстановить backup',true)}}
async function importXlsx(){try{if(!window.bjobDesktop?.importXlsx){toast('Импорт XLSX доступен в .exe',true);return}const result=await window.bjobDesktop.importXlsx();if(result?.cancelled)return;await DB.put('imports',{id:uid('import'),filePath:result.filePath,format:'xlsx',sheets:result.sheets,createdAt:today(),shopId:localStorage.getItem('bjob:v2:active-shop')||null});await audit('import.xlsx',{filePath:result.filePath,sheets:result.sheets?.map(x=>x.name)||[]});toast(`Импорт прочитан: ${result.sheets?.length||0} листов`);await renderRoute()}catch(error){console.error(error);toast(error.message||'Не удалось импортировать XLSX',true)}}
export async function start(){if(!session())return;await renderShell();await renderRoute();window.BJobNavigate=navigate;window.BJobLogout=()=>{logout();location.reload()}}
function fatal(e){console.error('B-JOB render failed',e);const view=document.querySelector('#single-view');if(view)view.innerHTML=page('Ошибка раздела','Не удалось отобразить экран',`<div class="single-fatal-inline">${esc(e?.message||e)}</div>`)}