import * as DB from './db.js';
import {parseWorkbook,importSheets} from './import.js';
import {templatesHtml,downloadTemplate} from './templates.js';

const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=v=>`${Math.round(Number(v)||0).toLocaleString('ru-RU')} ₽`;
const num=v=>Math.round(Number(v)||0).toLocaleString('ru-RU');
const state={page:'overview',loading:false};
const groups=[['Обзор',['overview','analytics','reports']],['Товары',['products','unit']],['Логистика',['warehouses','shipments','fbs']],['Маркетинг',['advertising']],['Управление',['production','api','import','settings']]];
const titles={overview:'Обзор',analytics:'Аналитика',reports:'Отчёты',products:'Товары',unit:'Юнит-экономика',warehouses:'Склады',shipments:'Поставки',fbs:'FBS',advertising:'Реклама',production:'Производство',api:'WB API',import:'Импорт данных',settings:'Личный кабинет'};
const icon={overview:'OV',analytics:'AN',reports:'RE',products:'PR',unit:'UE',warehouses:'WH',shipments:'SH',fbs:'FB',advertising:'AD',production:'PD',api:'API',import:'IM',settings:'AC'};
function nav(){return groups.map(([g,items])=>`<div class="nav-group"><span class="nav-group-title">${g}</span>${items.map(id=>`<button class="nav-link ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon[id]}</span>${titles[id]}</button>`).join('')}</div>`).join('');}
function layout(){return `<div class="app"><header class="top"><div class="brand"><div class="brand-logo">S</div><div><strong>StockFlow</strong><small>Business control system</small></div></div><div class="top-center"><span>Рабочее пространство</span><b>BELTANEE</b></div><div class="top-actions"><button class="btn btn-secondary" data-page="import">Импорт</button><button class="user-chip" data-page="settings"><span>O</span> Oleg</button></div></header><div class="nav-strip">${nav()}</div><main id="content"></main><div id="modal"></div><div id="toast"></div></div>`;}
async function data(){const names=['products','sales','stocks','ads','expenses','fbs','warehouses','shipments','productionOrders'];const out={};for(const n of names)out[n]=await DB.all(n);return out;}
function kpi(label,value,meta=''){return `<div class="kpi"><span>${label}</span><strong>${value}</strong>${meta?`<small>${meta}</small>`:''}</div>`;}
function empty(title,text,action=''){return `<section class="empty"><div class="empty-mark"></div><h2>${title}</h2><p>${text}</p>${action}</section>`;}
function table(head,rows,emptyText='Нет данных'){return `<div class="table-card"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${head.length}" class="table-empty">${emptyText}</td></tr>`}</tbody></table></div>`;}
async function overview(){const d=await data(),orders=d.sales.reduce((s,x)=>s+(Number(x.orders)||0),0),revenue=d.sales.reduce((s,x)=>s+(Number(x.amount)||0),0),stock=d.stocks.reduce((s,x)=>s+(Number(x.available)||0),0),ads=d.ads.reduce((s,x)=>s+(Number(x.spent)||0),0);return `<section class="hero"><div><span class="eyebrow">CONTROL CENTER</span><h1>Бизнес под контролем.</h1><p>Единая система для товаров, продаж, рекламы, складов, FBS и финансов.</p></div><button class="hero-action" data-page="analytics">Открыть аналитику</button></section><div class="kpis">${kpi('Заказы',num(orders),'загруженные данные')}${kpi('Выручка',money(revenue),'загруженные данные')}${kpi('Остаток',num(stock),'по складам')}${kpi('Реклама',money(ads),'фактический расход')}</div><div class="section-title"><h2>Рабочее состояние</h2><span>Обновляется из локальной базы</span></div><div class="status-grid"><div><b>Товары</b><strong>${num(d.products.length)}</strong><span>${d.products.length?'Каталог загружен':'Ожидает импорта'}</span></div><div><b>Продажи</b><strong>${num(d.sales.length)}</strong><span>${d.sales.length?'Есть фактические данные':'Ожидают импорта'}</span></div><div><b>Склады</b><strong>${num(d.warehouses.length)}</strong><span>${d.warehouses.length?'Созданы':'Создайте первый склад'}</span></div><div><b>FBS</b><strong>${num(d.fbs.length)}</strong><span>${d.fbs.length?'Очередь сформирована':'Очередь пуста'}</span></div></div>`;}
async function products(){const d=await data();const map=new Map();for(const p of d.products){const a=p.article||p.id;if(!map.has(a))map.set(a,[]);map.get(a).push(p);}if(!map.size)return empty('Каталог готов','Создайте первую карточку вручную или загрузите шаблон номенклатуры.','<button class="btn btn-primary" data-add-product>Создать карточку</button>');const rows=[...map].map(([a,items])=>{const p=items[0],variants=items.length,stock=d.stocks.filter(x=>x.article===a).reduce((s,x)=>s+(Number(x.available)||0),0);return `<tr><td><b>${esc(a)}</b></td><td>${esc(p.name||'Без названия')}</td><td>${variants}</td><td>${money(p.price)}</td><td>${num(stock)}</td><td><button class="link" data-product="${esc(a)}">Открыть</button></td></tr>`}).join('');return `<div class="page-head"><div><span class="eyebrow">CATALOG</span><h1>Товары</h1><p>Карточки, варианты, цены и остатки.</p></div><button class="btn btn-primary" data-add-product>Создать карточку</button></div>${table(['Артикул','Название','Вариантов','Цена','Остаток',''],rows)}`;}
async function unit(){const d=await data();if(!d.products.length)return empty('Юнит-экономика готова','После добавления товара можно заполнить расходы вручную и сразу получить прибыль и маржу.','<button class="btn btn-primary" data-page="products">Перейти к товарам</button>');const rows=d.products.map(p=>{const price=Number(p.price)||0,cost=Number(p.purchasePrice)||0,com=Number(p.commission)||0,log=Number(p.logisticsCost)||0,ad=Number(p.adCost)||0,other=Number(p.otherExpenses)||0,profit=price-cost-com-log-ad-other,margin=price?profit/price*100:0;return `<tr><td><b>${esc(p.article)}</b></td><td>${money(price)}</td><td>${money(cost)}</td><td>${money(com)}</td><td>${money(log)}</td><td>${money(ad)}</td><td>${money(other)}</td><td><strong>${money(profit)}</strong></td><td>${margin.toFixed(1)}%</td></tr>`}).join('');return `<div class="page-head"><div><span class="eyebrow">FINANCE</span><h1>Юнит-экономика</h1><p>Расходы задаются по товару и участвуют в расчёте автоматически.</p></div><button class="btn btn-secondary" data-expenses>Настроить расходы</button></div><div class="formula">Прибыль = цена − себестоимость − комиссия − логистика − реклама − прочие расходы</div>${table(['Артикул','Цена','Себестоимость','Комиссия','Логистика','Реклама','Прочие','Прибыль','Маржа'],rows)}`;}
async function warehouses(){const d=await data();const rows=d.warehouses.map(w=>`<tr><td><b>${esc(w.name)}</b></td><td>${esc(w.type||'Склад')}</td><td>${num(d.stocks.filter(s=>s.warehouse===w.name).reduce((a,x)=>a+(Number(x.available)||0),0))}</td><td>${esc(w.address||'—')}</td><td><button class="link" data-warehouse="${w.id}">Открыть</button></td></tr>`).join('');return `<div class="page-head"><div><span class="eyebrow">LOGISTICS</span><h1>Склады</h1><p>Создавайте склады, палеты, короба и перемещения.</p></div><button class="btn btn-primary" data-add-warehouse>Создать склад</button></div>${table(['Склад','Тип','Остаток','Адрес',''],rows,'Складов пока нет. Создайте первый склад, чтобы принимать поставки и перемещать товар.')}`;}
async function shipments(){const d=await data();const rows=d.shipments.map(x=>`<tr><td><b>${esc(x.number||x.id)}</b></td><td>${esc(x.warehouse||'—')}</td><td>${esc(x.status||'Черновик')}</td><td>${num(x.itemsCount||0)}</td><td>${esc(x.date||'—')}</td></tr>`).join('');return `<div class="page-head"><div><span class="eyebrow">LOGISTICS</span><h1>Поставки</h1><p>Создание, комплектация, приёмка и история поставок.</p></div><button class="btn btn-primary" data-add-shipment>Создать поставку</button></div>${table(['Номер','Склад','Статус','Позиций','Дата'],rows,'Поставок пока нет. Создайте поставку после создания склада.')}`;}
async function production(){const d=await data();const rows=d.productionOrders.map(x=>`<tr><td><b>${esc(x.number||x.id)}</b></td><td>${esc(x.article||'—')}</td><td>${num(x.quantity||0)}</td><td>${money(x.cost||0)}</td><td>${esc(x.status||'Черновик')}</td></tr>`).join('');return `<div class="page-head"><div><span class="eyebrow">PRODUCTION</span><h1>Производство</h1><p>Заявки на производство и планирование себестоимости.</p></div><button class="btn btn-primary" data-add-production>Создать заявку</button></div>${table(['Заявка','Артикул','Количество','Себестоимость','Статус'],rows,'Заявок нет. Создайте заявку, чтобы планировать выпуск товара.')}`;}
async function fbs(){const d=await data(),statuses=['Новые','Сборка','Упаковка','Готово к отгрузке'];return `<div class="page-head"><div><span class="eyebrow">FULFILLMENT</span><h1>FBS</h1><p>Заказ → сканирование → сборка → короб → отгрузка.</p></div><div><button class="btn btn-secondary" data-scan>Сканировать</button> <button class="btn btn-primary" data-add-fbs>Добавить заказ</button></div></div><div class="kanban">${statuses.map((s,i)=>`<div class="kanban-col"><header><b>${s}</b><span>${num(d.fbs.filter(x=>Number(x.stage||0)===i).length)}</span></header>${d.fbs.filter(x=>Number(x.stage||0)===i).slice(0,30).map(x=>`<article><b>${esc(x.article||'—')}</b><span>${esc(x.barcode||'Без штрихкода')}</span><small>${esc(x.warehouse||'—')}</small></article>`).join('')}</div>`).join('')}</div><div class="scanner-note">Сканирование использует камеру устройства, если браузер поддерживает BarcodeDetector. Для промышленного USB-сканера используется режим клавиатурного ввода.</div>`;}
async function advertising(){const d=await data(),spent=d.ads.reduce((s,x)=>s+(Number(x.spent)||0),0),clicks=d.ads.reduce((s,x)=>s+(Number(x.clicks)||0),0),impr=d.ads.reduce((s,x)=>s+(Number(x.impressions)||0),0),orders=d.ads.reduce((s,x)=>s+(Number(x.orders)||0),0);return `<div class="page-head"><div><span class="eyebrow">MARKETING</span><h1>Реклама</h1><p>Кампании, расходы и эффективность.</p></div><button class="btn btn-primary" data-add-ad>Добавить расход</button></div><div class="kpis">${kpi('Расход',money(spent))}${kpi('CTR',impr?(clicks/impr*100).toFixed(1)+'%':'—')}${kpi('CPC',clicks?money(spent/clicks):'—')}${kpi('CPO',orders?money(spent/orders):'—')}</div>${table(['Кампания','Показы','Клики','Расход','Заказы'],d.ads.map(x=>`<tr><td><b>${esc(x.campaign||'—')}</b></td><td>${num(x.impressions)}</td><td>${num(x.clicks)}</td><td>${money(x.spent)}</td><td>${num(x.orders)}</td></tr>`).join(''),'После импорта рекламного отчёта появятся фактические кампании.')}`;}
async function analytics(){const d=await data();const days={};for(const x of d.sales){const k=x.date||'—';days[k]=(days[k]||0)+(Number(x.orders)||0);}const rows=Object.entries(days).sort().slice(-30).map(([date,v])=>`<tr><td>${esc(date)}</td><td>${num(v)}</td></tr>`).join('');return `<div class="page-head"><div><span class="eyebrow">ANALYTICS</span><h1>Аналитика</h1><p>Фактические показатели и динамика без искусственных данных.</p></div></div><div class="analytics-layout"><div class="chart-card"><h3>Заказы по дням</h3>${rows?table(['Дата','Заказы'],rows):empty('Нет данных','Импортируйте продажи, чтобы построить динамику.')}</div><div class="insights"><h3>Контроль</h3><div>Продажи: <b>${num(d.sales.length)}</b> записей</div><div>Товары: <b>${num(d.products.length)}</b></div><div>Остатки: <b>${num(d.stocks.length)}</b></div><div>Реклама: <b>${num(d.ads.length)}</b></div></div></div>`;}
async function reports(){return `<div class="page-head"><div><span class="eyebrow">REPORTS</span><h1>Отчёты</h1><p>Экспорт фактических данных.</p></div></div><div class="report-grid">${['products','sales','stocks','ads','fbs','expenses'].map(s=>`<button class="report-card" data-export="${s}"><b>${s}</b><span>Скачать CSV</span></button>`).join('')}</div>`;}
async function api(){const rows=(await DB.all('apiConnections')).map(x=>`<tr><td><b>${esc(x.marketplace||'WB')}</b></td><td>${esc(x.name||'Подключение')}</td><td>${x.enabled?'Активно':'Выключено'}</td></tr>`).join('');return `<div class="page-head"><div><span class="eyebrow">INTEGRATIONS</span><h1>WB API</h1><p>Подключение магазинов и синхронизация. Ключ хранится локально и не выводится в интерфейс.</p></div><button class="btn btn-primary" data-add-api>Добавить подключение</button></div>${table(['Маркетплейс','Подключение','Статус'],rows,'Подключений нет. Добавьте API-ключ, чтобы подготовить синхронизацию.')}`;}
async function importer(){return `<div class="page-head"><div><span class="eyebrow">DATA IMPORT</span><h1>Импорт данных</h1><p>Не нужно угадывать формат. Выберите шаблон или загрузите отчёт Wildberries.</p></div><label class="btn btn-primary">Загрузить файл<input id="importFile" type="file" multiple accept=".xlsx,.xls,.csv" hidden></label></div>${templatesHtml()}<div class="import-help"><h3>Как это работает</h3><ol><li>Скачайте подходящий шаблон.</li><li>Заполните его данными или используйте выгрузку WB.</li><li>Загрузите файл. Система определит тип листа и проверит обязательные поля.</li><li>После проверки данные попадут в соответствующий раздел.</li></ol></div>`;}
async function settings(){const d=await data();return `<div class="page-head"><div><span class="eyebrow">ACCOUNT</span><h1>Личный кабинет</h1><p>Профиль, рабочее пространство и контроль доступа.</p></div></div><div class="settings-grid"><div class="settings-card"><h3>Рабочее пространство</h3><label>Название<input value="BELTANEE"></label><label>Роль<input value="Владелец" disabled></label><button class="btn btn-primary">Сохранить</button></div><div class="settings-card"><h3>Команда</h3><p>Добавляйте сотрудников и назначайте роли после подключения серверной авторизации.</p><button class="btn btn-secondary" data-add-user>Добавить сотрудника</button></div><div class="settings-card"><h3>Данные</h3><p>${num(d.products.length)} товаров, ${num(d.sales.length)} продаж, ${num(d.stocks.length)} записей остатков.</p><button class="btn btn-danger" data-reset>Очистить локальные данные</button></div></div>`;}
async function render(){const content=document.getElementById('content');content.classList.add('loading');try{const fn={overview,products,unit,warehouses,shipments,fbs,advertising,analytics,reports,production,api,import:importer,settings}[state.page]||overview;content.innerHTML=await fn();bind();}catch(e){content.innerHTML=empty('Ошибка','Раздел не удалось загрузить. Проверьте данные и попробуйте снова.');console.error(e)}finally{requestAnimationFrame(()=>content.classList.remove('loading'));}}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.className='toast show';setTimeout(()=>el.className='toast',2600);}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>downloadTemplate(b.dataset.template));document.querySelector('[data-refresh]')?.addEventListener('click',render);document.querySelector('#importFile')?.addEventListener('change',handleImport);document.querySelector('[data-reset]')?.addEventListener('click',async()=>{if(confirm('Удалить все локальные данные?')){await DB.reset();toast('Локальные данные очищены');render()}});document.querySelector('[data-add-warehouse]')?.addEventListener('click',()=>modal('Создать склад',['name','type','address'],async v=>{await DB.put('warehouses',{id:'wh:'+Date.now(),...v,createdAt:new Date().toISOString()});toast('Склад создан');render()}));document.querySelector('[data-add-production]')?.addEventListener('click',()=>modal('Заявка на производство',['number','article','quantity','cost'],async v=>{await DB.put('productionOrders',{id:'prod:'+Date.now(),...v,date:new Date().toISOString().slice(0,10),status:'Черновик'});toast('Заявка создана');render()}));document.querySelector('[data-add-shipment]')?.addEventListener('click',()=>modal('Создать поставку',['number','warehouse','itemsCount'],async v=>{await DB.put('shipments',{id:'sh:'+Date.now(),...v,date:new Date().toISOString().slice(0,10),status:'Черновик'});toast('Поставка создана');render()}));document.querySelector('[data-add-api]')?.addEventListener('click',()=>modal('Подключение WB API',['name','token'],async v=>{await DB.put('apiConnections',{id:'api:'+Date.now(),marketplace:'WB',name:v.name,token:v.token,enabled:true});toast('Подключение сохранено локально');render()}));document.querySelector('[data-add-fbs]')?.addEventListener('click',()=>modal('FBS заказ',['article','barcode','warehouse','amount'],async v=>{await DB.put('fbs',{id:'fbs:'+Date.now(),...v,date:new Date().toISOString().slice(0,10),stage:0,status:'new'});toast('Заказ добавлен');render()}));document.querySelector('[data-scan]')?.addEventListener('click',scan);document.querySelector('[data-add-product]')?.addEventListener('click',()=>modal('Создать карточку',['article','name','price','purchasePrice','commission','logisticsCost','adCost','otherExpenses'],async v=>{await DB.put('products',{id:'p:'+v.article,...v});toast('Карточка создана');render()}));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportStore(b.dataset.export));}
async function handleImport(e){if(!e.target.files.length)return;state.loading=true;toast('Проверяем файлы…');try{const sheets=await parseWorkbook(e.target.files[0]);const result=await importSheets(sheets);await DB.put('imports',{id:'imp:'+Date.now(),date:new Date().toISOString(),files:[...e.target.files].map(x=>x.name),result,status:'completed'});toast(`Импорт завершён: ${Object.values(result).reduce((a,b)=>a+b,0)} записей`);state.page='overview';render()}catch(err){toast('Импорт не выполнен: проверьте структуру файла');console.error(err)}finally{state.loading=false}}
function modal(title,fields,save){const m=document.getElementById('modal');m.innerHTML=`<div class="modal-backdrop"><form class="modal"><button type="button" class="modal-close">×</button><h2>${title}</h2>${fields.map(f=>`<label>${f}<input name="${f}" ${f==='token'?'type="password"':''}></label>`).join('')}<button class="btn btn-primary" type="submit">Сохранить</button></form></div>`;m.querySelector('.modal-close').onclick=()=>m.innerHTML='';m.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));await save(v);m.innerHTML='';};}
async function scan(){if(!('BarcodeDetector' in window)){modal('Сканер недоступен',['barcode'],async v=>{const x=(await DB.all('fbs')).find(o=>o.barcode===v.barcode);toast(x?'Заказ найден':'Штрихкод не найден');});return}toast('Сканер камеры доступен: подключите экран сканирования в рабочем режиме FBS.');}
async function exportStore(name){const rows=await DB.all(name);const keys=[...new Set(rows.flatMap(x=>Object.keys(x)))];const csv='\ufeff'+keys.join(';')+'\n'+rows.map(x=>keys.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`StockFlow_${name}.csv`;a.click();URL.revokeObjectURL(a.href);}
async function start(){document.getElementById('app').innerHTML=layout();await render();}
start();
