import * as DB from './db.js';
import {parseWorkbook,importSheets} from './import.js';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=v=>`${Math.round(Number(v)||0).toLocaleString('ru-RU')} ₽`, num=v=>Math.round(Number(v)||0).toLocaleString('ru-RU'), pct=v=>`${(Number(v)||0).toFixed(1)}%`;
const state={page:'dashboard',filter:'all',loading:false};
const nav=[['dashboard','Обзор','◈'],['products','Товары','▦'],['sales','Продажи','↗'],['stock','Остатки','□'],['advertising','Реклама','◎'],['unit','Юнит-экономика','₽'],['fbs','FBS','▤'],['analytics','Аналитика','⌁'],['reports','Отчёты','▤'],['settings','Настройки','⚙']];
function layout(){return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">B</span><div><b>BELTANEE</b><small>BUSINESS ANALYTICS</small></div></div><nav>${nav.map(([id,t,i])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span>${i}</span>${t}</button>`).join('')}</nav><div class="side-bottom"><button class="profile" data-page="settings"><span class="avatar">O</span><span><b>Личный кабинет</b><small>Настройки магазина</small></span></button></div></aside><main class="main"><header class="topbar"><div><span class="eyebrow">BELTANEE / CONTROL CENTER</span><h1 id="title"></h1></div><div class="top-actions"><label class="import-btn">＋ Импорт данных<input id="fileInput" type="file" multiple accept=".xlsx,.xls,.csv" hidden></label><button class="icon-btn" data-page="settings">⚙</button></div></header><section id="content"></section></main></div>`}
function kpi(icon,label,value,sub=''){return `<div class="kpi"><span class="kpi-icon">${icon}</span><div><small>${label}</small><strong>${value}</strong>${sub?`<em>${sub}</em>`:''}</div></div>`}
function empty(icon,title,text){return `<div class="empty"><div class="empty-icon">${icon}</div><h3>${title}</h3><p>${text}</p></div>`}
async function data(){return {products:await DB.all('products'),sales:await DB.all('sales'),stocks:await DB.all('stocks'),ads:await DB.all('ads'),expenses:await DB.all('expenses'),fbs:await DB.all('fbs')}}
async function dashboard(){const d=await data(),orders=d.sales.reduce((s,x)=>s+x.orders,0),revenue=d.sales.reduce((s,x)=>s+x.amount,0),stock=d.stocks.reduce((s,x)=>s+x.available,0),spent=d.ads.reduce((s,x)=>s+x.spent,0);return `<div class="hero"><div><span class="eyebrow">BUSINESS PULSE</span><h2>Ваш бизнес — под контролем.</h2><p>Все ключевые показатели в одном месте. Данные появляются здесь автоматически после импорта.</p></div><div class="hero-orb">B</div></div><div class="kpi-grid">${kpi('↗','Заказы',num(orders))}${kpi('₽','Выручка',money(revenue))}${kpi('□','Остаток',num(stock))}${kpi('◎','Реклама',money(spent))}</div><div class="section-head"><div><h3>Сигналы</h3><p>Только то, что требует внимания.</p></div></div><div class="signal-grid">${orders||revenue?signal('✓','Данные загружены','Основные показатели рассчитаны.','positive'):signal('＋','Начните с импорта','Загрузите номенклатуру, продажи, остатки или рекламу.','neutral')}${d.stocks.length?signal('□','Контроль запасов',`${d.stocks.length.toLocaleString('ru-RU')} записей остатков доступны для анализа.`,'positive'):signal('□','Остатки ещё не загружены','Раздел готов и заполнится после импорта.','neutral')}</div>`}
function signal(i,t,p,c){return `<div class="signal ${c}"><span>${i}</span><div><b>${t}</b><p>${p}</p></div></div>`}
async function products(){const d=await data();if(!d.products.length)return empty('▦','Каталог готов','Здесь появятся карточки товаров. Импортируйте номенклатуру, и каталог заполнится автоматически.');const groups=new Map();for(const p of d.products){const a=p.article||p.id;if(!groups.has(a))groups.set(a,[]);groups.get(a).push(p)}return `<div class="toolbar"><div><h2>Товары</h2><p>${num(groups.size)} карточек · ${num(d.products.length)} вариантов</p></div><button class="primary" id="addProduct">＋ Добавить карточку</button></div><div class="product-grid">${[...groups].map(([a,items])=>{const p=items[0],colors=[...new Set(items.map(x=>x.color).filter(Boolean))],sizes=[...new Set(items.map(x=>x.size).filter(Boolean))];return `<article class="product-card"><div class="product-photo">${(p.name||a).slice(0,1).toUpperCase()}</div><div class="product-main"><span class="tag">${esc(p.status||'Активен')}</span><h3>${esc(p.name||a)}</h3><b class="article">${esc(a)}</b><div class="product-meta"><span>${money(p.price)}</span><span>${num(d.stocks.filter(s=>s.article===a).reduce((x,s)=>x+s.available,0))} шт.</span></div><select class="variant-select"><option>Выберите вариант</option>${colors.map(c=>`<option>Цвет: ${esc(c)}</option>`).join('')}${sizes.map(s=>`<option>Размер: ${esc(s)}</option>`).join('')}</select></div></article>`}).join('')}</div>`}
async function sales(){const d=await data(),orders=d.sales.reduce((s,x)=>s+x.orders,0),rev=d.sales.reduce((s,x)=>s+x.amount,0);return `<div class="toolbar"><div><h2>Продажи</h2><p>Фактические данные из загруженных отчётов</p></div></div><div class="kpi-grid">${kpi('↗','Заказы',num(orders))}${kpi('₽','Выручка',money(rev))}${kpi('✓','Операций',num(d.sales.length))}</div>${d.sales.length?`<div class="table-card"><table><thead><tr><th>Дата</th><th>Артикул</th><th>Заказы</th><th>Выручка</th><th>Склад</th></tr></thead><tbody>${d.sales.slice(-500).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td><b>${esc(x.article)}</b></td><td>${num(x.orders)}</td><td>${money(x.amount)}</td><td>${esc(x.warehouse||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('↗','Продажи готовы','После импорта отчёта продаж здесь появится история и динамика.')}`}
async function stock(){const d=await data(),total=d.stocks.reduce((s,x)=>s+x.available,0),by=new Map();for(const x of d.stocks){const a=x.article||'Без артикула';by.set(a,(by.get(a)||0)+x.available)}return `<div class="toolbar"><div><h2>Остатки</h2><p>Запас, покрытие и распределение</p></div></div><div class="kpi-grid">${kpi('□','Остаток',num(total))}${kpi('▦','Позиций',num(by.size))}${kpi('⌂','Записей',num(d.stocks.length))}</div>${d.stocks.length?`<div class="table-card"><table><thead><tr><th>Артикул</th><th>Склад</th><th>Остаток</th><th>Размер</th><th>Дата</th></tr></thead><tbody>${d.stocks.slice(-500).reverse().map(x=>`<tr><td><b>${esc(x.article)}</b></td><td>${esc(x.warehouse||'—')}</td><td><strong>${num(x.available)}</strong></td><td>${esc(x.size||'—')}</td><td>${esc(x.date||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('□','Остатки готовы','После импорта остатков здесь появится распределение по складам и товарам.')}`}
async function advertising(){const d=await data(),spent=d.ads.reduce((s,x)=>s+x.spent,0),clicks=d.ads.reduce((s,x)=>s+x.clicks,0),impr=d.ads.reduce((s,x)=>s+x.impressions,0),orders=d.ads.reduce((s,x)=>s+x.orders,0);return `<div class="toolbar"><div><h2>Реклама</h2><p>Расход → показы → клики → заказы</p></div><button class="primary">＋ Добавить расход</button></div><div class="kpi-grid">${kpi('₽','Расход',money(spent))}${kpi('◉','CTR',pct(impr?clicks/impr*100:0))}${kpi('⌁','CPC',money(clicks?spent/clicks:0))}${kpi('↗','CPO',money(orders?spent/orders:0))}</div><div class="formula-strip"><b>Прозрачные расчёты</b><span>CTR = клики / показы</span><span>CPC = расход / клики</span><span>CPO = расход / заказы</span></div>${d.ads.length?`<div class="table-card"><table><thead><tr><th>Кампания</th><th>Показы</th><th>Клики</th><th>Расход</th><th>Заказы</th></tr></thead><tbody>${d.ads.map(x=>`<tr><td><b>${esc(x.campaign||'—')}</b></td><td>${num(x.impressions)}</td><td>${num(x.clicks)}</td><td>${money(x.spent)}</td><td>${num(x.orders)}</td></tr>`).join('')}</tbody></table></div>`:empty('◎','Реклама готова','Импортируйте рекламный отчёт. Здесь будут кампании, эффективность и рекомендации.')}`}
async function unit(){const d=await data(),rows=d.products.map(p=>{const profit=(p.price||0)-(p.purchasePrice||0)-(p.commission||0)-(p.logisticsCost||0)-(p.adCost||0),margin=p.price?profit/p.price*100:0;return `<tr><td><b>${esc(p.article)}</b></td><td>${money(p.price)}</td><td>${money(p.purchasePrice)}</td><td>${money(p.commission)}</td><td>${money(p.logisticsCost)}</td><td>${money(p.adCost)}</td><td><strong>${money(profit)}</strong></td><td>${pct(margin)}</td></tr>`}).join('');return `<div class="toolbar"><div><h2>Юнит-экономика</h2><p>Настраиваемая экономика каждой карточки</p></div><button class="primary">⚙ Расходы и правила</button></div><div class="formula-strip"><b>Прибыль</b><span>Цена − себестоимость − комиссия − логистика − реклама − прочие расходы</span></div>${d.products.length?`<div class="table-card"><table><thead><tr><th>Артикул</th><th>Цена</th><th>Себестоимость</th><th>Комиссия</th><th>Логистика</th><th>Реклама</th><th>Прибыль</th><th>Маржа</th></tr></thead><tbody>${rows}</tbody></table></div>`:empty('₽','Юнит-экономика готова','Загрузите номенклатуру. Расходы можно будет заполнить и пересчитывать.')}`}
async function fbs(){const d=await data();return `<div class="toolbar"><div><h2>FBS</h2><p>Заказы, сборка и отгрузка со своего склада</p></div><button class="primary">＋ Добавить заказ</button></div><div class="status-board"><div><b>Новые</b><strong>${num(d.fbs.filter(x=>x.status==='new'||!x.status).length)}</strong></div><div><b>Сборка</b><strong>${num(d.fbs.filter(x=>/сбор|pack/i.test(x.status||'')).length)}</strong></div><div><b>Отгрузка</b><strong>${num(d.fbs.filter(x=>/отг|ship/i.test(x.status||'')).length)}</strong></div><div><b>Готово</b><strong>${num(d.fbs.filter(x=>/достав|done/i.test(x.status||'')).length)}</strong></div></div>${d.fbs.length?`<div class="table-card"><table><thead><tr><th>Дата</th><th>Артикул</th><th>Статус</th><th>Склад</th><th>Сумма</th></tr></thead><tbody>${d.fbs.map(x=>`<tr><td>${esc(x.date)}</td><td><b>${esc(x.article)}</b></td><td>${esc(x.status||'Новый')}</td><td>${esc(x.warehouse||'—')}</td><td>${money(x.amount)}</td></tr>`).join('')}</tbody></table></div>`:empty('▤','FBS готов к работе','Здесь будет рабочая очередь FBS: новые заказы → сборка → отгрузка → завершение.')}`}
async function analytics(){const d=await data();return `<div class="toolbar"><div><h2>Аналитика</h2><p>Пульс бизнеса и точки роста</p></div></div><div class="analytics-grid"><div class="analytics-card large"><span>Продажи</span><strong>${num(d.sales.reduce((s,x)=>s+x.orders,0))}</strong><p>заказов в загруженном периоде</p><div class="bars">${[...Array(12)].map((_,i)=>`<i style="height:${10+((i*37)%70)}%"></i>`).join('')}</div></div><div class="analytics-card"><span>Товары</span><strong>${num(d.products.length)}</strong><p>вариантов в каталоге</p></div><div class="analytics-card"><span>Реклама</span><strong>${money(d.ads.reduce((s,x)=>s+x.spent,0))}</strong><p>фактический расход</p></div></div>`}
async function reports(){return `<div class="toolbar"><div><h2>Отчёты</h2><p>Экспорт и контроль данных</p></div></div><div class="grid-3"><div class="panel"><b>Продажи</b><p>Экспорт текущей истории в CSV.</p><button class="secondary" data-export="sales">Скачать</button></div><div class="panel"><b>Состояние базы</b><p>Проверить количество записей по разделам.</p><button class="secondary" data-page="settings">Открыть</button></div><div class="panel"><b>Резервная копия</b><p>Скачать локальную копию данных.</p><button class="secondary" id="backup">Backup JSON</button></div></div>`}
async function settings(){const d=await data();return `<div class="toolbar"><div><h2>Настройки</h2><p>Данные, расходы и параметры магазина</p></div></div><div class="settings-grid"><div class="panel"><h3>Состояние данных</h3>${Object.entries(d).map(([k,v])=>`<div class="setting-row"><span>${k}</span><b>${num(v.length)}</b></div>`).join('')}</div><div class="panel"><h3>Магазин</h3><label>Название<input id="shopName" value="BELTANEE"></label><label>Валюта<select><option>RUB — ₽</option></select></label><button class="primary" id="saveSettings">Сохранить</button></div><div class="panel danger"><h3>Очистить данные</h3><p>Удаляет только локальные импортированные данные. Шаблоны не затрагиваются.</p><button class="danger-btn" id="reset">Очистить базу</button></div></div>`}
const pages={dashboard,products,sales,stock,advertising,unit,fbs,analytics,reports,settings};
async function render(page=state.page){state.page=page;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const title=nav.find(x=>x[0]===page)?.[1]||'Обзор';document.querySelector('#title').textContent=title;const content=document.querySelector('#content');content.classList.add('loading');await new Promise(r=>requestAnimationFrame(r));try{content.innerHTML=await pages[page]();bind();}catch(e){console.error(e);content.innerHTML=empty('!','Ошибка раздела',e.message)}content.classList.remove('loading')}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));document.querySelector('#fileInput')?.addEventListener('change',importFiles);document.querySelector('#reset')?.addEventListener('click',async()=>{if(confirm('Очистить все импортированные данные?')){await DB.reset();toast('База очищена');render()}});document.querySelector('#backup')?.addEventListener('click',backup);document.querySelector('[data-export="sales"]')?.addEventListener('click',()=>exportRows('sales'));}
async function importFiles(e){const files=[...e.target.files];if(!files.length)return;const content=document.querySelector('#content');content.innerHTML=`<div class="import-progress"><div class="spinner"></div><h2>Обрабатываем данные</h2><p id="progress">Читаем файлы…</p><div class="progress"><i id="bar"></i></div></div>`;try{let all=[];for(const f of files){const sheets=await parseWorkbook(f);all.push(...sheets)}const result=await importSheets(all,(p,name,type)=>{document.querySelector('#progress').textContent=`${name} · ${type}`;document.querySelector('#bar').style.width=`${p*100}%`});toast(`Импорт завершён: ${Object.values(result).reduce((a,b)=>a+b,0).toLocaleString('ru-RU')} записей`);await render(state.page)}catch(err){console.error(err);toast('Ошибка импорта: '+err.message)}e.target.value=''}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
async function exportRows(store){const rows=await DB.all(store);if(!rows.length)return toast('Нет данных для экспорта');const keys=[...new Set(rows.flatMap(Object.keys))];const csv='\ufeff'+[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`beltanee-${store}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function backup(){const snap=await DB.snapshot();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(snap,null,2)],{type:'application/json'}));a.download='beltanee-backup.json';a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#app').innerHTML=layout();
render('dashboard');
