import {replaceMany,putMany} from './db.js';
const aliases={
 article:['артикул','vendor code','vendorcode','nm id','nm_id','sku','арт'],date:['дата','date','день','period'],orders:['заказы','заказ','orders','количество заказов'],amount:['выручка','сумма','amount','sales'],stock:['остаток','остатки','stock','quantity','доступно'],warehouse:['склад','warehouse','wb склад'],price:['цена','price','розничная цена'],cost:['себестоимость','cost','закупка'],commission:['комиссия','commission'],logistics:['логистика','logistics'],spent:['расход','затраты','spent','advertising cost'],clicks:['клики','clicks'],impressions:['показы','impressions'],campaign:['кампания','campaign'],size:['размер','size'],color:['цвет','color'],status:['статус','status']};
const clean=v=>String(v??'').trim();const norm=v=>clean(v).toLowerCase().replace(/[\s_\-№%()]/g,'');
function pick(headers,field){const a=aliases[field]||[];return headers.find(h=>a.some(x=>norm(h).includes(norm(x))))}
function val(row,h){return h==null?'':row[h]}
function n(v){const x=Number(String(v??'').replace(/\s/g,'').replace(',','.').replace(/[^0-9.\-]/g,''));return Number.isFinite(x)?x:0}
function date(v){if(v instanceof Date)return v.toISOString().slice(0,10);const s=clean(v);if(!s)return new Date().toISOString().slice(0,10);const m=s.match(/(\d{1,2})[.\-/](\d{1,2})[.\-/](\d{2,4})/);return m?`${m[3].length===2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s.slice(0,10)}
export async function parseWorkbook(file){const XLSX=await import('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const sheets=[];for(const name of wb.SheetNames){const ws=wb.Sheets[name];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(rows.length)sheets.push({name,rows})}return sheets}
export function classify(sheet){const h=Object.keys(sheet.rows[0]||{});const score={products:0,sales:0,stocks:0,ads:0,fbs:0};if(pick(h,'article'))score.products+=2,score.sales+=2,score.stocks+=2;if(pick(h,'orders'))score.sales+=4;if(pick(h,'stock'))score.stocks+=4;if(pick(h,'warehouse'))score.stocks+=2;if(pick(h,'spent')||pick(h,'campaign'))score.ads+=4;if(h.some(x=>norm(x).includes('fbs')||norm(x).includes('сборка')||norm(x).includes('доставк')) )score.fbs+=3;return Object.entries(score).sort((a,b)=>b[1]-a[1])[0][0]}
export function normalize(sheet,type){const h=Object.keys(sheet.rows[0]||{}),map={};for(const f of Object.keys(aliases))map[f]=pick(h,f);return sheet.rows.map((r,i)=>{const article=clean(val(r,map.article));const base={sourceSheet:sheet.name,row:i+2,article};if(type==='products')return {...base,id:`p:${article||i}`,name:clean(val(r,h.find(x=>/назван|товар|наимен/i.test(x))),),price:n(val(r,map.price)),purchasePrice:n(val(r,map.cost)),commission:n(val(r,map.commission)),logisticsCost:n(val(r,map.logistics)),color:clean(val(r,map.color)),size:clean(val(r,map.size)),status:clean(val(r,map.status))};if(type==='sales')return {...base,id:`s:${date(val(r,map.date))}:${article}:${i}`,date:date(val(r,map.date)),orders:n(val(r,map.orders))||1,amount:n(val(r,map.amount)),price:n(val(r,map.price)),warehouse:clean(val(r,map.warehouse))};if(type==='stocks')return {...base,id:`st:${date(val(r,map.date))}:${article}:${clean(val(r,map.warehouse))}`,date:date(val(r,map.date)),available:n(val(r,map.stock)),warehouse:clean(val(r,map.warehouse)),size:clean(val(r,map.size)),color:clean(val(r,map.color))};if(type==='ads')return {...base,id:`ad:${date(val(r,map.date))}:${clean(val(r,map.campaign))}:${i}`,date:date(val(r,map.date)),campaign:clean(val(r,map.campaign)),spent:n(val(r,map.spent)),clicks:n(val(r,map.clicks)),impressions:n(val(r,map.impressions)),orders:n(val(r,map.orders))};return {...base,id:`fbs:${i}`,date:date(val(r,map.date)),status:clean(val(r,map.status)),warehouse:clean(val(r,map.warehouse)),amount:n(val(r,map.amount))}}).filter(x=>x.article||type==='ads'||type==='fbs')}
export async function importSheets(sheets,progress=()=>{}){let products=[],sales=[],stocks=[],ads=[],fbs=[];for(let i=0;i<sheets.length;i++){const s=sheets[i],type=classify(s);const rows=normalize(s,type);if(type==='products')products.push(...rows);if(type==='sales')sales.push(...rows);if(type==='stocks')stocks.push(...rows);if(type==='ads')ads.push(...rows);if(type==='fbs')fbs.push(...rows);progress((i+1)/sheets.length,s.name,type)}const dedupe=(rows)=>[...new Map(rows.map(x=>[x.id,x])).values()];products=dedupe(products);sales=dedupe(sales);stocks=dedupe(stocks);ads=dedupe(ads);fbs=dedupe(fbs);if(products.length)await putMany('products',products);if(sales.length)await putMany('sales',sales);if(stocks.length)await putMany('stocks',stocks);if(ads.length)await putMany('ads',ads);if(fbs.length)await putMany('fbs',fbs);return {products:products.length,sales:sales.length,stocks:stocks.length,ads:ads.length,fbs:fbs.length}}
