// ============================================================
// BELTANEE — APPLICATION INITIALIZATION
// ============================================================

import DataIntegrityService from './services/DataIntegrityService.js';
import Database from './infrastructure/db.js';
import DemoDataService from './services/DemoDataService.js';
import { getDemoExperience, getDemoOnboardingState, completeDemoOnboarding } from './demo/demoExperience.js';
import { installV61Pages } from './ui/v61AnalyticsPages.js';
import { initImportController } from './ui/importController.js';
import { showLoading, setLoadingMessage, hideLoading } from './ui/loadingScreen.js';

function loadDemoStyles() {
    if (document.querySelector('link[data-beltanee-demo-styles]')) return;
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = './src/demo/demoStyles.css';
    link.dataset.beltaneeDemoStyles = '1';
    document.head.appendChild(link);
}

function escapeHtml(value) { return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function withTimeout(promise, ms, message) { return Promise.race([promise, new Promise((_, reject) => setTimeout(() => reject(new Error(message)), ms))]); }
async function collectBackup() { const backup = { version: '1.0', createdAt: new Date().toISOString(), database: Database.DB_NAME, dbVersion: Database.DB_VERSION, stores: {} }; for (const storeName of Object.values(Database.STORES)) { try { backup.stores[storeName] = await Database.getAll(storeName); } catch { backup.stores[storeName] = []; } } return backup; }
function downloadJson(filename, data) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function ensureProfilePage() {
    if (document.getElementById('page-profile')) return;
    const section = document.createElement('section'); section.id = 'page-profile'; section.className = 'page';
    section.innerHTML = `<div class="page-header"><h1>👤 Личный кабинет</h1><span style="font-size:12px;color:var(--text-secondary);">Локальный профиль BELTANEE</span></div><div class="grid-3"><div class="card"><div class="card-title">Профиль</div><div class="form-group"><label>Имя</label><input id="profileName" type="text" placeholder="Ваше имя"></div><div class="form-group"><label>Название бизнеса</label><input id="profileBusiness" type="text" placeholder="Название магазина"></div><button class="btn btn-primary" id="saveProfileBtn">💾 Сохранить</button></div><div class="card"><div class="card-title">Хранилище</div><div id="profileStorageInfo">Загрузка…</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:16px;"><button class="btn btn-secondary btn-sm" id="backupDataBtn">⬇️ Резервная копия</button><button class="btn btn-danger btn-sm" id="resetDataBtn">🗑️ Пересобрать данные</button></div></div><div class="card"><div class="card-title">Контроль данных</div><div id="dataIntegrityInfo">Проверяем после запуска…</div><div style="margin-top:12px;font-size:12px;color:var(--text-secondary);">${escapeHtml(Database.DB_NAME)} · schema ${Database.DB_VERSION}</div></div></div>`;
    document.querySelector('main.content')?.appendChild(section);
    const profile = JSON.parse(localStorage.getItem('beltanee-profile') || '{}'), name = document.getElementById('profileName'), business = document.getElementById('profileBusiness'); if (name) name.value = profile.name || ''; if (business) business.value = profile.business || '';
    document.getElementById('saveProfileBtn')?.addEventListener('click', () => { localStorage.setItem('beltanee-profile', JSON.stringify({ name: name?.value || '', business: business?.value || '' })); window.showToast?.('Профиль сохранён', 'success'); });
    document.getElementById('backupDataBtn')?.addEventListener('click', async () => { try { downloadJson(`beltanee-backup-${new Date().toISOString().slice(0,10)}.json`, await collectBackup()); window.showToast?.('Резервная копия создана', 'success'); } catch (error) { window.showToast?.(`Ошибка резервной копии: ${error.message}`, 'error'); } });
    document.getElementById('resetDataBtn')?.addEventListener('click', async () => { if (!confirm('Пересобрать фактические данные? Товары и профиль сохранятся, продажи/остатки/финансы будут очищены.')) return; for (const storeName of [Database.STORES.SALES, Database.STORES.STOCK, Database.STORES.STOCK_HISTORY, Database.STORES.FINANCE]) { try { await Database.clear(storeName); } catch {} } window.showToast?.('Фактические данные очищены. Импортируйте отчёты заново.', 'success'); setTimeout(() => window.location.reload(), 600); });
    setTimeout(() => DataIntegrityService.inspect().then(report => { const el = document.getElementById('dataIntegrityInfo'); if (!el) return; if (!report.warnings.length) { el.innerHTML = '✅ Дубликаты и критические аномалии не обнаружены.'; return; } el.innerHTML = `${report.ok ? '⚠️' : '🔴'} Найдено проблем: <strong>${report.warnings.length}</strong><br>` + report.warnings.map(w => `• ${escapeHtml(w.message)}`).join('<br>'); }).catch(error => { const el = document.getElementById('dataIntegrityInfo'); if (el) el.textContent = `Ошибка проверки: ${error.message}`; }), 250);
    Promise.all([Database.count(Database.STORES.PRODUCTS), Database.count(Database.STORES.SALES), Database.count(Database.STORES.STOCK), Database.count(Database.STORES.ADVERTISING)]).then(([products, sales, stock, ads]) => { const el = document.getElementById('profileStorageInfo'); if (el) el.innerHTML = `Товары: <strong>${products}</strong><br>Продажи: <strong>${sales}</strong><br>Остатки: <strong>${stock}</strong><br>Реклама: <strong>${ads}</strong>`; }).catch(() => {});
}
function patchProfileButton() { const button = document.getElementById('profileBtn'); if (!button || button.dataset.beltaneePatched) return; const replacement = button.cloneNode(true); replacement.dataset.beltaneePatched = '1'; replacement.addEventListener('click', () => { ensureProfilePage(); window.navigateTo?.('profile'); }); button.replaceWith(replacement); }
function ensureDemoExperience() {
    const experience = getDemoExperience();
    if (!experience?.products?.length || document.getElementById('demoExperienceBar')) return;
    const main = document.querySelector('main.content');
    if (!main) return;
    const bar = document.createElement('section'); bar.id = 'demoExperienceBar'; bar.className = 'demo-pulse';
    bar.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap;"><div><div class="demo-badge">DEMO 1 · ${escapeHtml(experience.config?.brand || 'BELTANEE')}</div><h2 style="margin:10px 0 4px;font-size:20px;">${escapeHtml(experience.pulse.headline)}</h2><div style="font-size:12px;color:var(--text-secondary);">${experience.actions.length} действия уже сформированы системой</div></div><button class="btn btn-secondary btn-sm" id="demoTourBtn">Как это работает</button></div><div class="grid-3" style="margin-top:16px;">${experience.pulse.metrics.map(metric => `<div class="demo-kpi"><div style="font-size:11px;color:var(--text-secondary);">${escapeHtml(metric.label)}</div><div style="font-size:20px;font-weight:750;margin-top:5px;">${escapeHtml(metric.value)}</div><div style="font-size:11px;margin-top:4px;">${escapeHtml(metric.trend)}</div></div>`).join('')}</div><div style="display:grid;gap:8px;margin-top:14px;">${experience.actions.slice(0,3).map(action => `<div class="demo-action-card" style="display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 12px;border:1px solid rgba(0,0,0,.06);border-radius:12px;background:rgba(255,255,255,.65);"><div><strong>${escapeHtml(action.article)}</strong><div style="font-size:11px;color:var(--text-secondary);margin-top:3px;">${escapeHtml(action.title || action.description || 'Рекомендуем проверить товар')}</div></div><span class="demo-badge">${escapeHtml(action.priority || 'Важно')}</span></div>`).join('')}</div>`;
    main.prepend(bar); document.getElementById('demoTourBtn')?.addEventListener('click', () => showDemoTour(true)); if (!getDemoOnboardingState().completed) setTimeout(() => showDemoTour(false), 700);
}
function showDemoTour(force) {
    if (!force && getDemoOnboardingState().completed) return; if (document.getElementById('demoTourOverlay')) return;
    const overlay = document.createElement('div'); overlay.id = 'demoTourOverlay'; overlay.style.cssText = 'position:fixed;inset:0;z-index:9999;background:rgba(10,12,18,.48);backdrop-filter:blur(5px);display:grid;place-items:center;padding:20px;';
    overlay.innerHTML = `<div class="card" style="max-width:520px;width:100%;padding:28px;box-shadow:0 24px 80px rgba(0,0,0,.24);"><div class="demo-badge">ПЕРВЫЙ ЗАПУСК</div><h2 style="margin:14px 0 8px;">Система уже нашла точки внимания</h2><p style="color:var(--text-secondary);line-height:1.55;margin-bottom:20px;">Сначала смотрим на Пульс бизнеса, затем открываем проблемный артикул и получаем конкретное действие. Демо-данные можно заменить реальным импортом в любой момент.</p><div style="display:grid;gap:9px;margin-bottom:22px;"><div>① <strong>Пульс</strong> — что происходит с бизнесом</div><div>② <strong>Товары</strong> — где именно проблема</div><div>③ <strong>Рекомендации</strong> — что сделать дальше</div></div><button class="btn btn-primary" id="demoTourClose" style="width:100%;">Понятно, показать систему</button></div>`;
    document.body.appendChild(overlay); document.getElementById('demoTourClose')?.addEventListener('click', () => { completeDemoOnboarding(); overlay.remove(); window.dispatchEvent(new CustomEvent('beltanee:demo-onboarding-complete')); });
}
async function checkArchitecture() { setLoadingMessage('Проверяем подключение локального хранилища…'); const names = [Database.STORES.PRODUCTS, Database.STORES.SALES, Database.STORES.STOCK, Database.STORES.ADVERTISING]; const counts = await withTimeout(Promise.all(names.map(store => Database.count(store))), 12000, 'Локальное хранилище не отвечает за 12 секунд. Закройте другие вкладки BELTANEE и повторите запуск.'); const report = { products: counts[0], sales: counts[1], stock: counts[2], advertising: counts[3], database: Database.DB_NAME, schema: Database.DB_VERSION, integrityDeferred: true }; console.info('[BELTANEE] Startup report', report); window.__BELTANEE_STARTUP_REPORT__ = report; return report; }
async function seedDemoIfEmpty() { const demoResult = await DemoDataService.seedDemoData(); if (!demoResult.seeded) return demoResult; console.info('[BELTANEE] Demo 1 seeded', demoResult); window.__BELTANEE_DEMO__ = demoResult; window.showToast?.('Демо-данные загружены: можно показать аналитику', 'success'); return demoResult; }
async function init() { loadDemoStyles(); showLoading('Запускаем BELTANEE…'); document.title = 'BELTANEE — Аналитическая платформа'; document.querySelector('.logo-text')?.replaceChildren(document.createTextNode('BELTANEE')); const badge = document.querySelector('.logo-badge'); if (badge) badge.textContent = '1.6'; ensureProfilePage(); patchProfileButton(); setLoadingMessage('Подготавливаем демонстрационные данные…'); try { await seedDemoIfEmpty(); } catch (error) { console.warn('[BELTANEE] Demo seed skipped:', error); } setLoadingMessage('Подключаем импорт шаблонов WB…'); installV61Pages(); initImportController(); try { const report = await checkArchitecture(); ensureDemoExperience(); setLoadingMessage('Рабочее пространство готово'); await new Promise(resolve => setTimeout(resolve, 300)); hideLoading(); console.log('✅ BELTANEE 1.6 ready', report); } catch (error) { console.error('[BELTANEE] Startup failed', error); setLoadingMessage(`Ошибка запуска: ${error.message}`); window.showToast?.(`Ошибка запуска: ${error.message}`, 'error'); await new Promise(resolve => setTimeout(resolve, 1400)); hideLoading(); } }
init();
export { checkArchitecture, ensureProfilePage, seedDemoIfEmpty, ensureDemoExperience };