import * as DB from './db.js';

const AUTH_KEY='bjob:v1:role';
const API_KEY='bjob:api-base';
const CREDS={SKLAD:{password:'SKLAD1',role:'warehouse'},ADMIN:{password:'ADMINB1',role:'admin'}};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));

function injectStyle(){if(document.getElementById('bjob-v1-style'))return;const s=document.createElement('style');s.id='bjob-v1-style';s.textContent=`
.v1-login{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:#0d0f13;color:#f5f6f8;font-family:Inter,system-ui,sans-serif}.v1-login-card{width:min(420px,calc(100vw - 32px));padding:32px;border:1px solid #2b3038;border-radius:22px;background:#15181e;box-shadow:0 30px 80px #0008}.v1-login-card h1{margin:0 0 8px}.v1-login-card p{color:#aeb5c0}.v1-login-card label{display:block;margin:14px 0 6px;color:#cbd1da}.v1-login-card input{width:100%;box-sizing:border-box;padding:13px;border:1px solid #343b46;border-radius:10px;background:#0f1217;color:#fff}.v1-login-card button{width:100%;margin-top:18px;padding:13px;border:0;border-radius:10px;background:#fff;color:#111;font-weight:700;cursor:pointer}.v1-login-error{min-height:20px;color:#ff7c7c;margin-top:10px}.v1-tools{position:fixed;right:18px;bottom:18px;z-index:9000;display:flex;gap:8px}.v1-tools button{border:1px solid #d8dbe0;background:#fff;border-radius:9px;padding:9px 12px;cursor:pointer}.v1-modal{position:fixed;inset:0;z-index:100000;background:#0008;display:grid;place-items:center;padding:20px}.v1-modal-card{width:min(760px,100%);max-height:90vh;overflow:auto;background:#fff;color:#111;border-radius:18px;padding:22px}.v1-modal-card h2{margin-top:0}.v1-form{display:grid;gap:12px}.v1-form label{display:grid;gap:5px;font-weight:600}.v1-form input,.v1-form select{padding:10px;border:1px solid #ccd1d8;border-radius:8px}.v1-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}.v1-actions button{padding:10px 14px;border-radius:8px;border:1px solid #ccd1d8;background:#fff;cursor:pointer}.v1-actions .primary{background:#111;color:#fff;border-color:#111}.v1-badge{display:inline-block;padding:4px 8px;border-radius:99px;background:#eef1f5;color:#313640;font-size:12px}
`;document.head.appendChild(s)}

function role(){return sessionStorage.getItem(AUTH_KEY)||''}
function setRole(r){sessionStorage.setItem(AUTH_KEY,r)}
function gate(){if(role())return;const root=document.createElement('div');root.className='v1-login';root.innerHTML=`<div class="v1-login-card"><small>B-JOB · ДОСТУП</small><h1>Вход в систему</h1><p>Выберите учётную запись и войдите в рабочее пространство.</p><form><label>Логин<input name="login" autocomplete="username" required></label><label>Пароль<input name="password" type="password" autocomplete="current-password" required></label><div class="v1-login-error"></div><button>Войти</button></form></div>`;document.body.appendChild(root);root.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const login=e.target.login.value.trim().toUpperCase(),password=e.target.password.value;const c=CREDS[login];if(!c||c.password!==password){root.querySelector('.v1-login-error').textContent='Неверный логин или пароль.';return}setRole(c.role);location.reload()})}

function restrictNav(){const r=role();if(!r)return;const apply=()=>{document.querySelectorAll('#mainNav button[data-page]').forEach(b=>{const page=b.dataset.page;b.hidden=r==='warehouse'&&page!=='fbs';});document.querySelectorAll('[data-page]').forEach(b=>{if(r==='warehouse'&&b.dataset.page&&b.dataset.page!=='fbs')b.hidden=true})};apply();new MutationObserver(apply).observe(document.body,{subtree:true,childList:true})}

async function snapshot(){return DB.snapshot()}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function backup(){const data=await snapshot();download(`bjob-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,createdAt:new Date().toISOString(),data},null,2))}
async function restore(file){const raw=await file.text();const parsed=JSON.parse(raw);if(!parsed?.data||typeof parsed.data!=='object')throw new Error('Неверный JSON-файл B-JOB.');for(const [store,rows] of Object.entries(parsed.data)){if(!Array.isArray(rows)||!DB.STORES.includes(store))continue;await DB.replaceMany(store,rows)}location.reload()}
function modal(title,body){const w=document.createElement('div');w.className='v1-modal';w.innerHTML=`<div class="v1-modal-card"><h2>${title}</h2>${body}</div>`;document.body.appendChild(w);w.addEventListener('click',e=>{if(e.target===w)w.remove()});return w}
function tools(){if(document.querySelector('.v1-tools')||!role())return;const t=document.createElement('div');t.className='v1-tools';t.innerHTML=`<button data-v1="backup">Экспорт JSON</button><button data-v1="import">Импорт JSON</button><button data-v1="source">Источник данных</button><button data-v1="logout">Выйти</button>`;document.body.appendChild(t);t.onclick=async e=>{const b=e.target.closest('[data-v1]');if(!b)return;try{if(b.dataset.v1==='backup')await backup();if(b.dataset.v1==='import'){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{if(i.files[0])try{await restore(i.files[0])}catch(err){alert(err.message)}};i.click()}if(b.dataset.v1==='logout'){sessionStorage.removeItem(AUTH_KEY);location.reload()}if(b.dataset.v1==='source'){const current=localStorage.getItem(API_KEY)||'';const w=modal('Источник данных',`<div class="v1-form"><p>Можно работать автономно через IndexedDB или указать адрес B-JOB API в локальной сети.</p><label>API URL<input id="v1-api" value="${esc(current)}" placeholder="http://192.168.1.20:8787"></label><span class="v1-badge">Пусто = автономный режим</span></div><div class="v1-actions"><button data-close>Отмена</button><button class="primary" data-save>Сохранить и перезагрузить</button></div>`);w.querySelector('[data-close]').onclick=()=>w.remove();w.querySelector('[data-save]').onclick=()=>{localStorage.setItem(API_KEY,w.querySelector('#v1-api').value.trim());location.reload()}}}catch(err){alert(err.message)}}}

injectStyle();gate();restrictNav();tools();
