const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const http = require('http');
const { URL } = require('url');
const crypto = require('crypto');
const { createLanServer, localIPv4 } = require('./lanServer');
const { createProtocol } = require('./lanProtocol');
const { createSyncProtocol } = require('./syncProtocol');
const { createSyncStorage } = require('./syncStorage');
const { createBackupManifest, verifyBackup } = require('./dataIntegrity');

let server,serverPort,lanServer,lanConfig,syncStorage;
const LAN_STORES=['products','stocks','warehouses','fbsSpaces','fbsBoxes','fbsInventory','stockMovements','shipments'];
function dataDir(){const dir=path.join(app.getPath('userData'),'data');fs.mkdirSync(dir,{recursive:true});return dir}
function appRoot(){return app.isPackaged?path.join(process.resourcesPath,'bjob-app'):path.resolve(__dirname,'..')}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};
function safePath(p){try{const root=path.resolve(appRoot()),target=path.resolve(root,`.${decodeURIComponent(p)}`);return target===root||target.startsWith(root+path.sep)?target:null}catch{return null}}
function localJsonStore(name){return path.join(dataDir(),`lan-${name}.json`)}
async function readLanStore(name){const f=localJsonStore(name);if(!fs.existsSync(f))return[];try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return[]}}
async function writeLanStore(name,rows){fs.writeFileSync(localJsonStore(name),JSON.stringify(rows??[],null,2),'utf8')}
async function clearLanStore(name){const f=localJsonStore(name);if(fs.existsSync(f))fs.unlinkSync(f)}
function getDeviceId(){const f=path.join(dataDir(),'device-id');if(fs.existsSync(f))return fs.readFileSync(f,'utf8').trim();const v=crypto.randomUUID();fs.writeFileSync(f,v,'utf8');return v}
function startLocalServer(){server=http.createServer((req,res)=>{try{const u=new URL(req.url||'/','http://127.0.0.1');if(u.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify({ok:true,mode:'desktop-local',version:app.getVersion()}));return}const target=safePath(u.pathname);if(!target){res.writeHead(403);return res.end('Forbidden')}let file=target;if(u.pathname==='/'||!path.extname(target))file=path.join(appRoot(),'index.html');if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res)}catch(error){console.error('desktop local server',error);res.writeHead(500);res.end('Internal error')}});server.listen(0,'127.0.0.1',()=>{serverPort=server.address().port;createWindow()})}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});win.webContents.on('did-fail-load',(_e,code,desc)=>console.error('B-JOB desktop page failed',code,desc));win.loadURL(`http://127.0.0.1:${serverPort}/`)}
async function lanRequest(baseUrl,token,pathName,options={}){const response=await fetch(`${baseUrl.replace(/\/$/,'')}${pathName}`,{...options,headers:{...(options.headers||{}),'X-BJOB-LAN-Token':token,'Content-Type':'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`LAN request failed: ${response.status}`);return data}
async function lanPushSnapshot(baseUrl,token,snapshot){const names=Object.keys(snapshot||{}).filter(n=>LAN_STORES.includes(n));for(const name of names)await lanRequest(baseUrl,token,'/lan/store',{method:'POST',body:JSON.stringify({name,rows:snapshot[name]||[]})});return{ok:true,stores:names}}
async function lanPullSnapshot(baseUrl,token){const hello=await lanRequest(baseUrl,token,'/lan/hello');const stores={};for(const name of(hello.stores||[]))stores[name]=(await lanRequest(baseUrl,token,`/lan/store?name=${encodeURIComponent(name)}`)).rows||[];return{ok:true,data:stores}}

ipcMain.handle('desktop-info',()=>({version:app.getVersion(),dataDir:dataDir(),port:serverPort,root:appRoot(),lan:lanConfig,deviceId:getDeviceId()}));
ipcMain.handle('desktop-export-json',async(_e,payload)=>{const r=await dialog.showSaveDialog({title:'Экспорт базы B-JOB',defaultPath:`BJOB-backup-${new Date().toISOString().slice(0,10)}.json`,filters:[{name:'B-JOB backup',extensions:['json']}]});if(r.canceled||!r.filePath)return{cancelled:true};fs.writeFileSync(r.filePath,JSON.stringify({format:'bjob-json',version:2,createdAt:new Date().toISOString(),deviceId:getDeviceId(),data:payload},null,2),'utf8');const manifest=createBackupManifest(r.filePath,{deviceId:getDeviceId(),type:'bjob-json',version:2});fs.writeFileSync(`${r.filePath}.manifest.json`,JSON.stringify(manifest,null,2),'utf8');return{cancelled:false,filePath:r.filePath,manifestPath:`${r.filePath}.manifest.json`,manifest}});
ipcMain.handle('desktop-import-json',async()=>{const r=await dialog.showOpenDialog({title:'Импорт базы B-JOB',properties:['openFile'],filters:[{name:'B-JOB backup',extensions:['json']}]});if(r.canceled||!r.filePaths[0])return{cancelled:true};const file=r.filePaths[0],raw=JSON.parse(fs.readFileSync(file,'utf8'));if(!raw||raw.format!=='bjob-json'||!raw.data||typeof raw.data!=='object')throw new Error('Неверный файл базы B-JOB');const manifestFile=`${file}.manifest.json`;if(fs.existsSync(manifestFile)){const manifest=JSON.parse(fs.readFileSync(manifestFile,'utf8'));const verification=verifyBackup(file,manifest);if(!verification.ok)throw new Error('Резервная копия повреждена: контрольная сумма не совпадает')}return{cancelled:false,filePath:file,data:raw.data}});
ipcMain.handle('lan-start',async()=>{if(lanServer)return lanConfig;const token=crypto.randomBytes(24).toString('hex');const protocol=createProtocol({stores:LAN_STORES,readStore:readLanStore,writeStore:writeLanStore,clearStore:clearLanStore});const sync=createSyncProtocol({readJournal:()=>syncStorage.read(),appendOperations:ops=>{const existing=syncStorage.read();const ids=new Set(existing.map(x=>x.id));for(const op of ops)if(!ids.has(op.id))syncStorage.append(op)}});const onRequest=async req=>{const u=new URL(req.url||'/','http://bjob.lan');return u.pathname.startsWith('/sync/')?sync(req):protocol(req)};const result=await createLanServer({port:8787,token,onRequest});lanServer=result.server;lanConfig={enabled:true,address:result.address,port:result.port,token:result.token,url:`http://${result.address}:${result.port}`};return lanConfig});
ipcMain.handle('lan-stop',async()=>{if(lanServer)await new Promise(r=>lanServer.close(r));lanServer=null;lanConfig=null;return{enabled:false}});
ipcMain.handle('lan-status',()=>lanConfig||{enabled:false,address:localIPv4()});
ipcMain.handle('lan-push',async(_e,{baseUrl,token,snapshot})=>lanPushSnapshot(baseUrl,token,snapshot));
ipcMain.handle('lan-pull',async(_e,{baseUrl,token})=>lanPullSnapshot(baseUrl,token));
ipcMain.handle('sync-status',()=>({deviceId:getDeviceId(),pending:syncStorage?.read().length||0}));
ipcMain.handle('sync-export',async()=>{const r=await dialog.showSaveDialog({title:'Экспорт журнала синхронизации',defaultPath:`BJOB-sync-${new Date().toISOString().slice(0,10)}.json`,filters:[{name:'JSON',extensions:['json']}]});if(r.canceled||!r.filePath)return{cancelled:true};fs.writeFileSync(r.filePath,JSON.stringify({format:'bjob-sync-journal',version:1,deviceId:getDeviceId(),operations:syncStorage.read()},null,2),'utf8');const manifest=createBackupManifest(r.filePath,{deviceId:getDeviceId(),type:'sync-journal'});fs.writeFileSync(`${r.filePath}.manifest.json`,JSON.stringify(manifest,null,2),'utf8');return{cancelled:false,filePath:r.filePath,manifestPath:`${r.filePath}.manifest.json`}});

app.whenReady().then(()=>{syncStorage=createSyncStorage(dataDir());startLocalServer();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})}).catch(error=>console.error('B-JOB desktop startup failed',error));
app.on('window-all-closed',()=>{if(server)server.close();if(lanServer)lanServer.close();if(process.platform!=='darwin')app.quit()});
